### ISSUE TITLE
Add events for relevant Actions:

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#108]
Right now, there is only the catscale_updated event.

We need more events for every relevant change in catquiz:
- a test item is added or removed from a scale
- a testitem status is changed (within scale)
- a testitem model status is changed (from calculated to manually confirmed etc.)
- a new scale is created
- a new context is created

To implement, duplicate the catscale_updated event, in classes/events, change what is necessary to change and trigger them in the right places. Always trigger in the classes that are called, not from the interface!

**Comment by eynimeni** [comment]
added context updated event in addition
