### ISSUE TITLE
Listen to events and invalidate caches

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#109]
Right now, we listen to two events: catscale_updated from local catquiz & attempt_completed from mod_adaptivequiz.

We need to listen to more events in order to correctly invalidate caches.

The event observer is a great place for invalidating caches.

We need to invalidate the table caches every time:

- after an import (add import event)
- a test item is added or removed from a scale
- etc.

Also, we need to make sure we have no deleted questions in tests.

Listen to "question deleted" event and remove deleted questions from test items.

**Comment by eynimeni** [comment]
when caches already deleted in function (i.e. after db update), events are cached there, not in the observer

**Comment by eynimeni** [comment]
not sure if the wildcard in events.php line 30 is working correctly
