### ISSUE TITLE
Improve Feedback visuals

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#110]
Right now, feedback after a test is only text based and shows only person ability and the number of correctly and incorrectly answered questions per scale.

We should have different feedback for every case (ie for every test strategy. Feedback should correspond to what was tested) and need visual improvements. The screenshot below should be considered as example.

 In the cat quiz-model  in mod_adaptive it's already possible to add feedback for every scale, if below lower limit.

This feedback should be shown after the attempt. In the future, we will have different feedbacks for different results.

![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/7524621/5c10f0d5-0bfd-47eb-9b0b-9f17e4bd7019)

**Comment by davidszkiba** [comment]
- [ ] Show the custom attempt feedback per scale if the ability is below the threshold
