### ISSUE TITLE
Add List of calculations

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#113]
Calculations Page 70 in  https://cloud.wunderbyte.at/index.php/f/3327489

Every calculation should show up here. Add Event to calculation, should be triggered manually and via adhoc

**Comment by davidszkiba** [comment]
Here calculations are triggered: https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/develop/classes/catmodel_info.php#L60
