### ISSUE TITLE
Add unit tests to all calculations

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#114]
Unit tests exist already for some functions. We should have a complete calculation for whole complete calculations:

All Models should have tested item param calculations

- [x] 1 PL
- [x] 2 PL
- [x] 3 PL

We need tested person abilities:

- [x] 1 PL
- [x] 2 PL
- [x] 3 PL

**Comment by davidszkiba** [comment]
I added the tests. However, they just expect the value that is currently calculated (so they all pass), because I don't know the expected values yet.
