### ISSUE TITLE
enhance import (test items can also be added to a catscale)

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#119]
We should also have the possibility to add items to scales and sub scales (and, in the same step, add item params).

The logic would work like this:
- questions which exist on the platform can be identified via label (ID)
- if there is a catscaleid column, a testitem can be attributed to the given catscale.
- All the other columns of the other importer can be there as well -> in the same step, test items can be added.

**Comment by eynimeni** [comment]
should catscaleids be imported in the field together like '["idparentscale", "idsubscale"]' or should there be a new row for each scale in the csv? @georgmaisser
