### ISSUE TITLE
ticket AP-56

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#12]
The Testenvironments currently holds the templates, which are general settings, and the real testenvironments, which are linked to a mod_adaptivequiz instance. We want more information about these tests at one glance.

- [x] Add column "course" (depict course name), in DB it's the course id) on table on page manage_testenvironments.php
- [x] Add column "nr of questions" on table on page manage_testenvironments.php
- [x] Add column "nr of users" on table on page manage_testenvironments.php (how many people have already answered these questions in this course)
- [x] Add column with Names of the Teachers in a given course.

**Comment by eynimeni** [comment]
@davidszkiba recheck if this can be closed

**Comment by eynimeni** [comment]
![Screenshot 2024-04-08 at 12 19 49](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/9e303215-c68f-4939-9e0d-5a8191fbe35b)
 
recheck tests& templates table: 

- [ ] are columnnames correct?
- [ ] # users
- [ ] # questions
