### ISSUE TITLE
BUG: Default-Context wird bei Installation nicht angelegt

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#123]
Bei Installation wird Default-Kontext nicht angelegt, Bug ließ sich auf einem lokalen 4.1-System replizieren

(CAT-) Context muss angelegt werden und in der Datenbank händisch auf "default:true" gesetzt werden.

**Comment by georgmaisser** [comment]
Getestet zweimal Lokal & auf alise.wunderbyte.at

Default context wird angelegt. Bitte verhalten noch einmal testen & muss ev. versucht werden auf der Instanz, wo der Fehler auftritt, direkt zu Debugger.
