### ISSUE TITLE
BUG: Textuelles Feedback bei den Kurseinschreibungen wird nicht angezeigt

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#124]
Das Text-Feedback wird trotz erfüllter Bedingung nach Test nicht angezeigt (Kurseinschreibung erfolgt aber).

![Bildschirmfoto 2023-09-02 um 12 52 36](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/69e5ca3a-2b5c-4ff6-8484-e9ece717cff9)

**Comment by georgmaisser** [comment]
- [ ] HTML Editor in feedback
- [ ] Möglichkeit Detailfeedback für gewisse Bereiche zu definieren 
- [ ] Möglicherweise auch Einschreibung in unterschiedliche Kurse je nach Person Ability, ev. Einschreibung über globale Gruppen

**Comment by ralferlebach** [comment]
Gelöst
