### ISSUE TITLE
BUG: Bei Berechnung „verschwinden“ Fragen aus dem Test, vmtl. Werden nur Status-4-Fragen gezogen

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#128]
Klickt man im Backend "Calculate", werden fortan die berechneten Fragen nicht mehr in einem Testlauf gezogen.  Vermutlich wird bei  der Berechnung der Status geändert und der neue Status im CAT-Test (noch) nicht berücksichtigt?

**Comment by davidszkiba** [comment]
Beim Ziehen der Fragen wird im Moment der Status nicht berücksichtigt.
Ich habe ein Quiz ausgeführt, bevor ich den "Calculate" button geklickt hab, und auch danach. Ich habe die "debug info" verglichen und daran sieht man, dass 2 von den jeweils 10 Fragen die gleichen sind.

**Comment by davidszkiba** [comment]
Der Status wird jetzt berücksichtigt. Die item parameter von importierten Fragen werden beim einer Berechnung nicht mehr überschrieben.
