### ISSUE TITLE
Quiz feedback

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#131]
- [x] Allow feedback to be shown to only teacher / only student or both
- [x] New page that provides a clickable list of past attempts
- [x] New page that shows the detailed feedback of a past attempt
- [x] #160
- [x] #161

Questions:
- ~~Should the decision if a feedback is shown to teacher or student be hardcoded or set via quiz settings? Are there examples for what feedback belongs to which category?~~ -> See comment below
- ~~To keep track of past attempts, we need to save them to the DB. Should we use a new table or is there a place where we can add this information?~~ -> See #140

**Comment by davidszkiba** [comment]
@georgmaisser Was meinst du zu dem?
> Should the decision if a feedback is shown to teacher or student be hardcoded or set via quiz settings? Are there examples for what feedback belongs to which category?

Bis jetzt haben wir nur beim "debuginfo" Feedback die Einstellung, dass es nur für gewisse Rollen sichtbar ist = und zwar direkt im code. Ich nehme an es reicht, wenn wir das bei jedem Feedback so machen?
Die Alternative wäre wohl, dass man in den Quizsettings für jedes Feedback extra die Rollen auswählen kann.

**Comment by georgmaisser** [comment]
Ich würde das so vorschlagen: Bei der Anzeige von Feedback sollte es einen Teacher Bereich u einen Student Bereich geben. Student Bereich sehen alle, für Teacher Bereich bracht ist die capability (has_capability) aus access.php. Das soll unabhängig davon sein, ob das FB direkt nach dem Quiz oder über den attempts table später angezeigt wird.

(ich werde noch einen shortcode machen, wo letzter Attempt, letzte Attempts, letzte Attempts nur aus einem Kurs, usw. angzeigt werden können)
