### ISSUE TITLE
AP-59 Calculate Contexts

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#14]
- [x] Create scheduled task to run through all contexts and recalculate values.
- [x] To be able to choose the contexts which should be recalculated, we need a marker on a context.

**Comment by davidszkiba** [comment]
Instead of adding a new marker field, we decided to use the context starttime and endtime as implicit marker: if a context is currently active, the scheduled task will update its parameters.
