### ISSUE TITLE
Add local_catquiz_attempts table

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#140]
After each test attempt, the feedback should be saved 

If we want to filter the attempts according to some values, those values should be put into their own column.
E.g.:

- userid
- starttime
- endtime

In this line we call the feedback generator with all required data in the `$context` variable: https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/develop/classes/output/attemptfeedback.php#L139

I think it would be best to store the data just before this call. This way, at a later point in time, we can retrieve the data from the DB and call the feedback generators exactly the same way.

Maybe its easiest to just store the $context object as json? And in addition, extract the values by which we want to filter and add them to separate columns?

**Comment by eynimeni** [comment]
columns to be displayed:

- scaleid, 
- contextid, 
- courseid
- attemptid, 
- instance id (not cmid) of mod adaptive quiz (table: m_adaptivequiz col id)
- user id
- teststrategy, 
- status col
- total num of testitems
- used testitems
- personabilities before,
- personabilities after
- starttime
- endtime
- json all data


cols for table:
- personabilities difference

**Comment by davidszkiba** [comment]
@eynimeni issue #131 depends to some extent on this one. If you could prioritize the following columns then I could start working on that issue sooner:

- scaleid
- contextid
- courseid
- attemptid
- instance id (not cmid) of mod adaptive quiz (table: m_adaptivequiz col id)
- user id
- teststrategy
- json all data (most important)

Thanks :)
