### ISSUE TITLE
Update-Probleme

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#145]
Nach dem Update auf
* mod_adaptive: 2023052800
* adaptivequizcatmodel_helloworld: 2023082700
* local_catquiz: 2023091900
* local_wunderbyte_table: 2023091900

kommt es zu folgendem unerwartetem Verhalten:

1. Menü-Punkt CAT-Manager verschwunden
(sowohl im lokalen Moodle 4.1 als auch im Web-Moodle 4.0)

![Bildschirmfoto 2023-09-20 um 21 19 32](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/2e8dc21d-c74a-49db-9026-145a5cd25bd4)
(auch Cache löschen sowie Logout und Login bringt hier nichts)

2. Anzeigen einer CAT-Skala führt zu Speicherüberlauf im Web-Moodle (Vers. 4.0.15+)

![Bildschirmfoto 2023-09-20 um 21 36 49](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/8d5cd24e-e76b-487e-92ee-cc342db854c1)

3. Weiter-Button nach Test-Rückmeldung führt zu einem Fehler (und anschließend wieder zurück auf die Rückmeldungsseite, statt in den Kurs zurück)

![Bildschirmfoto 2023-09-20 um 21 35 10](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/0aa2399e-e43e-4066-aace-cd53da621a9a)

![Bildschirmfoto 2023-09-20 um 21 34 59](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/2f464a73-a57c-432b-8c0c-70e0cd46c407)

4. Plugin-Verzeichnisse sind nicht durch index.php vor Fremdeinsicht geschützt.
(aktuell ist das gut, weil ich sonst kaum ins CAT-Management käme, aber so grundsätzlich ist das natürlich ein Sicherheitsproblem)

![Bildschirmfoto 2023-09-20 um 21 36 04](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/59e4c898-e591-4093-92c1-222c805a2041)

**Comment by ralferlebach** [comment]
Aufgrund von Fehler 3. kann jetzt auch kein Test bzw. Kurs mit einem Test gestartet werden. 

@georgmaisser @davidszkiba @eynimeni Könnt ihr da einmal (gern auch mit den Admin-Zugangsdaten) reinschauen, was da los ist?

**Comment by davidszkiba** [comment]
Ich hab mir Fehler 3 mal angesehen aber kann ihn leider nicht reproduzieren - weder lokal noch auf alise. Vielleicht hängt das mit der Moodle Version zusammen? Lokal bin ich im MOODLE_401_STABLE git branch.

**Comment by ralferlebach** [comment]
Der Fehler tat nach dem ersten vollständigen Testdurchlauf auf (inkl. Feedback), seitdem lässt sich kein ModAdaptive mehr starten.

Hast du einmal einenadaptiven Test zusammenstellen und "durchspielen"?

Ich kann dies leider auf meinem lokalen Moodle nicht, weil:
5. Fragen hinzufügen im Backend funktioniert nicht:
Über manage_catscales.php -> anzeigen gelange ich hierhin (alte Ansicht)
![image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/9b65711e-2542-4d22-8769-82e5d965761c)
und dann unter "Tstitems hinzufügen" passier nichts mehr.

und über "Fragen" -> Skala -> "Testitems zu CAT Skalen hinzufügen" wird keine QuestionBank angezeigt:
![image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/87415401-d5fa-4ded-ab20-b0ba87117e7b)

**Comment by ralferlebach** [comment]
Kann ich ein Version-Bump der letzten lauffähigen Version bekommen, sodass ich unsere AdaptiveQuizzes in unserem Moodle erst einmal schnell wieder zum Laufen bekomme?

**Comment by ralferlebach** [comment]
Ist gelöst.
