### ISSUE TITLE
Possible bug: events remains after plugin has been re-installed

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-local_catquiz#153]
Plugin has been re-installed but previous events were preserved:
![image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/24c6aba1-c280-472f-951c-dbeef07dc7ad)
It looks like an incorrect behaviour

**Comment by eynimeni** [comment]
behaviour is alright
