### ISSUE TITLE
infer all subscales: selection of scale

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#162]
Moved from #85 to here:

Select relevant subscales via
- [ ] min (left) or right (max) inflection point
- [ ] min/max difficulty of all items
- [ ] threshold left/right in test information curve
- [ ] user defined

**Comment by davidszkiba** [comment]
@ralferlebach hast du schon einen Algorithmus für diese Auswahl?

**Comment by eynimeni** [comment]
andere lösung gefunden - testpotentialfunktion wird nun genutzt
