### ISSUE TITLE
manually set params (itemdiff, guessing, discrimination)

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#166]
for questions table:
local/catquiz/manage_catscales.php?#lcq_questions

- [x] use wb_table actionbutton with modal to set values
- [x] display modal with fields to save data
- [x] automatically set status to updated when changed
- [x] form in detailview
- [ ] use same form as in detailview called for table action column edit button
- [ ] reload table with new cache after submission (event)
- [ ] make sure, params are updated after submission

**Comment by davidszkiba** [comment]
This functionality is already provided: the page that is shown when clicking on the "details view" action button contains the same form.
