### ISSUE TITLE
build charts according to mock up

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#167]
fix error on manage_catscales 

![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/f6639886-fb21-4d89-ad80-07203a809fd3)

**Comment by georgmaisser** [comment]
I think this error is not relevant anymore?

@eynimeni you can talk to @davidszkiba how to include graphs. please look at the template pdf to see which charts should be included. you can talk to Ralph as well to get the required data.

**Comment by eynimeni** [comment]
completed
