### ISSUE TITLE
Recalculation of items should only take place when there are new tests.

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#168]
Right now, recalculation is triggered no matter if there are new test items or not.

(Not 100% sure if this Is implemented already)

**Comment by georgmaisser** [comment]
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/7524621/58acdbe2-fb22-4acd-8ff5-34fe3741c773)

**Comment by georgmaisser** [comment]
After review, it seems that this is already done. But the numbers don't seem to be 100% correct. For A09 on Alise Wunderbyte, two questions have been recalculated, but only one question was used in a new attempt. In A10, it says that 6 questions have been recalculated, but only three have been played and there are only four in total. It seems that the counter always counts twice.

**Comment by davidszkiba** [comment]
@georgmaisser I'm working on this in #155 - it is not finished yet. I will check the numbers.
