### ISSUE TITLE
Test-Daten: Items, Personen, Responses

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#174]
[items.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12868008/items.csv)
[persons.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12868014/persons.csv)

(Achtung, neue Daten!)
[responses 1PL.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12868323/responses.1PL.csv)
[responses 2PL.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12868325/responses.2PL.csv)
[responses 3PL.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12868326/responses.3PL.csv)

[php-Dateien.zip](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12868408/php-Dateien.zip)

**Comment by ralferlebach** [comment]
Es gab einen Vorzeichenfehler bei den Responses. Bitte die neuen Dateien nutzen.

**Comment by davidszkiba** [comment]
Danke @ralferlebach. Nur um sicherzugehen, dass ich das richtig verstehe und auch um es schriftlich zu haben:
ihr habt zuerst die person abilities und item parameter festgelegt und daraus ein passendes Antwortmuster generiert.
Und ich mach es jetzt in die andere Richtgung:
Ich nehme an, dass die item Paramter so stimmen, und überprüfe, ob ich mit den angegebenen Responses auf die angegebe person ability komme. Korrekt?

**Comment by ralferlebach** [comment]
Korrekt.

Anbei ein neues Set an Daten, die auch Philipp-geprüft sind. Dafür haben wir auch recht gute Ergebnisse erhalten - im Sinne von korrelierenden Datenreihen. Wir werden nicht von 1:1-Zusammenhängen ausgehen können.

Bitte nun also diese Daten verwenden:

[items.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12874047/items.csv)
[persons.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12874048/persons.csv)
[responses 1PL.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12874049/responses.1PL.csv)
[responses 2PL.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12874050/responses.2PL.csv)
[responses 3PL.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12874051/responses.3PL.csv)


[php-Dateien.zip](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12874037/php-Dateien.zip)

**Comment by ralferlebach** [comment]
@davidszkiba : Wenn du magst, können wir uns morgen früh 8 Uhr (Ortszeit) auch noch einmal kurzschließen, bevor wir frühstücken und zum WB HQ rübermarschieren. Dort werden wir mit Georg bis 10 Uhr / 10.30 Uhr die Oberflächen besprechen und danach können wir auch wieder uns besprechen.

D.h. du könntest auch schon früh am Tag (Ortszeit) noch einmal Fragen loswerden oder Philipp mit Rückfragen bombardieren.

Was meinst du?

**Comment by davidszkiba** [comment]
Super, dann werde ich die neuen Dateien verwenden. Ich glaub dann sollte das eigentlich klar sein, aber vielleicht sprechen wir doch nochmal um 8:00 kurz. Danke
