### ISSUE TITLE
Beim Import Context neu erstellen falls noch nicht angelegt

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#176]
for csv import: 
- [x] check if field context is empty
- [x] if empty, check given scales: select parent scale if given, else scale
- [x] create context: use values from default context but set new contextid, and use autocontext_scalename_scaleid_usertime as naming convention
- [x] for following lines, if context is empty, check if context is already newly created (within same import) for this particular scale, if so, assign same context
- [x] if there is no context for a (parent-) scale, (and context id is empty) -> create new context (see above)

**Comment by georgmaisser** [comment]
- [ ] Also when manually creating a new parent scale, create context for it.

**Comment by eynimeni** [comment]
dann sollten wir in der db bei scale die contextid hinterlegen - oder wie ist die beste zuordnung?
