### ISSUE TITLE
Range Personability, N iterations, Schrittweite bestimmen

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#186]
- [x] CONST:PERSONABILITY_LOWER_LIMIT and 'PERSONABILITY_UPPER_LIMIT' are defined in lib.php 
- [x] Use filter function to limit calculated ability to that range

**Comment by davidszkiba** [comment]
@eynimeni The second point is done in #214 and will be merged soon
