### ISSUE TITLE
strings dictionary

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#226]
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/41062c81-25b7-4e17-932e-9877fc13fb19)

**Comment by eynimeni** [comment]
please make sure to use the terms as defined in the dictionary 
dictionary should be kept update here

**Comment by eynimeni** [comment]
@ralferlebach 
ich bräuchte noch:
item difficulty : Schwierigkeit des Elements?
likelihood: Wahrscheinlichkeit?
Testitem Dashboard: Fragen Ansicht?

**Comment by ralferlebach** [comment]
Das ist für den Bereich CAT-Manager?

item difficulty : Item-Schwierigkeit
item discrimination: Trennschärfe des Items
guessing parameter: Rate-Wahrscheinlichkeit
likelihood: Likelihood
Testitem Dashboard: Item-Übersicht

@davidszkiba : Hatten wir uns auf "Fragenschwierigkeit" oder "Item-Schwierigkeit" geeinigt?
Im CAT-Manager-Backend halte ich "Item" für angemessen, wir arbeiten aber auch dort sehr viel mit "Frage"... daher evtl. auch hier besser "Frage" statt "Item" verwenden.

Was meint ihr?

**Comment by davidszkiba** [comment]
Phew.. Ich finde das auch etwas verwirrend wenn es zwei Begriffe gibt. Ich denke außerhalb des CAT Managers sollte es auf jeden Fall "Frage" sein, innerhalb kann es aber trotzdem beide Begriffe geben, da es ja nicht das gleiche ist, oder?
Wenn ich es richtig verstehe, dann ist ein Item eine Frage *plus* Parameter. Also je nach Kontext muss man entweder von Fragen (zB "Fragen zur Skala hinzufügen") oder Items (zB "Alle Items neu berechnen") sprechen.

**Comment by davidszkiba** [comment]
@ralferlebach Ich erstelle gerade ein Plugin Setting und bräuchte auch noch Strings zum Beschreiben von

- dem Namen des `$tr` Parameters, der für trusted regions den Faktor angibt, mit dem der Standardfehler multipliziert wird.
- eine Beschreibung des `$tr` Parameters

**Comment by ralferlebach** [comment]
Multiplikator für Vertrauensbereich

"Der Multiplikator für den Vertrauensbereich gibt das Vielfache der Standardabweichung um den Mittelwert an, um den eine Parameterschätzung einer Person oder Item-Schwierigkeit erwartet wird. Wird der Multiplikator für den Vertrauensbereich zu hoch gewählt, besteht die Gefahr, dass der numerische Algorithmus instabil wird und bei schwieriger Datenlage unzuverlässige Werte liefert. Default-Wert ist ein Multiplikator von 3.0, was statistisch 99,9 Prozent aller zu erwartenden Fälle mit einschließt einschließt."

**Comment by ralferlebach** [comment]
In der Kommunikation mit Lernenden und Lehrenden verwenden wir "Fähigkeitswert" (anstelle von "Fähigkeits-Score").

Score kann auch auch als ein Punktwert verstandenwerten, es sind aber keine klassischen Punkte.
