### ISSUE TITLE
add participationhistory chart to feedback

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#228]
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/cac4bb84-e21c-4f7e-88ba-add134bceb1f)

**Comment by davidszkiba** [comment]
Auf gleiche Abstände achten

**Comment by eynimeni** [comment]
update
- [ ] check 0/null value for time: not 1.1.1970 but (unknown / not displayed)
- [ ] distances in timebased charts should be equal to time passed
