### ISSUE TITLE
Make defCAT strategy return expected values

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#229]
The teststrategy to infer the lowest skill gap should yield the same result as in the example data provided by @ralferlebach 

- [x] Calculate test potential: add function get_testpotential() to catscale class.
- [x] Calculate test information: add function get_testinformation() to catscale class.
- [x] Implement abort condititon: tp + ti < 1 / (max standarderror)** 2 and keep track of active scales
- [x] Change the algorithm: instead of iterating over the questions once, iterate over each scale first.

**Comment by ralferlebach** [comment]
Ist das Nachberechnen "unberechenbarer Skalen" (f = 0 oder 1) bereits implementiert, sodass das Endergebnis dieser auf den aktuellsten Stand der übergeordneten Skalen basiert?

(Hatte vorgestern in der letzten Version den Fall, dass genau das noch nicht geschehen war und dadurch das Testergebnis stark verzerrt wurde.)

**Comment by davidszkiba** [comment]
@ralferlebach das überprüfe ich jetzt nochmal. Wie kurz besprochen, bekomme ich allerdings mit dem neuen 07_teststrategie_tester.php Skript andere Werte als noch im Jänner. Bzw sind die Werte am Ende gleich, aber die Reihenfolge der Fragen unterscheidet sich. Ich hänge 2 CSVs vom alten und neuen Skript für die jeweils erste Person P000000 an.

[SimulationSteps defCAT 2024-01-12 12-32-52_p000000.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/14348415/SimulationSteps.defCAT.2024-01-12.12-32-52_p000000.csv)



[SimulationSteps defCAT 2024-02-19 16-04-07_P000000.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/14348419/SimulationSteps.defCAT.2024-02-19.16-04-07_P000000.csv)

**Comment by davidszkiba** [comment]
@ralferlebach Auch für Person P000642 unterscheiden sich die Werte zwischen der älteren und neueren 07_teststrategie_tester.php Version.
Und hier gibt es leider auch beim Endergebnis kleine Abweichungen.
Ich komme für diese Person auf die Werte, die von der älteren Version erzeugt wurden.
Ich hänge die beiden Outputs an.
[SimulationSteps defCAT 2024-02-19 16-04-07.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/14447447/SimulationSteps.defCAT.2024-02-19.16-04-07.csv)
[SimulationSteps strenCAT 2024-01-25 13-52-04.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/14447452/SimulationSteps.strenCAT.2024-01-25.13-52-04.csv)
Man sieht, dass in der neueren Version Skala Sim/B/B03 nach Schritt 8 deaktiviert wird, was in der älteren Version nicht passiert. Evtl ist das der Grund für die Abweichungen?
