### ISSUE TITLE
Deprecation Warning auf alise.wunderbyte.at-Server

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#245]
Während des Testdurchlaufs in 
https://alise.wunderbyte.at/course/view.php?id=9

kommt es nach einigen beantworteten Testfragen zu folgender Warnung und folgendem Fehler:
<img width="1323" alt="Bildschirmfoto 2024-01-19 um 16 08 07" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/920432de-18d6-49c8-b586-6d81dfd7c6e1">

**Comment by davidszkiba** [comment]
Die Warnings sollten mit 94f35b84 behoben sein
