### ISSUE TITLE
Test läuft nicht an auf ALiSe-LTI-Server

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#246]
Neu angelegter Test auf neu angelegtem System bricht mit folgender Fehlermeldung ab:

<img width="811" alt="Bildschirmfoto 2024-01-20 um 16 11 06" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/51b27a8f-f51f-445a-a079-cd935f0ddad2">

auch nach erneutem Bearbeiten der Testeinstellungen:

<img width="830" alt="Bildschirmfoto 2024-01-20 um 17 14 59" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/ea6f75a0-7780-46d9-8261-b9e04c74c1fc">

**Comment by davidszkiba** [comment]
Ist mit d5ca714 behoben
