### ISSUE TITLE
Einzuschreibende Kurse werden nicht angezeigt 

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#247]
In den Einstellungen im mod_adaptive werden Kurse, für die die bearbeitende Person nicht als Trainer eingeschrieben ist, nicht angezeigt und auch nicht gespeichert.

Das wird zum Problem, wenn mehrere Lehrende mit dem Test in einem Kurs arbeiten oder ein Adminstrator Unterstützung leistet und die Einstellungen aufruft und aktualisiert.

<img width="875" alt="Bildschirmfoto 2024-01-20 um 16 14 06" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/cd804899-aa4e-4de3-860d-154868f9ae93">

Bitte daher nur die Auswahl der Kurse eingrenzen, nicht aber schon gesetzte Kurse aus den Einstellungen wieder streichen.

**Comment by eynimeni** [comment]
sollte jetzt passen
