### ISSUE TITLE
Ergebnis des Testversuchs führt zu Fehler

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#253]
![grafik](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/ee21c1b0-fc5a-458d-b7d7-8fb4035f97f5)

Jana hat einen Test-Run durchgespielt und folgendes "Ergebnis" zurückgekehrt bekommen.

Ich versuche, das Problem zu reproduzieren.

**Comment by eynimeni** [comment]
wir haben das senden von emails bei uns getestet, das scheint gut zu funktionieren. 
das email das raus geht ist die benachrichtung, dass in einen kurs eingeschrieben wird. das sollte passieren, wenn in den entsprechenden feedbacksettings die checkbox angecheckt ist und in den user einstellungen bei nachrichten für dieses plugin email eingestellt ist: z.B.:
https://alise.wunderbyte.at/message/notificationpreferences.php?userid=2
![Screenshot 2024-01-23 at 12 08 52](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/46649053-29ab-4520-8985-c2c1b4f59f22)

es kann natürlich sein, dass bei eurem server die ausgehenden mails noch nicht so funktionieren. ihr könntet in den obigen einstellungen web aktivieren, dann seht ihr ob das funktioniert. falls der fehler wieder auftritt oder weiter besteht, bitte melde dich diesbezüglich nochmals!

**Comment by ralferlebach** [comment]
Ist gelöst.
