### ISSUE TITLE
Implement new Testsettings Mock-Up

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#262]
<img width="595" alt="Screenshot 2024-01-24 at 16 48 31" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/c89133b8-09ac-4273-9901-4ca32e04c4cd">

**Comment by ralferlebach** [comment]
Sieht sehr gut aus.

Es gibt allerdings noch kleinere Fixes und Verbesserungswünsche: https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/issues/295, https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/issues/296 und (ist vermutlich eine größere Sache) https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/issues/297.

Ich schließe den Issue, das Problem ist erledigt.
