### ISSUE TITLE
Aktivitätstext erscheint im mod_adaptive (immer) doppelt, aber nicht auf Kursseite

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#263]
<img width="815" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/56ef3c92-f6d1-4b1d-b15f-511f8e537285">

<img width="829" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/8d4cf1a1-ed9a-48ca-9efb-3f70099ecb7f">

<img width="856" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/ce68f681-5038-4460-bdea-16a5801dea6e">

**Comment by davidszkiba** [comment]
@ralferlebach kann das geschlossen werden?
