### ISSUE TITLE
Teststrategie "Stärken-orientierter CAT"

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#265]
[SimulationSteps strenCAT 2024-01-25 12-53-08.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/14052578/SimulationSteps.strenCAT.2024-01-25.12-53-08.csv)

[Quelltext.zip](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/14052613/Quelltext.zip)

**Comment by ralferlebach** [comment]
@davidszkiba:

Ich habe ein GitRepo für meine CodeBase angelegt und dich als Collaborator eingeladen. So bleiben in Zukunft Codeänderungen nicht verborgen.
https://github.com/ralferlebach/CAT-Simulation

Bezüglich des Ausschlusses wird bereits auf die min. Itemanzahl geprüft. Hier kann aber statt > auch >= genutzt werden (erspart die n_max+1-te Frage):
Zeile 154:
                if ($N_calc[$scale_temp] >= $N_min) {

**Comment by davidszkiba** [comment]
Perfekt, danke

**Comment by eynimeni** [comment]
covered in #330
