### ISSUE TITLE
Kurseinschreibung und Einstellung mod_adaptive (ohne Kursberechtigung)

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#269]
Habe im Referenz-Test alle Kurs-Einschreibungen (mit entsprechender Berechtigung) angelegt und dann die Berechtigungen gelöscht.

Erster Testdurchgang hat erwartungskonform mich in Kurs A02 eingeschrieben, der nächste hätte mich in A07 einschreiben sollen, aber das ist nicht passiert.

<img width="1059" alt="Bildschirmfoto 2024-01-25 um 20 45 14" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/68e4d981-9769-4354-90f1-d1f899acd1c1">
<img width="889" alt="Bildschirmfoto 2024-01-25 um 20 45 23" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/4b94dcf6-ff78-4cb9-98e8-09f20ec55565">

Einstellungen des Tests gescheckt und die Kurseinschreibungen für alle Kurse, in die ich nicht (mehr) eingeschrieben war, waren verschwunden, z.T. mit kompleeten Verlust der Anzeige in mod_adaptive (2. Bild)

<img width="850" alt="Bildschirmfoto 2024-01-25 um 20 45 59" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/745619cd-b007-4923-821d-9c3c70eece6e">
<img width="782" alt="Bildschirmfoto 2024-01-25 um 20 46 13" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/40993e46-a5ba-4ebe-a287-7ee5ba403995">

**Comment by eynimeni** [comment]
danke!

**Comment by ralferlebach** [comment]
Scheint jetzt stabil zu laufen.
