### ISSUE TITLE
Importer überschreibt gleichlautende Skalen, anstatt neuen Skalen-Baum anzulegen

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#273]
Beim Import auf alise.wunderbyte.at mit foldender Datei

wurden die bestehenden Skalen der Globalskala Sim (z.B. A01) mit den Items befüllt, anstatt wie in der Datei spezifiziert, eine neue Globalskala "SimV2" anzulegen und den Skalenbau darunter aufzubauen.

Für ALiSe werden wir sehr wahrscheinlich in den untergeordneten Skalen ebenso Namensdopplungen haben, eine Identifikation ist somit nur über den gesamten Pfad oder zumindest nur mittels Globalskala sinnvoll.

Die Zuordnungspriorität sollte daher entsprechend der abnehmender Eindeutigkeit sein:
1. Skalen-ID (Nummer)
2. Skalenbaum (Globalskala als Unique)
3. Einzelskalenname, wenn 1 und 2 nicht angegeben und Skalenname nur einmal in Datenbank vorhanenden.

**Comment by ralferlebach** [comment]
[export_CATscales V2.csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/14084512/export_CATscales.V2.csv)

**Comment by ralferlebach** [comment]
Ist das schon gelöst?

**Comment by eynimeni** [comment]
Ad 3)
Wenn Skala 1x vorhanden ist, kann es ja trotzdem sein, dass wir die Skala neu erstellen möchten. 
Das Matching passiert also
1. id
2. name 
2. a) name nicht gefunden : neu anlegen (ggf. mit übergeordneten skalen)
2 b) name gefunden: 
2b1 parentscales von gefundenem namen sind identisch mit importiertem item: in best. skala item hinzufügen / updaten
2b2 parentscales von gefundenem namen sind nicht identisch mit importiertem item: neues item und bisher unbekannte skalen werden angelegt
2b3 keine parentscales vorhanden

ad 2b3:
Hier gibt es wieder zwei Fälle:
2b3a: Fehler
2b3b: Globalskala soll angelegt werden

Wir brauchen also eine Unterscheidung. 
Das Matching über den Marker, ob die Column "parentscalenames" vorhanden ist erscheint uns hier bei näherer Überlegung zu unsicher/fehleranfällig. 

Folgender Vorschlag:
Normalerweise kommt der Fehler.
Will man ein Item direkt einer Globalskala zuordnen, muss man diese Skala vorher im Manage Catscales Dashboard anlegen. 
Optional könnten wir noch einen Key definieren zB "parent", "global" oder "0" der in der "parentscalenames" Spalte übergeben werden kann. 

Was meinst du @ralferlebach ?

**Comment by eynimeni** [comment]
sorry, dass das etwas länger gedauert hat. 
wir schauen jetzt auch, dass wir alle fälle automatisiert testen, dafür hab ich die logik auch nochmal zusammen geschrieben: 

1) Scaleid is set:
	1 A: scaleid corresponding to given scale in db -> assign to corresponding scale:
	- no matter if scalename & parentscalenames are given (same behaviour if they are correct or incorrect)
	1 B: if scaleid was not found -> error
2) Scalename is set (no id):
	2 A: parentscalenames is set 
		2 A 1: parentscalenames lead to existing location of scale with scalename-> update item in tree
		2 A 2: parentscalenames lead to new location of scale -> create scale(s), create & assign item
		2 A 3: parentscalenames is set to “0” -> create new root/parent scale 
	2 B: parentscalename is not set -> error
3) No id, no scalename -> error

**Comment by davidszkiba** [comment]
Assuming that tests are positive
