### ISSUE TITLE
update alise.wunderbyte.at to settings of wup lti server

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#282]
Moodle 4.3
PHP 8.2.7
Plugins aktuell
DB: MariaDB 10.11

**Comment by davidszkiba** [comment]
@mona-shakiba maybe this would be a good candidate to try using ansible?

**Comment by davidszkiba** [comment]
was done on alise2.wunderbyte.at
