### ISSUE TITLE
Maximal merkwürdiger MySQL-Fehler

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#286]
Angeblich wird ein BigInt als multibyte-utf-String behandelt.

Ort: moodle.alise.uni-wuppertal.de
aktuelle local_catquiz-Version.

<img width="850" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/975af581-a5e6-4541-8dd8-fcbdd033ce1f">

**Comment by ralferlebach** [comment]
Vermute den Fehler gefunden zu haben:

Da in local_catquiz_tests gelöschte mod_adaptive - Tests nicht ebenso gelöscht werden, kommt es zu Dateninkonsistenzen:

<img width="1101" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/78569a44-9a19-4aad-9d84-5a94c53b0e98">
<img width="834" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/4c9d516b-8f99-40a9-acab-21259a0c7a21">

Löschen der nicht mehr benötigten Einträge und Setzen der componentid auf 6 in Eintrag-ID 15 machte den mod_adaptive-Test 6 wieder zugänglich.
<img width="795" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/9e683996-e121-4ffe-8266-d37b0036530c">

Allerdings fehlt jeglicher Eintrag zu Test 7, der durch ein Duplizieren von Test 6 zustande kam.

**Comment by ralferlebach** [comment]
Offenbar wird von der MOODLE-API bei

eine Collation auf utf-multibyte durchgeführt.

Habe Zeile 484 in testenvironment.php geändert zu:
$equal = " WHERE 'componentid' = :componentid";

Funktioniert jetzt.

**Comment by davidszkiba** [comment]
@ralferlebach ich denke die eigentliche Ursache ist, dass deine Datenbank nicht utf8 sondern latin-1 verwendet. Hier wird beschrieben, wie du die Datenbank auf utf8 ändern kannst: https://docs.moodle.org/403/en/MySQL_full_unicode_support
Davor kannst du ein DB Backup machen (das sollte mit `mysqldump` möglich sein).

**Comment by ralferlebach** [comment]
Und hier vom LTI-Server (neu):

<img width="1107" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/32308adc-36c8-4d44-9eb6-8c2d92f62041">

**Comment by ralferlebach** [comment]
Moodle 4.0 (upgedatet von 3.11)
<img width="828" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/23e1e793-9de2-4b2d-9f13-d5eda3fe170f">

Moodle 4.3 (frisch)
<img width="998" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/d8f047a5-feea-4311-99af-11412b526484">

Es scheint jedoch nicht an der Datenbank-Definition zu liegen:
<img width="619" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/558b855e-b315-412a-8b3e-b16664730179">
<img width="762" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/e6ba0ad6-c57b-41c6-9460-ca6de115b015">
vs.
<img width="578" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/3eb6ecb2-7b03-4c13-8ced-b3800ca85922">
<img width="876" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/9fec9c83-0b46-44af-907f-8d50751715d6">

Auch in der Moodle-Config lässt sich kein Unterschied erkennen:
<img width="489" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/f9147096-0fe6-483b-9977-500043fd2fac">
vs.
<img width="357" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/af2eb989-609d-4cb2-9c5b-6b33ba334202">

An PHP scheint es nicht zu liegen, an der Moodle-Version scheint es auch nicht zu liegen, am Statement scheint es nicht zu liegen, bleibt die MariaDB-Version. 10.3.39 vs. 10.11.4

**Comment by davidszkiba** [comment]
Ist behoben worden
