### ISSUE TITLE
Ansicht Test und beantwortete Fragen

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#288]
render questionpreview in separate tab (not as part of in personabilities)
darstellung chronologisch nach quizverlauf
answers don't have to be displayed

**Comment by ralferlebach** [comment]
#294 sieht für die Fragenansicht nun eine eigenständige Seite vor - und ich denke, das ist auch aus Nutzendensicht die gescheiteste Lösung.

**Comment by eynimeni** [comment]
render questionpreview on new page not in personabilities

**Comment by eynimeni** [comment]
Offene Fragen:
für wen soll der Link sichtbar sein? Ist es wirklich Teil des Teacherfeedbacks, wie im pdf von #294 angegeben?
Oder sollen das die Studierenden sehen können?

Vorschlag:
Wir nutzen die questionssummary (Die Auswertung wieviele Fragen richtig, wieviele falsch sind) in einem eigenen Tab und zeigen dort den Link an zu einer neuen Seite mit der Fragenübersicht (ohne Beantwortungen) an?

**Comment by ralferlebach** [comment]
![Image](https://github.com/user-attachments/assets/13ee9550-9d8e-4974-a254-20fdf42415bd)
Als Icon oder als Link bei Fragenummer oder/und Name.

**Comment by eynimeni** [comment]
- [ ] Quizsetting ob Frage angezeigt werden soll

- [ ] In Tabelle mit Übersicht über gespielte Fragen soll der Fragenname als Link (Button) zur Fragenansicht führen, idealerweise als nachgeladenes Modal - wichtig ist, nicht alle Fragen gleich zu rendern.

- [ ] Außerdem ein Fallback falls Fragenname leer ist die Questionid

**Comment by ralferlebach** [comment]
Optionen in den Quiz-Settings like:
![Image](https://github.com/user-attachments/assets/24eb91a2-aa54-4032-8dfc-60c0de8aabe5)

**Comment by eynimeni** [comment]
Geschätzter Aufwand: 3 Tage

**Comment by eynimeni** [comment]
duplicate #445
