### ISSUE TITLE
Fehlermeldungen und Testabbrüche in Feldtestung (zahlreich)

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#293]
Trotz vorheriger Testung brach in unserem Feldtest mit 34 TN bei 4 Teilnehmern Test (Defizit-orientiert) mit folgenden Fehlern ab:

![IMG_20240131_094200822_AE](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/37285ebf-814a-42c4-afc7-c9cc95195612)

Es handelt sich um folgenden Test:
https://moodle.alise.uni-wuppertal.de/mod/adaptivequiz/view.php?id=1584

und folgende Versuche:

SELECT * FROM `alise_adaptivequiz_attempt`
WHERE instance = 8 AND timecreated > 1706689000

<img width="1008" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/46f24f96-5af2-4675-a768-89cd6616e124">
<img width="1008" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/0de8247c-f319-481a-b187-28065282e828">

**Comment by ralferlebach** [comment]
Eine weitere Rückmeldung, diesmal auf dem LTI-Server:

"Hey Ralf,


ich habe heute mal ALiSe als Gastnutzer ausprobiert. Als ich eine leere Eingabe gemacht habe gab es einen Fehler. Als ich dann zu allem Überfluss noch die Zurück-Funktion meines Browsers verwendet habe, war es ganz vorbei.


Siehe Screenshots anbei."
![grafik](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/5cca76b3-0f84-4976-8a76-c59fb9993933)
![grafik](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/a09a91f9-b142-4063-88cb-fbae92518b32)
![grafik](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/640a98e3-3e23-4053-9e13-8d672abbc284)

Ich kann diese Art von Fehlern aus eigener Erfahrung bestätigen, aber nicht stabil reproduzieren.

**Comment by ralferlebach** [comment]
Ich kann es jetzt sogar auf alise.wunderbyte.at bestätigen

<img width="857" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/21293071-5edd-46ba-8a59-54d4934e5405">

**Comment by eynimeni** [comment]
error message is not displayed anymore, new message that quizsettings need to be updated and saved.
