### ISSUE TITLE
CATquizFeedback: Rückmeldung (Inhalt und Standard-Ansicht)

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#294]
Die ersten Rückmeldungen unserer Test-Nutzenden (Lehrende wie Studierende) deuten daraufhin, dass zum einen die Inhalte der Rückmeldungen (durchweg berechtigt) hinterfragt werden, zum anderen unklar bleibt, was nun für die Nutzer zu tun ist (und welche der Informationen wichtig und welche unwichtig sind).

Ich habe beide Problemstellungen einmal zusammengefasst:
1. Auswahl der defizitären/stärksten/was-auch-immer-Skala
2. Darstellung des Feedbacks in Form von (schriftlicher) Rückmeldung (Primär-Information) + einordnenden Informationen (Sekundär-Informationen)

Informationen die sich an Lehrende richten, sollten m.E. nicht im catquifeedback enthalten sein, sondern einen eigenen Shortcode bekommen. 

[2024-01-31 Aufbau der Standard-Ansicht einer Rückmeldung.pdf](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/14113703/2024-01-31.Aufbau.der.Standard-Ansicht.einer.Ruckmeldung.pdf)

**Comment by ralferlebach** [comment]
Gut zu wissen, dass andere Experten gleicher Meinung sind: 
<img width="161" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/6c35fdaa-9912-4c6d-b5ea-78b4c2d5a091">
war dies Teil meiner aktuellen Lektüre:
<img width="596" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/07244fba-bf9a-4308-8641-2ebead002f26">
;-)

**Comment by eynimeni** [comment]
- [ ] Error Message falls eine Skala kein Ergebnis bringt: "Im letzten Versuch konnte zu dieser Skala kein Ergebnis ermittelt werden.”
- [ ] Ergebnisse des Filters in Attempt Table Speichern (Update)
- [ ] bei Error Message Parameter mitgeben.
