### ISSUE TITLE
Eingaben von Komma-Zahlen (mit Komma statt Punkt) erlauben, SE auch größer 1 zulassen

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#296]
Betrifft alle numerischen Felder mit Float-Werten im mod_adaptive
<img width="515" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/7d75de14-62f6-482b-9651-aa8b794441a7">

Ferner darf der Standardfehler auch größer als 1 sein, d.h. 0,1 oder 10 müssten akzeptiert werden. (SE > 0)
<img width="537" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/3a430941-e08a-46af-85cf-528659d9e08b">

**Comment by eynimeni** [comment]
über den standardfehler sollten wir nochmals sprechen, auch mit @davidszkiba . die grenzen sind noch nicht fertig implementiert.
aber die validierung des formulars sollte jetzt passen :-)
