### ISSUE TITLE
Start-Optionen für Testung in mod_adaptive und ggf. Frageauswahl

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#297]
Die Auswahl sollte leichter verständliche Optionen anbieten und die Option, mit  vorangegangenen Fähigkeitswerten zu starten, muss separat als Checkbox geboten werden (zwei voneinander unabhängige Konditionen).
 
<img width="577" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/94cef5c5-59f9-47dd-91d0-76097bb9140f">

**Comment by davidszkiba** [comment]
@eynimeni @ralferlebach 
Eigentlich sind diese Optionen doch nicht unabhängig, oder?
Wenn ich z.B. die Option  "mit einer leichten Frage beginnen" wähle, dann schließt das die Option aus, dass Ergebnisdaten aus vorherigen Testversuchen übernommen werden. Denn die Auswahl der Frage ist dann nur von der Fragenschwierigkeit selbst abhängig aber nicht von den vorherigen Versuchen.

**Comment by davidszkiba** [comment]
@ralferlebach @eynimeni 
Wenn die Personenfähigkeit aus vorherigen Versuchen geschätzt werden soll:
wird dann immer die Frage zurückgegeben, die die größte Fischerinformation hat? Also wird hier praktisch die erste Frage dann mittels radikalem CAT ausgewählt?
Oder soll das davon abhängen, welche Teststrategie für das Quiz ausgewählt ist? Also zB unterste Kompetenzlücke diagnostizieren?
Im zweiten Fall müsste ich dann nämlich nicht nur für die Hauptskala, sondern auch für jede Unterskala den Mittelwert der Personenfähigkeit verwenden. Und hier stellt sich die Frage, ab wie vielen Werten man schätzen will? Es wird voraussichtlich mehr Werte für die Hauptskala als für Unterskalen geben.
Ich implementiere es jetzt erst mal so, dass nur der Wert in der Hauptskala geschätzt wird und die Frage mit der höchsten Fischerinformation zurückgegeben wird.

**Comment by ralferlebach** [comment]
Morgen David,

ja, genau, letzteres: Das gesamte Fähigkeitsprofil (PP und Se, also dann, wenn es auch berichtet wurde) übernehmen und strategiespezifisch weitertesten.


LG
Ralf

**Comment by davidszkiba** [comment]
@ralferlebach Ok danke.
Ab wie vielen Werten kann ich dann davon ausgehen, dass ich einen validen Durchschnitt bilden kann? Verwenden wir auch hier das Minimum von 50 Personenfähigkeiten?
Was soll passieren, wenn es zB in der Hauptskala bereits 50 Einträge gibt, aber in einer Unterskala weniger als 50? Soll dann trotzdem geschätzt werden? Oder muss auch jede Unterskala mindestens 50 Einträge haben, damit ein valider Durchschnitt gebildet werden kann?

**Comment by davidszkiba** [comment]
Start new test -  (checkbox) by using previous users results
... otherwise start with - [select]
