### ISSUE TITLE
Warnings im Test-Test

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#298]
https://alise.wunderbyte.at/course/view.php?id=20

<img width="873" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/0b2b2eb3-1bfd-4b67-b895-3d5e1772403b">

**Comment by davidszkiba** [comment]
Couldnt reproduce now - probably fixed already
