### ISSUE TITLE
Kleiner Typo bzw. Fehler im String (Einstellungen im mod_adaptive)

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#299]
Die zweite Zeile soll sicher vermutlich "Anzahl der Fragen pro Skala" lauten.

<img width="504" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/d77c1405-f1c1-47b9-82bb-4a3070081a44">

**Comment by eynimeni** [comment]
ja hab ich auch schon bemerkt, sollte ab commit #3fa7680 (31.1. 8:45) gefixt sein!
