### ISSUE TITLE
Show same question after page reload

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#311]
If a user does not answer the question and reloads the page (or logs out, logs back in and continues the quiz), the same question should be shown again.
This prevents users from reloading the page until they get an easy question.

**Comment by ralferlebach** [comment]
Hallo David,
hier die möglichen Fälle:

Seite wird erneut geladen (vor/rück-Navigation, Reload, etc.) und
Session nicht erneuert
Zeitbegrenzung gesetzt und für Item nicht abgelaufen oder Zeitbegrenzung nicht gesetzt
=> gleiches Item präsentieren 

Session nicht erneuert
Zeitbegrenzung für Item abgelaufen
=> Item als falsch beantwortet bewerten und neues Item präsentieren 

Session erneuert
Zeitbegrenzung gesetzt und für Item nicht abgelaufen
=> gleiches Item präsentieren

Session erneuert
Zeitbegrenzung für Item abgelaufen oder Zeitbegrenzung nicht gesetzt
=> neues Item präsentieren und Item unbewertet lassen (aber für den weiteren Attempt nicht erneut präsentieren)
