### ISSUE TITLE
comparison to peer students

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#314]
"you performed better than XY%" überprüfen
- [ ] wenn man der erste ist
- [ ] stimmen die werte

pointer in farbbalken überprüfen
- [ ] kein pointer falls man der erste ist
- [ ] ist die berechnung korrekt und bezieht sich auf die selbe skala - nicht die globalskala?

**Comment by davidszkiba** [comment]
Ich hab jetzt folgende Änderungen verwendet:

- wenn es keine Personen mit schlechteren Abilities gibt, wird der "You performed better than XX%" Text nicht angezeigt.
- wenn es nicht genug Daten zum Vergleich gibt, also wir nicht mindestens 3 abilities für die angegebene Skala haben, dann wird kein Durchschnitt angezeigt und der untere Pfeil wird ausgeblendet.
- Für den unteren Pfeil wird jetzt der Durchschnitt verwendet und nicht mehr der Median. Das entspricht wahrscheinlich eher dem, was man sich hier erwarten würde.

Ein paar Beispiele:


Erster Versuch und es gibt noch keine Vergleichsdaten:



![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/17564611/74743673-a00e-46a9-9f8f-caa52aa88c04)


Es gibt Ergebnisse von 2 anderen Usern mit abilities von 1.5000 und 0.5:



![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/17564611/b30b5940-75f3-4a00-9881-21318c56e462)


Es gibt Ergebnisse von 2 anderen Usern mit abilities 1.5 und 0.5. Der aktuelle user ist der schlechteste von den 3:



![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/17564611/0539c893-fe58-483b-b109-b03d9b0e4745)


Und noch einmal, wobei der aktuelle user ein mittleres Ergebnis hat:




![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/17564611/0da1d46b-0a1a-4001-964b-78520059eee0)

**Comment by davidszkiba** [comment]
Der PR für dieses Issue merged die Änderungen in den https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/tree/GH-294-apply-strategy-settings branch. Es ist also erst komplett abgeschlossen, wenn dieser branch gemerged ist. Grund ist, dass dieses Issue von den Änderungen im genannten branch abhängig ist.

**Comment by davidszkiba** [comment]
This is merged in #398
