### ISSUE TITLE
Tagesaktuelle Warnings

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#321]
<img width="1440" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/5f29c624-545c-4025-974e-0ebff642d070">

wird in GH-283 gefixt

**Comment by ralferlebach** [comment]
Wenn ich die Seite refreshe, dann sind die Warnungen weg.

**Comment by eynimeni** [comment]
![Screenshot 2024-02-14 at 15 45 43](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/e33a8084-7c01-41bb-af9c-6dcfd0c78680)
ich habe diese Warning beim beginnen des quizattempts https://alise.wunderbyte.at/mod/adaptivequiz/view.php?id=51 auf alise mit version tag aliseupdate_02_13

**Comment by eynimeni** [comment]
![Screenshot 2024-02-14 at 16 07 16](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/9b48f8f4-8946-4f26-8f80-89d0dedb818a)

fallbacks für maxquestions aktualisieren (inf logik)

**Comment by eynimeni** [comment]
> ![Screenshot 2024-02-14 at 15 45 43](https://private-user-images.githubusercontent.com/78353570/304771657-e33a8084-7c01-41bb-af9c-6dcfd0c78680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTE1NDAsIm5iZiI6MTcwODM1MTI0MCwicGF0aCI6Ii83ODM1MzU3MC8zMDQ3NzE2NTctZTMzYTgwODQtN2MwMS00MWJiLWFmOWMtNmRjZmQwYzc4NjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE0MDA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NWJmZDUxNzQzNzZiM2U3MGU4MzEzMmE5ZWI5NjE1NTgzNzNjNDA5NWVlZjE0OWI4MGNkYWI3OTE1NzdjMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QndYgE6l1mGVm21sYZpOWzz3l5TjG8N7P0mkovnGtTI) ich habe diese Warning beim beginnen des quizattempts https://alise.wunderbyte.at/mod/adaptivequiz/view.php?id=51 auf alise mit version tag aliseupdate_02_13

es lag daran, dass noch ein begonnener attempt im table war der versucht wurde, wieder aufgenommen zu werden. sollte in zukunft nicht mehr auftreten.
