### ISSUE TITLE
Einstellungen je nach gewählter Teststrategie

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#325]
<img width="588" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/10b8bcca-e848-4c71-9944-cf1f176c8bb3">

[2024-02-16 Einstellungsmöglichkeiten je Teststrategie.pdf](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/14309363/2024-02-16.Einstellungsmoglichkeiten.je.Teststrategie.pdf)

**Comment by davidszkiba** [comment]
@ralferlebach Ich habe eine Frage bzgl "Standardfehler min/max global" vs "Standardfehler min/max Einzelskala":
Laut Tabelle haben die 3 Strategien  "Defizit/Stärke", "relevante Skalen" und "alle Skalen" einen Standardfehler für die globale Skala *und* einen für Einzelskalen.
Im Code gibt es bis jetzt nur 1 Setting für min/max vom Standardfehler. Bei den 3 oben genannten Teststrategien bezieht sich das dann auf den Fehler pro Einzelskala. Beim (radikalen/moderaten) CAT bezieht sich dieser Wert auf die Globalskala. Also gibt es für diese drei Teststrategien keinen Wert für die Globalskala.
Das stimmt doch so, oder?

**Comment by ralferlebach** [comment]
Ja, der klassische Test testet ALLE in der ausgewählten Skala enthaltenen Fragen (und nur diese Fragen) durch, auch die, die noch zu pilotieren sind.

Mit anderen Worten: da ist die Pilotierung automatisch mit drin, wenn es in der Skala Fragen ohne Item Parameter gibt.

**Comment by ralferlebach** [comment]
#522
