### ISSUE TITLE
Feedback Display Filter

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#339]
- [ ] graphical summary should only contain relevant data
- [x] student view only main areas
- [x] modal seems to modify html display of tabs (bulletlist for tabstitle, tab content underneath each other) -> ?? see commit "TABS in Modal WIP"

teacherfeedback:
- [ ] hide unwanted graphs in summary(tbd)

- [x] temp solution until seperate tabs / page logic is applied

**Comment by ralferlebach** [comment]
#517
