### ISSUE TITLE
check if scales contain itemparams in quizsettings

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#354]
since in #353 scales without itemparams are simply excluded from quiz,
add check for all scales if itemparams are given to quizsettings. as a catmanager / teacher, I may select only scales for a quiz that contain itemparams. 
this can be done either in validation or only scales with items should be displayed. to be decided.

Info item neben Frage: über CSS Klasse hinzufügen, Styling zB Warndreieck mit Info

**Comment by eynimeni** [comment]
should these scales without items really be excluded from quizsettings? what if items are imported later to already existing quizes?

**Comment by davidszkiba** [comment]
@eynimeni The exclusion is always just for the current attempt, the quiz settings are not changed. So if at some point items are imported to an existing scale, the scale will not be excluded anymore in following attempts.
