### ISSUE TITLE
Direkte Rückkehrmöglichkeit zum Kurs nach Test-Ende/Ergebnis

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#357]
<img width="890" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/5a9d1e96-24d0-4f31-bd62-9575950e59d0">

zu

<img width="864" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/bd0ae7a7-710a-41e1-bc5b-d1480adcec4b">

**Comment by eynimeni** [comment]
covered in pull request for adaptivequiz by @ralferlebach
