### ISSUE TITLE
Behat test sometimes fails on first attempt

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#358]
![image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/17564611/4eb4717e-f59e-47eb-aec1-5ef679cafd35)

Check if it is possible to reproduce it locally and if so, how to make it pass on the first run.

**Comment by eynimeni** [comment]
github related and not a real problem
