### ISSUE TITLE
adaptive feedback berücksichtigen (pull request for adaptive)

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#362]
In Quizsettings:

- [ ] Feedbacktext von adaptive als editor
<img width="967" alt="Screenshot 2024-03-06 at 11 55 43" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/c44b2619-ad7f-4a42-adab-b513c26b8b3e">

- [ ] in feedback nach quiz oben vor den feedbackgeneratoren rein gerendert

**Comment by ralferlebach** [comment]
Ist in alise_adaptivequiz gepusht,
als Pr bei vtos
https://github.com/vtos/moodle-mod_adaptivequiz/pull/42

und sollte jetzt auch das Problem des fehlenden Contexts bei #210 lösen.

(Bitte prüfen und Warnmeldung wieder entfernen: #695)
