### ISSUE TITLE
Tracking im Feedback

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#364]
Wir haben gestern im Gespräch festgestellt, dass wir ein Event-Tracking (im Sinne der Moodle-Logs) für die Evaluation und Bewertung der Nützlichkeit der einzelen Informationen zwingend benötigen, wenn im Feedback eines CAT-Test-Versuches

* die weiteren Informationen aufgerufen werden
* auf eines der Reiter geklickt wird und diessen Informationen den Nutzenden angezeigt werden

**Comment by eynimeni** [comment]
event on tab change

**Comment by eynimeni** [comment]
covered in #376
