### ISSUE TITLE
JS errors after submitting last answer (instead of feedback page)

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-local_catquiz#372]
All behat tests dedicated to run quiz in behalf of student are failing after student answer last question
The following JS errors appears (quantity differnt, text the same)

![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/99209607-8cde-4dd8-8e8d-45cc7eb085ef)

**Comment by eynimeni** [comment]
@semteacher should be fixed?
