### ISSUE TITLE
Incorrect "Show" link on the "Test & Template" tab

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-local_catquiz#381]
Incorrect "Show" link on the "Test & Template" tab. 
It points to course ( on my dev for example it is http://localhost:58000/course/view.php?id=1 )

![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/c2fc2d9c-0ef8-4e2e-8f55-ed11c82dd2af)

**Comment by davidszkiba** [comment]
@eynimeni Ich weiß nicht, wo der Link hinzeigen sollte. Ich hab kurz geschaut und glaube nicht, dass es eine extra Seite für Testenvironments gibt. Vielleicht können wir den Link einfach wieder entfernen?
Du hast ihn damals hier hinzugefügt: 8f8d86d8 Vielleicht weißt du noch, wohin der Link hätte zeigen sollen?

**Comment by eynimeni** [comment]
this is correct, it should point to the course where the test is located
