### ISSUE TITLE
Problem im LTI-Server nach zu langer Zeit an Inaktivität

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#391]
Version: 0.9.0-RC

<img width="847" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/b5a35d25-7a5c-4fb5-8c81-06b58daee9cf">

<img width="827" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/5f33bb4c-abf4-4183-b97f-ba5467305fa0">

**Comment by davidszkiba** [comment]
Ich glaub das liegt daran, dass es mittlerweile in der Progress Klasse eine neue Property "gaveupquestion" gibt. In der Datenbank befindet sich wahrscheinlich noch ein alter  Progress in dem dieses Feld nicht vorkommt. Das sollte relativ einfach zu beheben sein, indem man in der betreffenden Zeile einen fallback macht der ein leeres Array erzeugt, falls es das Feld nicht gibt:

```
        $instance->gaveupquestions = $data->gaveupquestions ?? [];
```

**Comment by ralferlebach** [comment]
Danke für den Hinweis. Ich habe alle noch offenen Attempts gelöscht und nun läuft es.

Codeseitig muss hier nichts unternommen werden, da das Problem in Zukunft nicht mehr auftreten sollte.
