### ISSUE TITLE
Itemparameter Berechnung - Tests

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#393]
Check that the current tests cover all models

- [x] Tests for rasch model are active and work
- [x] Tests for raschbirnbaum are active and work
- [x] Tests for mixedraschbirnbaum are active and work

**Comment by davidszkiba** [comment]
In commit 0e662066ab623757112507657cdea91f86d34abb non-working tests were removed. Should be fixed and added again.

**Comment by davidszkiba** [comment]
Tests for rasch and raschbirnbaum are green now. Only mixedraschbirnbaum fails. This will be fixed in GH-399

**Comment by davidszkiba** [comment]
@ralferlebach ich verwende jetzt folgende Vorgehensweise zum Testen. Im Moment verwende ich dafür nur 'rasch' und 'raschbirnbaum'.

Ich verwende immer die responses aus tests/fixtures/responses.1PL.csv und als Startwerte für die person abilities die Werte aus tests/fixtures/persons.csv.

1. Berechnung item params mit rasch. Startwerte itemparams: keine (0). Abilities: aus CSV Datei.
2. Berechnung item params mit raschbirnbaum. Startwerte itemparams: Ausgabe von rasch. Abilities: CSV Datei.
4. Ich berechne die person abilities anhand dieser Werte neu. Erste Iteration ist damit fertig.
5. Berechnung item params mit rasch. Startwerte itemparams: Ausgabe von rasch in Iteration 1. Abilities: wie gerade neu berechnet
6. Berechnung item params mit raschbirnbaum. Startwerte itemparams: Ausgabe von rasch. Abilities: neu berechnet
7. Abilities updaten usw.

Stimmt das so? Für die Berechnung mit dem Rasch Modell verwende ich also immer die Werte von Rasch aus der vorherigen Iteration. Für die Berechnung mit Raschbirnbaum verwende ich immer die Ausgabe vom Rasch.

**Comment by davidszkiba** [comment]
@ralferlebach Das sind die Ergebnisse für die Daten aus dem teststrategie_tester repository.
Ich habe die Itemparameter erstmal mit Rasch und Rasch-Birnbaum berechnet. Ich habe praktisch von Null weg berechnet, also keine bestenden Itemparameter als Startwert verwendet.
Was auffällt, ist, dass bei Rasch-Birnbaum die Discrimination immer als 3 berechnet wird - das wird wohl so nicht stimmen?
Ich habe die Ergebnisse grob stichprobenartig kontrolliert: bei Items mit niedrig berechneter Difficulty gibt es viele richtige Antworten, bei hoher Difficulty nur wenige richtige.

[items.csv](https://github.com/user-attachments/files/17277100/items.csv)
[items_rasch.csv](https://github.com/user-attachments/files/17277099/items_rasch.csv)
[items_raschbirnbaum.csv](https://github.com/user-attachments/files/17277101/items_raschbirnbaum.csv)

**Comment by davidszkiba** [comment]
Mit `bmin` und `bmax` auf `-5.0` und `5.0` gesetzt, kommen folgende Werte:

[items2.csv](https://github.com/user-attachments/files/17277392/items2.csv)
[items_raschbirnbaum2.csv](https://github.com/user-attachments/files/17277394/items_raschbirnbaum2.csv)

**Comment by ralferlebach** [comment]
@davidszkiba:
Die 1PL-Werte sehen sehr gut aus, die 2PL-Werte leider nicht.

Setze bitte einmal die Grenzwerte für b auf 0.0 bis 5.0 (anstatt-5.0 bis 5.0) und verwende als Startwerte für die Berechnung für a (Difficultiy) das Ergebnis aus der 1PL-Berechnung und b=1 (Discrimination).

Gleiches für 3PL. hier das Ergebnis der 2PL-Berechnung (a und b) als Startwert nutzen und c=0.5 (Guessing). Die Grenzwerte für c sind dabei 0.0 ... 1.0.

**Comment by davidszkiba** [comment]
Die Werte von Rasch und Rasch-Birnbaum stimmen jetzt gut überein:

[rasch_2024-10-21_19-55-27.csv](https://github.com/user-attachments/files/17460462/rasch_2024-10-21_19-55-27.csv)
[raschbirnbaum_2024-10-21_19-55-27.csv](https://github.com/user-attachments/files/17460463/raschbirnbaum_2024-10-21_19-55-27.csv)

**Comment by davidszkiba** [comment]
Geschätzte abilities:

[abilities_2024-10-21_21-04-44.csv](https://github.com/user-attachments/files/17461270/abilities_2024-10-21_21-04-44.csv)

**Comment by davidszkiba** [comment]
Die Werte bei mixedraschbirnbaum scheinen mit den richtigen Startwerten jetzt auch zu passen. Ein Paramter "b min", der bei der trusted regions Funktion verwendet wird, war fälschlicherweise auf +3 statt auf -3 eingestellt, daher sind zuerst komische Werte entstanden.
Hier der letzte Stand, berechnet mit den V1 responses und abilities:

[mixedraschbirnbaum_2024-10-22_19-09-34.csv](https://github.com/user-attachments/files/17476042/mixedraschbirnbaum_2024-10-22_19-09-34.csv)
[rasch_2024-10-22_19-09-34.csv](https://github.com/user-attachments/files/17476043/rasch_2024-10-22_19-09-34.csv)
[raschbirnbaum_2024-10-22_19-09-34.csv](https://github.com/user-attachments/files/17476041/raschbirnbaum_2024-10-22_19-09-34.csv)
[abilities_2024-10-22_19-09-34.csv](https://github.com/user-attachments/files/17476059/abilities_2024-10-22_19-09-34.csv)

**Comment by ralferlebach** [comment]
Kannst du dies auch noch einmal (1PL, 2PL und 3PL) bitte für die Datei
responses 3PL V1.csv (für alle drei Modelle dieselbe Datei)
berechnen lassen?

Dann sollten auch entsprechende Guessing-Parameter geschätzt werden können.

**Comment by davidszkiba** [comment]
Ja, ich habe vorher die 1PL V1 responses verwendet. Mit den 3PL V1 responses schauen die Werte nicht gut aus.

[rasch_2024-10-24_17-00-27.csv](https://github.com/user-attachments/files/17504410/rasch_2024-10-24_17-00-27.csv)
[raschbirnbaum_2024-10-24_17-00-27.csv](https://github.com/user-attachments/files/17504409/raschbirnbaum_2024-10-24_17-00-27.csv)
[abilities_2024-10-24_17-00-27.csv](https://github.com/user-attachments/files/17504411/abilities_2024-10-24_17-00-27.csv)
[mixedraschbirnbaum_2024-10-24_17-00-27.csv](https://github.com/user-attachments/files/17504408/mixedraschbirnbaum_2024-10-24_17-00-27.csv)

**Comment by ralferlebach** [comment]
So schlecht ist es gar nicht einmal. Möglicherweise müssen wir doch einen der grob-schätzenden numerischen Schritte zwischenschalten, aber die 3PL-Werte werden mit über 50% bereits nahe an den Ursprungswerten bestimmt, obwohl die Grenzen offenbar noch nicht korrekt eingestellt sind.
[itemparameter.V1 Versuch mit 3PL-Daten.xlsx](https://github.com/user-attachments/files/17505349/itemparameter.V1.Versuch.mit.3PL-Daten.xlsx)

Kannst du für 
1PL, 2PL und 3PL die Difficultiy auf a_min=-5 und a_max=5 festsetzen (jetzt wohl -6 bis 6)
2PL und 3PL die Discrimination auf b_min = 0 und b_max = 6 vorgeben
3PL das Guessing auf c_min=0 und c_max=0,5 festlegen

und damit noch einmal rechnen? Dann würde ich gern die Ergebnisse mit dir einmal per Zoom besprechen, wenn das dir passt.

**Comment by davidszkiba** [comment]
Hier sind mal die bestehenden settings von raschbirnbaum:
https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/feature/itemparams/catmodel/raschbirnbaum/settings.php

Im Moment ist `trusted_region_min_a` auf -10 und `trusted_region_max_a` auf 10 eingestellt und `trusted_region_factor_sd_a` auf 3.0. Ich werde also min_a und max_a auf -5 bzw +5 ändern. Und die anderen Werte so wie in deinem vorigen Kommentar beschrieben

**Comment by davidszkiba** [comment]
[mixedraschbirnbaum_2024-10-24_18-48-54.csv](https://github.com/user-attachments/files/17505698/mixedraschbirnbaum_2024-10-24_18-48-54.csv)
[rasch_2024-10-24_18-48-54.csv](https://github.com/user-attachments/files/17505699/rasch_2024-10-24_18-48-54.csv)
[abilities_2024-10-24_18-48-54.csv](https://github.com/user-attachments/files/17505700/abilities_2024-10-24_18-48-54.csv)
[raschbirnbaum_2024-10-24_18-48-54.csv](https://github.com/user-attachments/files/17505701/raschbirnbaum_2024-10-24_18-48-54.csv)

**Comment by davidszkiba** [comment]
@ralferlebach das sind jetzt die Dateien, die mit 3PL responses generiert worden sind UND in denen die Modelle die  geänderten Parameter Grenzen verwenden:

[rasch_2024-10-24_20-11-53.csv](https://github.com/user-attachments/files/17506634/rasch_2024-10-24_20-11-53.csv)
[raschbirnbaum_2024-10-24_20-11-53.csv](https://github.com/user-attachments/files/17506635/raschbirnbaum_2024-10-24_20-11-53.csv)
[abilities_2024-10-24_20-11-53.csv](https://github.com/user-attachments/files/17506636/abilities_2024-10-24_20-11-53.csv)
[mixedraschbirnbaum_2024-10-24_20-11-53.csv](https://github.com/user-attachments/files/17506637/mixedraschbirnbaum_2024-10-24_20-11-53.csv)

**Comment by ralferlebach** [comment]
[itemparameter.V1 Versuch mit 3PL-Daten 2. Versuch.xlsx](https://github.com/user-attachments/files/17507013/itemparameter.V1.Versuch.mit.3PL-Daten.2.Versuch.xlsx)
