### ISSUE TITLE
Unit test failures für catmodels

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#399]
Die Berechnungen vom 2PL Modell stimmen, aber bei 1PL und 3PL gibt es Abweichungen.

Testoutput ist angehängt.

#### least_mean_squares_1st_derivative_ip

Erster Wert ist parameter `n`
Zweiter Wert ist das personparam array
Dritter Wert ist fraction `k`
Vierter Wert ist das itemparam array mit difficulty

```
1) catmodel_rasch\rasch_test::test_least_mean_squares_1st_derivative_ip with data set "testcase3" (27, array(-2), 0.3, array(-2.5), 0.5968974)
Failed asserting that -4.092074 matches expected 0.596897.

/var/www/html/local/catquiz/catmodel/rasch/tests/rasch_test.php:185
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97
```

Params testcase3:

```
            "testcase3" => [
                'n' => 27,
                'pp' => ['ability' => -2],
                'k' => 0.3,
                'ip' => [
                    "difficulty" => -2.5,
                ],
                'expected' => 0.5968974,
            ],
```

```
2) catmodel_rasch\rasch_test::test_least_mean_squares_1st_derivative_ip with data set "testcase4" (27, array(-2), 0.95, array(-2.5), 0.2227782)
Failed asserting that 4.156557 matches expected 0.222778.

/var/www/html/local/catquiz/catmodel/rasch/tests/rasch_test.php:185
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97
```

Params testcase4

```
            "testcase4" => [
                'n' => 27,
                'pp' => ['ability' => -2],
                'k' => 0.95,
                'ip' => [
                    "difficulty" => -2.5,
                ],
                'expected' => 0.2227782,
            ],

```

#### least_mean_squares_2nd_derivative_ip

```
3) catmodel_rasch\rasch_test::test_least_mean_squares_2nd_derivative_ip with data set "testcase1" (5, array(-3), 0.3, array(-2.5), -0.1822235)
Failed asserting that 0.596897 matches expected -0.182224.

/var/www/html/local/catquiz/catmodel/rasch/tests/rasch_test.php:210
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97

4) catmodel_rasch\rasch_test::test_least_mean_squares_2nd_derivative_ip with data set "testcase2" (5, array(-3), 0.95, array(-2.5), 1.345301)
Failed asserting that 0.222778 matches expected 1.345301.

/var/www/html/local/catquiz/catmodel/rasch/tests/rasch_test.php:210
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97

5) catmodel_rasch\rasch_test::test_least_mean_squares_2nd_derivative_ip with data set "testcase3" (27, array(-2), 0.3, array(-2.5), 0.5968974)
Failed asserting that 1.980019 matches expected 0.596897.
```

### Testoutput

[output_mixedraschbirnbaum.txt](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/14801926/output_mixedraschbirnbaum.txt)
[output_raschbirnbaum.txt](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/14801927/output_raschbirnbaum.txt)
[output_rasch.txt](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/14801928/output_rasch.txt)

**Comment by davidszkiba** [comment]
@ralferlebach wie besprochen hier ein paar Beispiele für catmodel unit tests.

**Comment by davidszkiba** [comment]
@ralferlebach Ich hab gerade bemerkt, dass `catmodel/rasch/tests/rasch_test.php` wahrscheinlich fehlerhafte Einträge bei den Test-Datensätzen hat. So ist zB für die `test_least_mean_squares_2nd_derivative_ip` Funktion der `dataProvider` angegeben, der die Testdaten für test_least_mean_squares_*1st*_derivative_ip zurückgibt.

**Comment by davidszkiba** [comment]
Ich habe die Testdaten jetzt korrigiert.
Es gibt jetzt 2 fehlerhafte Werte:
1) In mixedraschbirnbaum::least_mean_squares_1st_derivative_ip() stimmt jeweils `$derivative[0]` nicht:
https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/dev-david-issue-393/catmodel/mixedraschbirnbaum/classes/mixedraschbirnbaum.php#L280
2) In mixedraschbirnbaum::least_mean_squares_2nd_derivative_ip() stimmt jeweils `$derivative[1][1]` nicht:
https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/dev-david-issue-393/catmodel/mixedraschbirnbaum/classes/mixedraschbirnbaum.php#L324

**Comment by eynimeni** [comment]
nach rücksprache mit @ralferlebach 
diese formeln müssen wir aktuell nicht nutzen, also kann es vorerst ad acta gelegt werden.
