### ISSUE TITLE
Closures in Variablenzuweisungen?

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#4]
Kurze Verständnisfrage: Welche Bewandtnis hat es, dass in Variablenzuweisungen anonyme Funktionen (Closures) statt einfacher Werte verwendet werden?

z.B. 

$likelihood = function($x){return 1;};

in Zeile 66 in dev_daniel Wunderbyte-GmbH/moodle-local_catquiz/tree/dev_daniel/classes/catcalc.php

**Comment by danerk** [comment]
Um funktionelle Bestandteile möglichst sinnvoll zu kapseln, soll der Lösungsalgorithmus unabhängig von der konkreten Form der Likelihoods sein. Um dennoch die mathematischen Vorteile (Log -> Summe statt Multiplikation, elementare Ableitbarkeit,...) zu behalten, werden die likelihoods der einzelenen Items - Responses  (basierend auf deren Modell) verkettet und zu jener Likelihood kombiniert, die dann durch einen(!) "Solver" maximiert werden soll.

Die Verkettung ist innerhalb einer Schleife mit den Funktionen 'compose_plus' und 'compose_multiply' verkettet. Diese Funktionen machen immer paarweise aus zwei Callables ein zusammengesetztes Callable.

Die Funktion 

$likelihood = function($x){return 1;};

ist der initiale Wert und sollte callable sein, da es dann mit den weiteren Likelihood-Teilen über compose_multiply(callable,callable) -> callable verbunden wird.
