### ISSUE TITLE
shortcode teacherview = catquizstatistics

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#405]
- [x] Create new shortcode "catquizstatistics"
- [x] Move charts 2 & 3 from Quiz progress summary to shortcode

![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/096a53ca-8224-4730-b0bd-ce34135c30ed)

in teacherfeedback not the first graph but 2-4

![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/019bb815-3735-43ab-8611-9a9dc00ceed6)
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/bb5b823c-06b3-44b1-b974-701a6e25ab11)
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/7ed602d2-f7db-4ce1-a946-fedbff417919)

**Comment by eynimeni** [comment]
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/763565a7-a0a6-4376-8a53-ec4563b27bf5)
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/9fccf4ca-81cf-4091-92e6-aadf2faa5531)

**Comment by ralferlebach** [comment]
[20240430 - Übersicht CatQuizStatistics.pdf](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/15158455/20240430.-.Ubersicht.CatQuizStatistics.pdf)

**Comment by ralferlebach** [comment]
Beispielshortcodes:

catquizstatistics
wenn nur ein CAT im Kurs, dann cmid von diesem annehmen
wenn mehrere CAT im Kurs mit gleicher globalskala, dann diese annehmen
wenn mehre CAT und unterschiedlichen Globalskalan, dann Fehlermeldung im Textblock mit Lösungsvorschlag
(Sobald das System nicht in der Lage ist, die Zuordnung eindeutig aufzulösen)

catquizstatistics testid = cmid
nehme Daten und Globalskala des spezifizierten CATs 

catquizstatistics scaleid = skala
nehme spezifizierte (Global-)Skala, standardmäßig über alle CATs im aktuellen Kurs
wenn Skala im Kurs oder der Shortcode außerhalb eines Kurses verwendet wird, dann Fehlermeldung in Textblock (siehe oben)

catquizstatistics scaleid = skala scope = kursid|all
nehme spezifizierte (Global-)Skala, standardmäßig über alle CATs in der Moodle-Instanz bzw. Kursinstanz
(* Profi-Parameter! Berechtigungsfrage noch offen)

**Comment by ralferlebach** [comment]
Frage: 
* Wie gehen wir mit ausgeschriebenen TN um?
* Wie gehen wir mit Rollen (TN, Tutoren, Lehrende) um?

**Comment by davidszkiba** [comment]
Falls es mehrere Tests betrifft und sich die Ranges unterscheiden -> nur schwarz/grau anzeigen.

**Comment by ralferlebach** [comment]
#517
