### ISSUE TITLE
politome items als Modell anlegen

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#415]
@ralferlebach übergibt php mit formeln an @davidszkiba 
Dann Tests bauen

Bei polytomen Items gibt es nicht mehr nur 1 float Wert für die difficulty. Stattdessen gib es ein ganzes array von "intercepts".
Deshalb:

- [x] Neue Spalte `item_params` erstellen, in der die Parameter in json Form gespeichert werden. Default: NULL
- [x] Spaltenredundanz checken
- [x] Evtl upgrade von bestehenden Daten auf die neuen Daten schreiben -> sollte nicht notwendig sein
- [x] aufrufen neue modelle implementieren
- [x] vergleich ergebnisse mit testdaten

@ralferlebach kannst du bitte testdaten zur verfügung stellen, damit @davidszkiba dann die ergebnisse vergleichen kann?

**Comment by ralferlebach** [comment]
- [ ] Manuell in DB einfügen
- [ ] Aus Datenbank lesen => Datenstruktur prüfen lassen (DB > $ip)
- [ ] Daten in Datenbank schreiben => Datenbank-Eintrag prüfen ($ip > DB),
- [ ] aggregatsfunktion für difficulty anlegen, discrimination kann direkt übernommen werden; gewichteter Mittelwert -> jetzt Wert von '1.000'
- [ ] Importer fertig stellen (neue Spalte mit JSON?)

**Comment by davidszkiba** [comment]
Für `grmgeneralized` funktioniert es so weit.
@ralferlebach liefert noch die restlichen Modelle, die dann auch noch eingebunden und getestet werden.
