### ISSUE TITLE
TO BE REPLICATED: Fix import: import subscales

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#417]
It seems if a main scale is created manually and later other scales are imported, they will be in different contexts.
This leads to an error when attempting a quiz, because the item parameters are either in one context or another context, so for some scale no items will be found.

**Comment by eynimeni** [comment]
@ralferlebach ist das nochmals aufgetreten? kannst du uns evt. die betroffenen importfiles zur verfügung stellen?

wie besprochen konnten wir das problem nicht reproduzieren, bei uns kommt zum erwarteten verhalten:
neue root-skalen erhalten einen kontext
neue sub-skalen haben kontext null, durch den import der items wird allerdings ein neuer context erzeugt, der kontext der rootskala wird upgedated mit dem neuen kontext. bestehende items aus dem alten kontext werden dupliziert und mit dem neuen kontext versehen.
