### ISSUE TITLE
teststrategy - balanced

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#42]
- [x] Create new test strategy which should ultimately make sure that all the test items will have a similar number of views.

For this, we need a "number of attempts" penalty, which doesn't concern the single user, but is based on the attempts of all users.
Now we have another logic which will alter the Fischer information and ultimately lead to a different sorting of this. There will be a few more, based on sub scales and so on. In order to keep this manageable, we should develop an interface and a class for each functionality, to keep the code clean. We will then iterate for every item over each of these classes and always adjust the rank, depending on the active settings.
- [x] Implement general interface for these adoptions of the question rank.
- [x] Implement the "numberofgeneralattempts" class
- [x] Implement the "lasttimeplayed" class (which will incorporate the current penalty code)

**Comment by davidszkiba** [comment]
Start as follows:
- create an `item_score_modifier` interface, which contains an `update_score(item $i)` method that expects an item and modifies its score
- the  `local_catquiz\teststrategy\info` class provides a method `get_score_modifiers([])`. It expects an array as parameter that tells it which classes to return.
- Each strategy implements a `requires_score_modifiers()`  that returns an array of strings to specify the modifiers that are used by the strategy.
- The base strategy class constructor gets and sets the required modifiers.
