### ISSUE TITLE
Feedback: Rückmeldungen und Änderungswünsche

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#420]
Wie gestern bereits angekündigt, hier meine Rückmeldungen mit den Änderungswünschen.

(Betrifft etliche noch offen issues und Todos im Projektboard, wenn ich diese finde, verlinke ich sie hier.)
[Änderungswunsch CATQuiz Feedback.pdf](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/14996205/Anderungswunsch.CATQuiz.Feedback.pdf)

**Comment by ralferlebach** [comment]
CATQuizstatistics - Shortcode: #405

**Comment by eynimeni** [comment]
- [ ] Begründung, warum kein valides Ergebnis gefunden wurde: klären ob Änderungen von #413 ausreichen
- [ ] In shortcode collapsable: Unterscheidung ob Feedback von aktuellem User oder anderer Person
    - [ ] bei aktuellem User: „Mein Testversuch vom xx.xx.xxxx um xx.xx Uhr“
    - [ ] „Testversuch ### vom xx.xx.xxxx um xx.xx Uhr, vorgenommen durch Vorname Nachname“ für Dozierende
- [ ]  feedbackgenerator "comparetotestaverage" first, title = "Überblick" statt "Übersicht im Vergleich"
- [ ] „Ergebnis-Details“ statt „Fähigkeits-Score“ (= "personabilties")

dann weitere Details aus PDF

**Comment by eynimeni** [comment]
wird durch neues feedback zu charts von philip und ralf abgelöst

**Comment by ralferlebach** [comment]
#517
