### ISSUE TITLE
Wird schon ein Zeitfaktor bei der Fragenauswahl berücksichtigt?

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#424]
Ralf hat bei mehreren Attempts oft die gleichen Fragen gesehen...

**Comment by davidszkiba** [comment]
Wird verwendet bei:
 - Auswahl einer Pilotfrage, indirekt über `strategybalancedscore`:

```
            $lasttimeplayedpenaltyweighted = (1 - (
               $question->lasttimeplayedpenalty / $context['penalty_threshold']));
            $numberofgeneralattemptspenaltyweighted = (1 - (
                $question->numberofgeneralattempts / $context['generalnumberofattempts_max']));
            $question->score = $numberofgeneralattemptspenaltyweighted * $lasttimeplayedpenaltyweighted;
```

 - Radikaler CAT : 
 
```
            $question->score = (1 - (
                $question->lasttimeplayedpenalty / $context['penalty_threshold']))
                * $question->fisherinformation[$context['catscaleid']];
```

**Comment by davidszkiba** [comment]
Ich hab es mit dem radikalen CAT getestet und es scheint dort zu funktionieren

**Comment by davidszkiba** [comment]
- plugin setting fuer penalty threshold in Tagen hinzufuegen
- logistische Funktion verwenden

@ralferlebach kannst du mir die Formel schicken?

**Comment by ralferlebach** [comment]
Meine Bitte ist, folgende (logistische, nicht lienare) Formel zu verwenden:

$lasttimeplayedpenaltyweighted = 1 / (1 + exp ( 4.6 * (1 - ($$currenttime$$ - $$lastplayed$$) / $context['penalty_threshold']));

Wenn $question->lasttimeplayedpenalty =  $$currenttime$$ - $$lastplayed$$ zurückliefert, (also ohne die momentane max-Klausel, es dürfen ausdrücklich dann negative Werte entstehen, wenn $context['penalty_threshold'] überschritten wurde), vereinfacht sich dies zu

$lasttimeplayedpenaltyweighted = 1 / (1 + exp ( 4.6 * (1 - $question->lasttimeplayedpenalty / $context['penalty_threshold']));

Der Faktor 4.6 ( bzw. ln(99)/0,9 tp) sorgt dafür, dass nach 10% der verstrichenen Penalty-Zeit ein Wahrscheinlichkeitsbeitrag von 1% überschritten wird. Also wenn als Penalty-Threshold 10 Tage angegeben werden, dann ist der Wichtungsfaktor 
an Tag 01: 0,01, 
an Tag 10: 0,5 und 
an Tag 19: 0,99
