### ISSUE TITLE
Divison by zero in strategydeficitscore.php

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#430]
Eine userin hat einen division by zero Fehler bekommen. Ausgelöst in https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/main/classes/teststrategy/preselect_task/strategydeficitscore.php#L89:

```
...
                $standarderrorplayed = $context['se'][$scaleid];
                $testinfo = $standarderrorplayed === INF ? 0 : 1 / $standarderrorplayed ** 2;
...
```

Der `$standarderrorplayed`  Wert kommt vom `$context['se']`, was nur auf 2 Arten gesetzt wird:

1. Einmal kommt der Wert vom `$context['initial_standarderror']`, das immer auf 1.0 gesetzt ist.
2. An anderen Stellen kommt der Wert aus `catscale::get_standarderror($ability, $items, $default)`:

```   
     /**
     * Returns the standard error for the given ability and items
     *
     * @param float $ability
     * @param model_item_param_list $items
     * @param float $default
     * @return float
     */
    public static function get_standarderror(
        float $ability,
        model_item_param_list $items,
        float $default = 1.0
    ): float {
        if (count($items) === 0) {
            return $default;
        }

        $fisherinfo = 0.0;
        $models = model_strategy::get_installed_models();
        foreach ($items as $item) {
            $fisherinfo += $models[$item->get_model_name()]::fisher_info(['ability' => $ability], $item->get_params_array());
        }

        $fisherinfo = max(10 ** -6, $fisherinfo);
        return (1 / sqrt($fisherinfo));
    }

```

**Comment by ralferlebach** [comment]
Was passiert, wenn $context['se'] für [$scaleid] nicht gesetzt ist? Dann nimmt php den Wert unset bzw. 0 an, richtig?

Das würde zu den beiden, dem Fehler vorangegangenen Warnings passen:
[Wed Apr 17 13:02:12.793154 2024] [php:warn] [pid 833845] [client 132.195.61.61:62176] PHP Warning:  Undefined array key 133 in /var/www/html/local/catquiz/classes/teststrategy/preselect_task/filterbytestinfo.php on line 69, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php?cmid=816
[Wed Apr 17 13:02:13.085448 2024] [php:warn] [pid 833845] [client 132.195.61.61:62176] PHP Warning:  Undefined array key 133 in /var/www/html/local/catquiz/classes/teststrategy/preselect_task/strategydeficitscore.php on line 88, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php?cmid=816

Wonach wir also suchen müssen ist, wieso die Variable NICHT für die entsprechende Skala in dem Fall gesetzt war.

**Comment by davidszkiba** [comment]
@ralferlebach Ja stimmt, in dem Fall wird es zu 0 konvertiert.

Wenn ich bei mir die unit tests ausführe, sind da immer für alle Skalen Werte eingetragen. Ich versuche herauszufinden, wie es dazu kommen kann, dass hier ein Wert fehlt.

**Comment by ralferlebach** [comment]
Scheint gelöst zu sein.
