### ISSUE TITLE
Einstellungen beim Duplizieren der Aktivität werden nicht übernommen

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#443]
Beim Duplizieren einer Aktivität in Moodle 

<img width="825" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/284adf84-e74b-4070-bed4-66cff0f6d3d6">

werden die Einstellungen des local_catquiz nicht mitübernommen.

**Comment by ralferlebach** [comment]
Siehe auch Umsetzung fürs Löschen und #662

**Comment by davidszkiba** [comment]
Ich hab das jetzt auf unterschiedliche Arten versucht. Bin nicht sicher, ob vielleicht das adaptivequiz plugin angepasst werden muss, damit subplugins sich einhaken können. Ich hab backup/restore in local_catquiz und im subplugin (was vermutlich der bessere Ansatz ist) erstellt, und beide Klassen werden nicht aufgerufen.

**Comment by davidszkiba** [comment]
Ok es geht, aber man braucht dazu Änderungen in mod_adaptivequiz und im catquiz catmodel-subplugin:

Änderung im adaptivequiz plugin: https://github.com/Wunderbyte-GmbH/moodle-mod_adaptivequiz/commit/9b48a1f36444af1cd24bf3b0eb15a50736f75a9b
Änderung im catquiz subplugin: https://github.com/Wunderbyte-GmbH/moodle-adaptivequizcatmodel_catquiz/commit/109551ada448f521ccc6a703842cfbc1ef38d7a4
