### ISSUE TITLE
gespielte fragen in feedback darstellen

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#445]
- [x] falls möglich: den link in die tabelle in graphical summary
- [x] icon mit lupe
- [x] on click: modal
- [x] modal: lazy load!!
- [x] render question inkl gegebene antwort

**Comment by eynimeni** [comment]
gesamtänderung von philip und ralf beeinhaltet das??

**Comment by ralferlebach** [comment]
Ja, es ist aber nicht das erste Issue dazu.
#517

**Comment by eynimeni** [comment]
geschätzter aufwand 3 tage

**Comment by davidszkiba** [comment]
Wenn im Quiz das Anzeigen von Antworten eingestellt ist, dann gibt es eine Spalte mit Lupe:

![Image](https://github.com/user-attachments/assets/3ca22708-bc19-48ef-bb97-9a6090aac92b)

 Ein Klick auf Fragelabel oder Lupe öffnet ein Modal mit den Informationen:

![Image](https://github.com/user-attachments/assets/9d892bbb-79e3-40c9-bad4-c57aad02e756)
