### ISSUE TITLE
Fehler bei Cache purge

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#447]
Eingesetzt: RC4 0.91

Test gestartet (erste Frage angezeigt), Cache gepurged, Test reload. Ergebnis:

<img width="818" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/cac715ac-413d-4f69-b687-b23e3006c7f5">

**Comment by davidszkiba** [comment]
Das ist mit GH-448 behoben worden und in der neuen release enthalten: https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/releases/tag/0.9.1-rc5
