### ISSUE TITLE
check timestamp constant calculation

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#451]
warum werden manchmal quartale genommen? obwohl es nur einzelne tage sind. welche records werden considered?

**Comment by davidszkiba** [comment]
@eynimeni hast du vielleicht ein Beispiel, wo das auftritt? Ich nehme an du weißt nicht, wie man das reproduzieren kann?

**Comment by davidszkiba** [comment]
@ralferlebach weißt du, ob das noch aktuell oder bereits behoben ist?

**Comment by ralferlebach** [comment]
Ich kann mit dem Issue nichts anfangen und weiß auch nicht, worauf sich das bezieht.
