### ISSUE TITLE
"Ergebnis", obwohl gar keine Testfragen beantwortet

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#455]
Es werden offensichtlich falsche Ergebnisse gespeichert und ausgegeben.

a) Im Fall von Wiederholungen, wobei dies aufgefallen ist, weil in den fraglichen Attempts keine Frage gespielt wurde:
<img width="694" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/a1185979-a2dd-400a-905c-21415077d6c7">

b) Das Problem scheint aber auch bei Teilnehmern, die noch keinerlei vorherige Versuche durchlaufen sind:
<img width="703" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/a0b61eb8-1bd8-4bf0-9272-ca0ec9ee4897">

Bitte unbedingt Fehlerursache identifizieren und fixen!

**Comment by ralferlebach** [comment]
Verwendetes SQL für die Abfrage:

SELECT ca.id, ca.userid, ca.starttime, ca.endtime, ca.number_of_testitems_used,
REPLACE(REGEXP_SUBSTR(ca.json, '"primarybecause":"lowestskill","name":"Ma-[A-Z]'), '"primarybecause":"lowestskill","name":"', '') AS resultcategory,
REPLACE(REGEXP_SUBSTR(ca.json, '"primarybecause":"lowestskill","name":"Ma-[A-Z][0-9]+'), '"primarybecause":"lowestskill","name":"', '') AS resultscale
FROM `mdl_local_catquiz_attempts` as ca
WHERE courseid = 198
ORDER BY ca.userid, ca.id ASC

**Comment by davidszkiba** [comment]
@ralferlebach wie im meeting gerade besprochen:
in der Datenbank wird immer der aktuelle Stand nach der letzten gespielten Frage gespeichert. D.h. es wird auch eine primary scale gespeichert, selbst wenn die dann im Feedback evtl nicht angezeigt wird, weil bei der Anzeige vom Feedback geprüft wird, ob alle Bedingungen wie zB Minimalanzahl an Fragen oder Standardfehler erfüllt sind.

**Comment by eynimeni** [comment]
@ralferlebach überprüft ob das akutell überhaupt noch vorkommt und ob es wirklich zu einem fehlverhalten kommt. 
möglicherweise ist das outdated und solange kein fehlerhaftes verhalten passiert, ist kein handlungsbedarf
