### ISSUE TITLE
status in attempts table nutzen

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#460]
// Attempt Status.
define('LOCAL_CATQUIZ_ATTEMPT_OK', 0);
define('LOCAL_CATQUIZ_ATTEMPT_ABORTED', 1);

- [x] konstanten erweitern um mögliche abbruch kriterien (> 0)
- [x] in db status speichern
- [x] in readme info dazu ergänzen --> evtl überflüssig, weil enduser sowieso den übersetzten Status string sehen?

**Comment by davidszkiba** [comment]
@eynimeni Es gibt bereits eine andere Stelle, wo alle Status-Werte definiert sind: https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/develop/classes/local/status.php Ich hab es so geändert, dass die strings in integer Werte konvertiert werden können, um sie in der DB zu speichern: [9da868b](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/commit/9da868b855b7d123814b515adcaaba20213ec355)
Bis jetzt werden die Werte nur intern verwendet. Daher weiß ich nicht, wo sie im README dokumentiert werden sollen.

**Comment by davidszkiba** [comment]
@ralferlebach anstatt dass wir im README die einzelnen integer Werte erklären müssen, hab ich in der quiz attempts Ansicht die Statuswerte übersetzt. Also man sieht jetzt statt "0" den Wert "Ok" und statt 8 sieht man "Die Maximalanzahl an Testfragen wurde erreicht".
