### ISSUE TITLE
reportierte skalen in personabilities

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#461]
- [x] im ersten bereich von personabilities sollten:
    - [x] alle zu reportierenden und nciht ausgeschlossenen skalen aufgelistet sein
    - [x] als erste skala die primary scale ('isprimary')
    - [x] danach je nach strategie die sortierweise nach value (ergebnis): von unten nach oben bei inferlowestskillgap, sonst von oben nach unten
- [x] in der darunter liegenden (ersten) grafik:
    - [x]  alle zu reportierenden und nciht ausgeschlossenen skalen anzeigen (= ident mit liste)
    - [x] änderung: 0 wert (relativ zu) ist nicht mehr die primary scale sondern die rootscale (globalskala)

**Comment by davidszkiba** [comment]
Ich hab jetzt die Globalskala als Referenzwert eingestellt. Theoretisch werden in der Skala die Bars für die Globalskala "Simulation" und für "SimA" im Chart angezeigt. Aber da die Balken eine Breite von 0 haben, sieht man sie natürlich nicht.


![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/17564611/5c3ddf9e-5d68-4ddd-800a-72f8c2f7cb22)
