### ISSUE TITLE
bereinigen questionsummary

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#463]
nur die in #420 angegebenen werte anzeigen: 

- [x]  aus graphical summary 1. chart: alles raus außer "Abilitiy in der obersten Skala - danach" -> umbenennen in "Abilitiy in der Global-Skala"
- [x]  aus graphical summary 1. chart: neue Linie: Ability in Skala to report (Werte nach Fragenbeantwortung)

**Comment by ralferlebach** [comment]
In #517 enthalten?

**Comment by davidszkiba** [comment]
Das ist bereits umgesetzt:

![image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/17564611/9561e553-d362-44c8-bf32-fe1bd4ae30b3)

Einzig die Skalenbeschriftung ist wohl nicht optimal. Sieht so aus, als würde hier noch die questionid verwendet. Besser wäre einfach anzugeben, die wievielte Frage es im aktuellen Quiz war.

**Comment by davidszkiba** [comment]
Ja, in #517 enthalten. Die Skalen-Beschriftung hab ich jetzt trotzdem schon mal schnell gefixed.
