### ISSUE TITLE
Fehler: Division by zero

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#467]
Nach Löschung des noch offenen Test-Attempts in adaptivequiz_attempt kommt nun:

<img width="814" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/5e8cb975-851f-41d5-8d69-fac19a0ae415">

**Comment by davidszkiba** [comment]
Solved in the adaptivequizcatmodel_catquiz subplugin version 1.0.1.
