### ISSUE TITLE
AP-87 Create Subplugins that use R packages instead of php implemented algorithms

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#47]
- [x] Setup R Server with REST Interface (plumber)
- [x] Create Subplugin that connects to R Server and uses 1 PL RaschBirnbaum Model
- [ ] Create Subplugin that connects to R Server and uses 2 PL RaschBirnbaum Model
- [ ] Create Subplugin that connects to R Server and uses 3 PL RaschBirnbaum Model
- [ ] Create Subplugin that connects to R Server and uses Partial credit Model
- [ ] Create Subplugin that connects to R Server and uses Graded Response Model

All Plugins should be implemented in a way that they can interface with the already setup administration

**Comment by eynimeni** [comment]
outdated
