### ISSUE TITLE
Error im CATQuizManager

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#472]
Im Frontend ist davon nichts zu merken, aber die ErrorLogs sind voll von diesem Eintrag:

[Tue Apr 30 14:04:37.493705 2024] [php:notice] [pid 44281] [client 132.195.30.12:61513] Default exception handler: Die gesuchte Datei wurde nicht gefunden. Debug: \nError code: filenotfound\n* line 2148 of /lib/filelib.php: moodle_exception thrown\n* line 1853 of /lib/questionlib.php: call to send_file_not_found()\n* line 5140 of /lib/filelib.php: call to question_pluginfile()\n* line 44 of /pluginfile.php: call to file_pluginfile()\n, referer: https://lti.alise.uni-wuppertal.de/local/catquiz/manage_catscales.php?scaleid=91

Bitte prüft einmal, was es damit auf sich hat und fixt die Ursache. Danke.

**Comment by ralferlebach** [comment]
Ist immernoch da.

**Comment by eynimeni** [comment]
falls es wieder auftritt, nachgehen
