### ISSUE TITLE
Fehlerhafte Einschreibungen bei defizit-orientierter Strategie

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#479]
Offensichtlich werden Teilnehmende nicht nur in den Kurs zum größten Defizit eingeschrieben sondern gleich in eine ganze Reihe von Kursen.

Bei dieser Person sollten es eigentlich nur 3 Kurse sein:

<img width="672" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/09a70d78-7374-4baa-8f50-8feff1d2dc67">

**Comment by davidszkiba** [comment]
Es wird nicht auf die primary scale gefiltert. Das muss noch angepasst werden.

**Comment by eynimeni** [comment]
<img width="1145" alt="Screenshot 2024-05-08 at 11 47 07" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/fdba2051-ccbd-4db2-bb87-b61e1a9830bc">

**Comment by ralferlebach** [comment]
Guten Morgen,

ich habe über die aktuelle Lösung noch einmal länger nachgedacht und sie überzeugt mich nicht. Das eigentliche Problem, dass Einschreibungen intransparent vorgenommen werden, bleibt nämlich bestehen.

Folgende 2 Szenarien sind für einen Zestzweck "Diagnostizieren das größte Defizit" denkbar: 
1. es gibt frei verfügbares Material in weiteren Kursen und Lernenden soll der Schritt der Selbsteinschreibung abgenommen werden
In diesem Fall würden alle diese Kurse mit einer Selbsteinschreibung versehen sein/werden, eine Einschreibung ist daher nicht notwendig. Da Einschreibungen unter "Meine Kurse" den Lernenden angezeigt werden, sollte die systembedingte Einschreibung NUR für den/die Kurse der untersten Kompetenz (Defizit) bzw. größten Stärke erfolgen. Anderenfalls würde die intransparente Einschreibung unter Lernenden problematisch empfunden.

2. es gibt undisclosed Material in weiteren Kursen und der Test fungiert als strikter Gate-Keeper
In dem Fall wäre eine Einschreibung in andere Kurse als denen für die unterste Kompetenzlücke sogar Lehrenden-seitig hoch problematisch empfunden.

Für Einschreibung in allen Skalen mit beiden Ergebnissen vorzunehmen, gibt es entsprechende Teststrategien.

Daher bitte: Die Option wieder aus dem Einstellungen entfernen und bei Defizit/Stärke-orientierten Strategien nur in die mit der detektieren Skala und Range assoziierten Kurse und Gruppen einschreiben.

**Comment by ralferlebach** [comment]
Und bitte in der Datenbank bei modifierid = 0 angeben, da es sich um eine systemveranlasste Einschreibung und keine nutzerveranlasste Selbsteinschreibung handelt, @eynimeni.

Das ist bei Moodle m.E. so auch der Standard, siehe oben im Bild die Einschreibung per LTI (modifierid = 0), die zweite Einschreibung hatte ich (id = 2) manuell vorgenommen und daher zur Rückverfolgung meine ID in das Feld eingetragen.

**Comment by davidszkiba** [comment]
> Guten Morgen,
> 
> ich habe über die aktuelle Lösung noch einmal länger nachgedacht und sie überzeugt mich nicht. Das eigentliche Problem, dass Einschreibungen intransparent vorgenommen werden, bleibt nämlich bestehen.
> 
> Folgende 2 Szenarien sind für einen Zestzweck "Diagnostizieren das größte Defizit" denkbar:
> 
>     1. es gibt frei verfügbares Material in weiteren Kursen und Lernenden soll der Schritt der Selbsteinschreibung abgenommen werden
>        In diesem Fall würden alle diese Kurse mit einer Selbsteinschreibung versehen sein/werden, eine Einschreibung ist daher nicht notwendig. Da Einschreibungen unter "Meine Kurse" den Lernenden angezeigt werden, sollte die systembedingte Einschreibung NUR für den/die Kurse der untersten Kompetenz (Defizit) bzw. größten Stärke erfolgen. Anderenfalls würde die intransparente Einschreibung unter Lernenden problematisch empfunden.
> 
>     2. es gibt undisclosed Material in weiteren Kursen und der Test fungiert als strikter Gate-Keeper
>        In dem Fall wäre eine Einschreibung in andere Kurse als denen für die unterste Kompetenzlücke sogar Lehrenden-seitig hoch problematisch empfunden.
> 
> 
> Für Einschreibung in allen Skalen mit beiden Ergebnissen vorzunehmen, gibt es entsprechende Teststrategien.
> 
> Daher bitte: Die Option wieder aus dem Einstellungen entfernen und bei Defizit/Stärke-orientierten Strategien nur in die mit der detektieren Skala und Range assoziierten Kurse und Gruppen einschreiben.

Wir verwenden intern die Begriffe Primärskala bzw "zu-reportierende" Skala.
In der Teststrategie zur Diagnose des größten Defizits ist die Primärskala auch die zu reportierende Skala.
In anderen Teststrategien kann es aber Unterschiede geben. Im klassischen CAT ist die Globalskala die Primärskala aber alle gespielte Skalen werden reportiert. Das gleiche gilt für die "Test all subscales" Strategie.

Daher meine Frage: soll in den Kurs eingeschrieben werden, der mit der Primärskala assoziiert ist? Oder in die Kurse der zu reportierenden Skalen?
