### ISSUE TITLE
AP-88 Implement trusted regions

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#48]
- [ ] Implement trusted region for 3 PL Model algorithm to deal with numeric instability

**Comment by ralferlebach** [comment]
Ich bin mir nicht sicher, wo dies am besten untergebracht wird.

Zunächst die mathematischen Stütz-Formeln für den Schätz-Prozess, die bei kritischen Verläufen hinzugezogen werden sollten. Die zurückgelieferten Funktionen könne/sollten evtl. entsprechend der Anzahl der berechneten Daten noch multipliziert werden, z.B. mit log(n), sodass diese sich auch bei hohen Fallzahlen durchsetzen können.

Diese Formeln/Funktionen sollten in den einzelnen Modellen hinterlegt werden.

Für 1 PL benötigt es nur die Terme zu Parameter a (b kann 0 gesetzt werden), bei 2 PL und 3 PL werden die vollen Terme (mit $a und $b) benötigt

`// Mathematische Berechnung der TR
$function = exp(-1/2 * (($a - $a_m)/($a_s)) ** 2) * 1 / (1 + exp($b_a * ($b - $b_m)));

$d_log_function = [
function ($x) use ($p) { return (($a_m - $a) / $a_s ** 2) }, // d/da
function ($x) use ($p) { return (-($b_a * exp($b_a * $b)) / (exp($b_a * $b_m) + exp($b_a * $b))) } // d/db
];

$dd_log_function = [[
function ($x) use ($p) { return (-1/$a_s ** 2) }, // d/da d/da
function ($x) use ($p) { return (0) } //d/da d/db
],[
function ($x) use ($p) { return (0) }, //d/db d/da
function ($x) use ($p) { return (-($b_a ** 2 * exp($b_a * ($b_l + $b))) / (exp($b_a * $b_l) + exp($b_a * $b)) ** 2) } // d/db d/db
]]; 
`

Die harte Setzung sollte direkt in den Schätz-Algorithmus implementiert werden:

`// Harte Setzung der TR
if (($a - $a_m) < -($a_tr * $a_s)) {$a = -($a_tr * $a_s) - $a_m; }
if (($a - $a_m) > ($a_tr * $a_s)) {$a = ($a_tr * $a_s) - $a_m; }

if ($b < 0) {$b = 0; }
if ($b > ($b_tr * $b_l)) {$b = $b_tr * $b_l; }

if ($c < 0) {$c = 0; }
if ($c > ($c_tr)) {$c = $c_tr; }`


Dabei bedeuten die Werte/Variablen jeweils folgendes:

`$a = $params['discrimination'];
$b = $params['difficulty'];
$c = $params[2];

// Diese Werte sollten ggf. dynamisch bestimmt werden
$a_m = 0; // Mittelwert/Erwartungswert der Schwierigkeiten
$a_s = 2; // Standardabweichung der Schwierigkeiten
$a_tr = 3; // Nutze max. 3 Standardabweichungen als TR (3 * $a_s deckt rund 99,9% aller beobachteten Fälle ab)

$b_l = 5; // Lageparameter der Trennschärfen, unter dem Wert wird Faktor > 0,5, über dem Wert < 0,5
$b_l = 2; // Anstieg der Trennschärfen
$b_tr = 5; // Nutze max. 5 * Lageparameter als TR für die TR

$c_tr = 0.5; // Nutze max. 0.5 als TR für den Rateparameter`

**Comment by davidszkiba** [comment]
Hallo @ralferlebach
Diese Funktionen werden ausgeführt, nachdem eine erste Schätzung der Parameter ermittelt worden ist, richtig? Ich denke, dann wäre der beste Ort um diese Funktionen aufzurufen in der `model_raschmodel` Klasse, direkt nachdem die Parameter geschätzt worden sind: https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/develop/classes/local/model/model_raschmodel.php#L55

Ich werde eine abstract function `restrict_to_trusted_region(array $params)` in `model_raschmodel` hinzufügen und direkt nach der Parameterschätzung aufrufen. Diese Funktion muss dann von allen Unterklassen implementiert werden.

**Comment by ralferlebach** [comment]
Ist implementiert.
