### ISSUE TITLE
Fehler mit Test-Abbruch (aber keine Fehlermeldung in Error-Logs)

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#482]
Aufgefallen bei der Durchsicht der WErgebnisse:
<img width="811" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/7640c570-fe1e-4203-ab0e-abf5c805aef3">

Offensichtlich ein Versuch, der mittendrin mit einem Fehler regulär abgebrochen ist:
<img width="1114" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/6437dc5c-0091-486b-8048-6317fc5e5e9e">

Die einzigen Hinweise auf einen Fehler in den Error-Logs finden sich hier:

[Tue Apr 30 11:37:22.547491 2024] [php:warn] [pid 42304] [client 87.160.106.48:58180] PHP Warning:  Undefined variable $message in /var/www/html/local/catquiz/classes/catquiz.php on line 1816, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php?cmid=2343
[Tue Apr 30 11:37:22.548150 2024] [php:warn] [pid 42304] [client 87.160.106.48:58180] PHP Warning:  Undefined variable $message in /var/www/html/local/catquiz/classes/catquiz.php on line 1816, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php?cmid=2343
sh: 1: /usr/bin/latex: not found
sh: 1: /usr/bin/dvips: not found

Das Progress-JSON lautet:

[progress.318.json](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/15245645/progress.318.json)

Was ist da konkret passiert und wie kann dies in Zukunft verhindert werden?

**Comment by ralferlebach** [comment]
[CATQuiz-Export-Attempt318(3).csv](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/15294881/CATQuiz-Export-Attempt318.3.csv)

**Comment by davidszkiba** [comment]
Wie besprochen:
Eine Möglichkeit hier wäre, dass alle Skalen ausgeschlossen worden sind. Aber das lässt sich mit der jetzigen debuginfo CSV Datei nicht nachvollziehen.

Welche Daten brauchen wir, um einen Versuch nachzustellen? Bzw einen Vesuch nachzuvollziehen?

### Diese Daten sollten in der Debuginfo stehen
Die Anfangsbedingungen müssen gespeichert werden, damit man nachvollziehen kann, wie die erste Frage ausgewählt worden ist. Das heißt:
- [x] Abilities des users vor der ersten Frage -> bereits in 'personabilities' Spalte enthalten. 
- [ ] Durchschnittliche Ability im Test vor der ersten Frage
- [ ] Time penalty information: das basiert auf dem letzten Zeitpunkt, zu der jede Frage gespielt worden ist + der momentanen Zeit
- [ ] In debug info ausgeben, welche Skalen ausgeschlossen/eingeschlossen worden sind.

**Comment by eynimeni** [comment]
add data to debug info

**Comment by davidszkiba** [comment]
Hab mir das nochmal angeschaut.

- Die Informationen über die aktiven Skalen sieht man bereits in der debug info
- Man sieht auch schon die `last time played penalty` für die ausgewählte Frage. Diese Info für *alle* Fragen auszugeben ist denke ich keine gute Idee, da das bei sehr vielen Fragen zu Problemen führen kann.
- Die Spalte `selected_scale` habe ich entfernt, da es jetzt keine selected Scale gibt. Es werden zwar Skalen ein- oder ausgeschlossen, aber es wird nicht explizit eine Skala gewählt, von der eine Frage gezogen wird. Stattdessen wird eine Frage ausgewählt, und ein Skalen-Term trägt zur Gewichtung der Frage bei. In der `lastquestion` Spalte sieht man, welcher Skala eine Frage zugeordnet ist.
