### ISSUE TITLE
Error: Probleme mit Cache

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#493]
[Mon May 06 05:54:21.134400 2024] [php:warn] [pid 147137] [client 185.104.138.50:51031] PHP Warning:  rename(/var/www/moodledata/cache/cachestore_file/default_application/local_catquiz_catscales_num_items/2_3-cache/4CUZKNR7DX.6638546d20bc88.34606524.temp,/var/www/moodledata/cache/cachestore_file/default_application/local_catquiz_catscales_num_items/2_3-cache/2_3_4_5_6_7_8_9_10_88_89_90_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_33_34_35_36_37_38_39_40_41_42_43_44_45_46_47_48_49_50_51_52_53_54_55_56_57_58_59_60_61_62_63_64_65_66_67_68_69_70_71_72_73_74_75_76_77_78_79_80_81_82_83_84_85_86_87-dd25120dd899fdc20385a3f947a78b8a.cache): File name too long in /var/www/html/cache/stores/file/lib.php on line 869, referer: https://lti.alise.uni-wuppertal.de/local/catquiz/manage_catscales.php?scaleid=1

**Comment by davidszkiba** [comment]
Merged into develop
