### ISSUE TITLE
Remove test if activity is removed

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#495]
At the moment, removing a quiz in a course does not remove the test from the `local_catquiz_tests` table. We should fix that

**Comment by eynimeni** [comment]
also remove corresponding attemptdata of deleted test

**Comment by davidszkiba** [comment]
Ähnlich zu #443

**Comment by davidszkiba** [comment]
Hab einen PR im adaptivequiz catmodel subplugin erstellt: https://github.com/Wunderbyte-GmbH/moodle-adaptivequizcatmodel_catquiz/pull/1
