### ISSUE TITLE
Überflüssige Daten aus der Attempts Tabelle automatisch entfernen

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#496]
In einer frühren alise Version sind attempts angelegt worden, die zu viel Platz beanspruchen. Das ist zwar bereits gelöst, aber es sollten trotzdem alte attempts in der DB aufgeräumt werden.

**Comment by ralferlebach** [comment]
- [ ] qtype wordselectinstallieren, Zeile 465 zu einer Division durch 0 manipulieren
- [ ] eine Frage des qtype wordselect anlegen, 9 weitere Fragen aus Simulation-Skala zu einer Skala anlegen (mit Fantasie-Werten, 1 PL)
- [ ] Quiz anlegen und spielen, Error und dessen Folgen auswerten
