### ISSUE TITLE
ERROR: bestehende Kurse werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#498]
Kursseite bleibt nach Update und Einfügen von catquizstatistics leer:

<img width="1419" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/fdc58664-1a10-425b-9eec-f50c76f92adb">

**Comment by ralferlebach** [comment]
Diese Einträge passen (zeitlich) zum Fehler:

[Mon Jun 17 10:20:40.107772 2024] [php:error] [pid 610538] [client 37.201.212.237:16144] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 933888 bytes) in /var/www/html/lib/dml/mysqli_native_moodle_database.php on line 1402, referer: https://lti.alise.uni-wuppertal.de/course/editsection.php?id=2023&sr=0
[Mon Jun 17 10:25:56.731556 2024] [php:error] [pid 610538] [client 37.201.212.237:23487] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 974848 bytes) in /var/www/html/lib/dml/mysqli_native_moodle_database.php on line 1402, referer: https://lti.alise.uni-wuppertal.de/course/editsection.php?id=2023&sr=0
[Mon Jun 17 10:27:34.931648 2024] [php:error] [pid 606958] [client 37.201.212.237:48161] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 974848 bytes) in /var/www/html/lib/dml/mysqli_native_moodle_database.php on line 1402, referer: https://lti.alise.uni-wuppertal.de/course/editsection.php?id=2023&sr=0

**Comment by ralferlebach** [comment]
Ich bekomme leider auch nicht mehr am Frontend ausgegeben:
<img width="1438" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/59991ff5-14d8-4d68-84b4-3fdc87b13533">

**Comment by davidszkiba** [comment]
> Ich bekomme leider auch nicht mehr am Frontend ausgegeben, wenn ich die Fehlerausgabe in den Moodle-Settings zulasse: <img alt="grafik" width="1438" src="https://private-user-images.githubusercontent.com/12737344/340250939-59991ff5-14d8-4d68-84b4-3fdc87b13533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTc4NDYsIm5iZiI6MTcxODYxNzU0NiwicGF0aCI6Ii8xMjczNzM0NC8zNDAyNTA5MzktNTk5OTFmZjUtMTRkOC00ZDY4LTg0YjQtM2ZkYzg3YjEzNTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA5NDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5M2Q3ZGJmZmQ3MzY2ODUwM2E5N2Q3N2NhOTAzOGU2MDAwZTVhMGE5MGE0MDk1ZjYzNmYyN2ZiYTY3NmE3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qwHSaQWusikkFIotbgFGXo91X4ErduDxwnoeHiQ2XP4">



> Ich bekomme leider auch nicht mehr am Frontend ausgegeben, wenn ich die Fehlerausgabe in den Moodle-Settings zulasse: <img alt="grafik" width="1438" src="https://private-user-images.githubusercontent.com/12737344/340250939-59991ff5-14d8-4d68-84b4-3fdc87b13533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTc4NDYsIm5iZiI6MTcxODYxNzU0NiwicGF0aCI6Ii8xMjczNzM0NC8zNDAyNTA5MzktNTk5OTFmZjUtMTRkOC00ZDY4LTg0YjQtM2ZkYzg3YjEzNTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA5NDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5M2Q3ZGJmZmQ3MzY2ODUwM2E5N2Q3N2NhOTAzOGU2MDAwZTVhMGE5MGE0MDk1ZjYzNmYyN2ZiYTY3NmE3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qwHSaQWusikkFIotbgFGXo91X4ErduDxwnoeHiQ2XP4">



> Ich bekomme leider auch nicht mehr am Frontend ausgegeben, wenn ich die Fehlerausgabe in den Moodle-Settings zulasse: <img alt="grafik" width="1438" src="https://private-user-images.githubusercontent.com/12737344/340250939-59991ff5-14d8-4d68-84b4-3fdc87b13533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTc4NDYsIm5iZiI6MTcxODYxNzU0NiwicGF0aCI6Ii8xMjczNzM0NC8zNDAyNTA5MzktNTk5OTFmZjUtMTRkOC00ZDY4LTg0YjQtM2ZkYzg3YjEzNTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA5NDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5M2Q3ZGJmZmQ3MzY2ODUwM2E5N2Q3N2NhOTAzOGU2MDAwZTVhMGE5MGE0MDk1ZjYzNmYyN2ZiYTY3NmE3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qwHSaQWusikkFIotbgFGXo91X4ErduDxwnoeHiQ2XP4">

Ich hab im code nachgesehen: diese Stelle ist in der PHP Funktion `insert_record(...)`. Ich werde nachschauen warum und wo hier Werte in die Datenbank geschrieben werden.

**Comment by ralferlebach** [comment]
Auch mit der Hotfix-Version gibt es übrigens keine genaueren Ausgaben.

**Comment by davidszkiba** [comment]
Ok. Ich versuche es lokal nachzustellen indem ich viele, große attempts in meine lokale Datenbank einfüge

**Comment by ralferlebach** [comment]
Jetzt geht es:
<img width="1440" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/6a11b904-8a0b-4a4f-a15e-2aeef046c8d1">
