### ISSUE TITLE
ERROR: offensichtlich falsche Datenauswahl in Statistik

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#499]
In dem Kurs liegen noch gar keine Test-Versuche vor, trotzdem wird bereits ein Histogramm ausgegeben:

<img width="789" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/acac5f2c-7050-4add-ac28-5f1be4210ad7">

Die zweite Grafik erzeugt einen Fehler:
<img width="809" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/f30a810f-96a1-4d28-99a4-be7107828584">

Gleiches hier:
<img width="796" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/1174f078-fcde-4944-a9f7-624f706d8cc6">

Die Grafik ist korrekt:
<img width="549" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/06c1e0b9-b918-45ca-9795-18c80d82c9b8">

die aber nicht:
<img width="581" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/85534dba-068c-416b-b151-9fc8f9a172b5">

Lernfortschritt zeigt gar nichts an:
<img width="816" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/4bc07bc8-5f70-4b25-b936-75d860e588d4">

Export liefert (noch?) sämtliche Daten zurück:
<img width="830" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/be016aba-8608-4af7-a144-d829019c3e24">

<img width="602" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/ea60db5d-7bda-4de0-bd13-ac759c5c7f0b">

**Comment by ralferlebach** [comment]
In Ergänzung dazu:

In alise.wunderbyte.at](https://alise.wunderbyte.at/course/view.php?id=139#testusage-117

werden keine Daten gefunden, obwohl diese vorliegen müssten bzw. ebenso Fehler produziert:
<img width="734" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/4d9d199b-eba3-40e3-9db6-6ab3f764a317">

**Comment by davidszkiba** [comment]
> In Ergänzung dazu:
> 
> In alise.wunderbyte.at](https://alise.wunderbyte.at/course/view.php?id=139#testusage-117
> 
> werden keine Daten gefunden, obwohl diese vorliegen müssten bzw. ebenso Fehler produziert: <img alt="grafik" width="734" src="https://private-user-images.githubusercontent.com/12737344/340220720-4d9d199b-eba3-40e3-9db6-6ab3f764a317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTk5NjAsIm5iZiI6MTcxODYxOTY2MCwicGF0aCI6Ii8xMjczNzM0NC8zNDAyMjA3MjAtNGQ5ZDE5OWItZWJhMy00MGUzLTlkYjYtNmFiM2Y3NjRhMzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEwMjEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3M2FlMGJlNTRmOTFlYmIwODM4ZDU0ZTdmNTdlZjRhNjdlNmY0Njg5YzM1MzJkODk3MmRhZDBmZjY5YTFlOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zKn4YctismAoPgeNSkhnJswxvtagK5sj_YdYsqoBPG0">

Ich denke hier werden im obersten Chart zu viele attempts angezeigt: 3 attempts kommen vom admin user, obwohl der nicht als Teilnehmer in den Kurs eingeschrieben ist.
In den anderen beiden Charts wird korrekt auf Teilnahme im Kurs gefiltert.
Ich werde hier also im oberen Chart mit den Versuchen pro Tag den Filter auf Kursteilnahme hinzufügen.

**Comment by davidszkiba** [comment]
Dass zu viele Daten angezeigt werden, ist mit hotfix/1.0.1 behoben. Für die falsche Datenauswahl bei den Antworten/Versuchen pro Person gibt es ein separates Issue: #504
