### ISSUE TITLE
ERROR: Errormeldunge bei Log-Daten

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#500]
<img width="1317" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/1c171684-76a8-4fc6-8235-44723195412d">

**Comment by davidszkiba** [comment]
@ralferlebach kannst du das bitte mit einer aktuellen Version nochmal testen, und falls es behoben ist, dieses Issue schließen?

**Comment by ralferlebach** [comment]
Aktuell kann ich den Fehler nicht reproduzieren, daher schließe ich das Issue vorerst.
