### ISSUE TITLE
ERROR: Nicht (mehr) vorhandener Test wird als Datenquelle angezeigt

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#501]
Stammt aus alise.wunderbyte.at
https://alise.wunderbyte.at/course/view.php?id=139#overview-117

<img width="753" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/4b271c31-db66-457a-a598-911c9947b26f">

Einer der beiden Tests wurde vermutlich gelöscht, wird aber als Datenquelle angezeigt.

**Comment by davidszkiba** [comment]
Will be solved in #495

**Comment by davidszkiba** [comment]
Duplicate of #495
