### ISSUE TITLE
ERROR: Farben in Feedbacks verschwunden

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#502]
Wie besprochen

<img width="677" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/62ada145-59c7-4b60-a653-6605f46fdac2">

**Comment by davidszkiba** [comment]
Fixed in ef5b38a8c5b68275052940b4dc0e2f3a022b51af - not yet merged into main but part of the hotfix/1.0.1 branch
