### ISSUE TITLE
ERROR: Tabelle wird nicht angezeigt (alter Datenbestand)

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#503]
in alise.wunderbyte.at (OK):
<img width="704" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/b198d1fa-a78b-4b93-9d94-1f0f84926a2a">

auf lti.alise.uni-wuppertal.de (fehlt):
<img width="728" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/209f0c7e-7f2d-4cad-bc92-e2c7ade8c67f">

**Comment by ralferlebach** [comment]
[json.json](https://github.com/user-attachments/files/15863697/json.json)

**Comment by davidszkiba** [comment]
@ralferlebach könntest du mir bitte auch die json Daten aus dem zugehörigen progress Eintrag schicken? Das wäre der Eintrag in mdl_local_catquiz_progress mit  attemptid 396 und contextid 8
Es wäre vor allem die "json" Spalte interessant, aber auch die "quizsettings"

**Comment by ralferlebach** [comment]
JSON aus Progress
[json.json](https://github.com/user-attachments/files/15886376/json.json)

Quizsettings aus Test
[quizsettings.json](https://github.com/user-attachments/files/15886378/quizsettings.json)

**Comment by davidszkiba** [comment]
@ralferlebach die Ursache dafür ist folgende:
ich habe als Teil der Aufräumarbeiten der attempt feedback Daten, die in der Datenbank gespeichert werden, einen array key "numberofitemsplayed" entfernt. Ich habe zwar kurz später realisiert, dass dieser array key doch benötigt wird, um das feedback korrekt anzuzeigen, aber es sieht so aus, als wäre der Korrektur-commit 140b9be895536ec64adfe6ea5b96339d7dc0e9ac nicht vor 1.0.0 live gegangen.
Das bedeutet, es gibt leider einige feedbacks, in denen diese Daten fehlen.

Ich habe in commit 78f026e27157db49973facf0e30e3dae2ab3d5c2 den code so geändert, dass der Skalenname, die ability und der Standardfehler angezeigt werden, auch wenn "numbeofitemsplayed" nicht gesetzt ist,  aber die Information mit der Anzahl der gespielten Fragen pro Skala nicht angezeigt wird. Also es wird alles bis auf "X ausgewertete Fragen: " angezeigt. Ich bin nicht sicher, ob das ein sehr sauberer Fix ist, weil dadurch evtl zu viele Skalen angezeigt werden.

**Comment by eynimeni** [comment]
im meeting heute 21.6.24 besprochen, für daten einer gewissen phase wird tabelle nicht angezeigt
