### ISSUE TITLE
ERROR: Fehlerhafte Daten in Grafiken

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#504]
Bei den Testversuchen wird korrekterweise angezeigt:
<img width="498" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/70a67279-293c-4ffd-abe1-e5faed4dca53">

aber die zwei folgenden Grafiken zeigen nur zwei Versuche an:
<img width="511" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/c087e5b0-ac1e-43a9-b855-e07c36be998a">

<img width="490" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/0c9ef065-30f5-4c78-bc0c-e8e38e8e2d61">

**Comment by eynimeni** [comment]
handling für alte datenstruktur -> attempt skippen falls auslese nicht möglich ist

**Comment by davidszkiba** [comment]
Das lag vermutlich am Filtern auf Kursteilnahme. Sollte mit der plugin-version 2024062401 behoben sein.
