### ISSUE TITLE
ERROR: Beschreibungen der Fähigkeitsranges werden nicht übernommen

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#505]
<img width="680" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/ca686b4c-535a-426b-8e4e-e2b79d2e375a">

(Wenn die Beschreibungen einheitlich sind, sollten diese - wie die numerischen Ranges - auch übernommen werden.)

aber:
<img width="516" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/f4c1e198-b4b0-4c73-9c39-fcaaed91cb5d">
<img width="486" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/3dbcce4a-1412-4a1f-b2f5-e180b9da8259">
<img width="490" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/077c2445-a11d-490c-b809-373c306ca7f7">
<img width="520" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/7ea19a41-0866-4486-b409-e2302a677580">

**Comment by eynimeni** [comment]
warten auf die gesamtänderungen

**Comment by ralferlebach** [comment]
#513 #517

Bitte zunächst diesen Fehler fixen, dann erst die Legenden ausblenden.

**Comment by ralferlebach** [comment]
Vermutlich mit #513 zusammenhängend.
