### ISSUE TITLE
IMPROVEMENT: Ausblenden div. Legenden und Datentabellen (catquizstatistics)

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#506]
Bei folgenden Grafiken sollen die Legenden ausgeblendet werden (die Möglichkeit, auszublenden, macht keinen Sinn):
<img width="494" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/05ddd6a8-fd4a-4d40-ae38-13df1b9c41d1">
<img width="488" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/44402e4d-6d08-4a06-8b18-309f1e23bb0e">
<img width="513" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/a2522427-b7cb-4559-87f1-011f0e713973">
<img width="544" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/f7bea5b5-a655-4daf-a37a-023fcf30c0d9">

Ebenso bitte auch überall die Datentabellen ausblenden.
<img width="557" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/5bf3627e-4dcd-42bc-b175-7221348b6611">

**Comment by eynimeni** [comment]
wir warten noch auf die gesamtänderungen inkl feedback von philip wie heute besprochen ok, @ralferlebach ?

**Comment by ralferlebach** [comment]
#520
