### ISSUE TITLE
ERROR/IMPROVEMENT: nicht zu reportierende Skalen werden angezeigt, Skalen werden nicht nach Gesamtanzahl geordnet

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#507]
Die Skala "ALiSe Mathematik" ist als nicht zu reportieren hinterlegt, wird aber hier reportiert.

Zudem sollten die Skalen nach Gesamtzahl absteigend geordnet sein.
<img width="482" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/708024c5-b14b-4075-aaad-d3ee8cd8b410">

**Comment by davidszkiba** [comment]
@ralferlebach ich habe gerade eine neue Version mit den Änderungen aus diesem issue gemacht: https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/tree/172d1baa49fde47f2e3ae92c3b3d2b0084b79c34 Könntest du das bitte testen, ob es jetzt so stimmt, und danach ggf schließen?

Der Filter auf zu reportierende Skalen holt sich die Info, ob eine Skala zu reportieren ist, aus dem attempt und nicht aus dem Quiz. Das bedeutet: Falls die Quiz settings geändert werden, betrifft das neue setting nur attempts, die nach dieser Änderung erstellt worden sind.

**Comment by ralferlebach** [comment]
<img width="522" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/2c289fa7-244c-4f6d-8f7d-b727da15930a">
