### ISSUE TITLE
ERROR: Neue Fragen werden in bestehende (gleichlautende) Subskalen eingeordnet, obwohl Baumpfad verschieden ist

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#508]
Hier: Neue Deutsch-Items in Mathematik
<img width="754" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/e35ad1c8-614d-4a70-8a5b-d1b5dba4d6a9">

**Comment by eynimeni** [comment]
@ralferlebach wurde hier der Catquiz Importer verwendet? Stimmt es dass der angebene Skalenname mit einer bestehenden Skala übereinstimmt, keine Skalenid angegeben war und parentscales angegeben waren, die anders sind, als die Parents der gefundenen skala? Oder Hast du evt noch die Import-Datei und den Datenbank scales table zum damaligen Stand?

**Comment by ralferlebach** [comment]
Ja, der Skalenname war gleich, die Angaben zur Parent-Scale nicht. Es handelte sich damit um eine neu anzulegende Skala.

Dennoch wurden die Fragen der (gleichlautenden) Bestandskala zugeordnet.

**Comment by ralferlebach** [comment]
Ja, exakt so würde ich es als Nutzer auch erwarten.

**Comment by davidszkiba** [comment]
Ok.
Im Moment geschieht folgendes:

Nach dem import der zwei Dateien, gibt es folgende Zuordnung:

SimA01-00 SimulationBeta -> SimA -> SimA01 Korrekt
SimA01-01  Simulation-> SimABeta -> SimA01 Korrekt
SimA01-02 SimulationBeta -> SimA -> SimA01 Falsch!
SimA01-03 SimulationBeta -> SimA -> SimA01 Falsch!

Es gibt 3 Skalen SimA01 mit folgender Struktur:

- Simulation -> SimA -> SimA01 : 20 items
- SimulationBeta -> SimA -> SimA01 : 3 items
- Simulation -> SimABeta -> SimA01: 1 item
