### ISSUE TITLE
ERROR: bereits getroffene Einstellungen bei nicht-zu-reportierenden Skalen werden verworfen und überschrieben

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#513]
<img width="813" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/3eaec397-2c93-499d-a955-54ffe3b9066c">
In dieser Skala waren Ranges und Range-Bezeichnungen eingestellt. Nach dem Speichern gehen diese Werte verloren.

Folge (u.a.):
<img width="822" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/3998ef3d-73b2-4f33-a616-90516b45fcde">
statt
<img width="766" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/d4d34aaa-40be-4d73-bf7c-2004cb25e5d4">

(fehlerhafte Ranges, keine Bezeichnung, führt auch zu Problemem bei anderen Statisitk-Grafiken)

**Comment by eynimeni** [comment]
@ralferlebach ich konnte den beschriebenen fehler leider nicht reproduzieren. können wir uns das bitte nochmals gemeinsam ansehen?

**Comment by ralferlebach** [comment]
So ist vorzugehen:

# Test anlegen
# bei den Feedback die Globalskala ausfüllen, Bereiche und Bereichsbezeichnungen eintragen und auf alle Subskalen übertragen
# Reportierem der Globalsskala ausschalten
# Abspeichern
# Test durchführen bzw. Einstellungen erneut öffnen

**Comment by eynimeni** [comment]
zwischen 2 und 3 muss gespeichert werden, dann sollte es gehen

**Comment by ralferlebach** [comment]
Nein, das funktioniert nicht. Bitte wie angegeben testen und fixen!

<img width="857" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/3c9c5262-1d56-4ad5-9653-6ead1d02019b">
(Einstellungen geöffnet, 0,5 als Wert eingestellt, gespeichert, Einstellungen geöffnet, reportieren abgeschaltet, gespeichert, Einstellungen geöffnet - das ist das Ergebnis!)

**Comment by eynimeni** [comment]
Wir haben hierfür jetzt folgende Lösung entworfen:

Im Form alle hideIf und disabledIf raus die auf die Checkbox hören
Dafür Click Listener auf Checkbox, falls sie nicht angeklickt ist den gesamten Hintergrundbereich (card-body) ausgrauen. 
Ideal wäre, der Bereich wo die Collapisbles für andere Skalen liegen in ein eigenes div, das nicht ausgegraut wird. (nur falls es leicht geht)

**Comment by davidszkiba** [comment]
Letzten Punkt mit eigenem `div` hab ich nicht gemacht, aber die card header sind trotzdem nicht ausgegraut.
