### ISSUE TITLE
ERROR: Importer setzt falschen Kontext

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#514]
Import mit folgender Datei durchgeführt (Simulation V2):
[export_CATscales V2.csv](https://github.com/user-attachments/files/15949695/export_CATscales.V2.csv)

Fragen werden korrekt auf Kontext 1 (wie in CSV angegeben) angelegt:
<img width="1052" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/e994480b-ab82-43c1-ac86-c02862898e0a">

Skala jedoch nicht:
<img width="868" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/faf20290-e7c5-422f-8f6e-9bd3d17f097a">

Folge:
Test läuft nicht
<img width="885" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/bf63ca7e-3fca-48e6-8fca-84132916e7f3">

**Comment by eynimeni** [comment]
ja, stimmt, wenn items einem bestehenden context zugeorndet werden, wird der kontext der root-skala nicht upgedated. 
üblicherweise würde ja ein neuer auto-context durch den import erstellt werden. 
es ist kein problem, es im code anzupassen, aber wahrscheinlich sollten wir noch durchdenken, ob das andere unerwünschte konsquenzen bringt.

**Comment by eynimeni** [comment]
wir haben diese Fragen schon in #450 gestellt. setzen wir auf die "to discuss"-liste für eins der nächsten meetings!

**Comment by eynimeni** [comment]
@ralferlebach Nach reiflichen Überlegungen, sind wir zu dem Ergebnis gekommen, dass es am wenigsten fehleranfällig ist, den Context der Root-Scale nur nach automatischer Erzeugung eines Kontextes via Importer umzustellen. 
Wenn jemand neue Items explizit einem bestehenden Kontext zuordnen möchte, bleibt das möglich. In diesem Fall muss dann leidiglich im CAT-Manager Dashboard der Kontext manuell eingestellt werden:
<img width="1009" alt="Screenshot 2024-06-24 at 17 35 53" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/ef5bd76c-036a-4ab1-8467-19bf0fb2bb9e">

Ich habe die Doku noch um diese Infos erweitert.

**Comment by ralferlebach** [comment]
Ich verstehe die Antwort nicht. Was ist nun die Lösung?

Wenn ich eine neue Skala mittels Importer einlese und in der CSV-Datei eine Context-ID angegeben ist, werden dann in Zukunft weiterhin die Fragen und die (neue) Skala unterschiedlichen Contexten zugeordnet?

In dem Fall ist der Fehler nicht behoben - und das Issue ist noch zu lösen.

**Comment by eynimeni** [comment]
TODOs:

- [ ] Wenn neue Skala angelegt wird und dort ist eine contextid angegeben, soll diese contextid für die entsprechende globalskala gesetzt werden
- [ ] Warnung, wenn item eine contextid hat, die nicht in rootscale ausgewählt ist

**Comment by eynimeni** [comment]
nach prüfung von @ralferlebach : fehler ist nicht mehr aufgetreten
