### ISSUE TITLE
Restliche Test-Strategien umsetzen

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#522]
Es fehlen noch:
- [ ] relevante Skalen testen
- [ ] alle Skalen testen

Das Testen auf relevante Skalen werden wir in der ersten Juli-Woche benötigen.

**Comment by ralferlebach** [comment]
#162

**Comment by davidszkiba** [comment]
PR ist erstellt. Wenn die checks grün sind, merge ich
