### ISSUE TITLE
ERROR: Abbruch während des Tests

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#528]
Beschreibung:..

"bei mir ist das System bei einer Checkbox mit Fehler ausgestiegen. Es war die Frage e ^-x

Angeklickt hatte ich den radio-button ‚0‘

Bild hängt an"

<img width="669" alt="Unbenannt" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/67323cf3-4493-48da-be54-564da1d2c6f2">

**Comment by ralferlebach** [comment]
Guten Morgen, Herr Erlebach,

 

den Fehler bekomme ich jetzt übrigens ständig. Eventuell hängt er damit zusammen, dass ich langsam bin: es passiert, dass ich beim Bearbeiten unterbrochen werden und dann meine Antwort länger dauert. Eine Art von ‚timeout‘ hatte ich bislang noch nie, aber eben diesen Fehler. Ich habe aber auch noch nicht auf die Uhr geguckt, ob ich die angekündigte maximale Bearbeitungszeit von 15 Minuten jemals erreicht habe.

Der Test wird nach der Fehlermeldung übrigens gleich wieder neu gestartet.

 

Viele Grüße

**Comment by ralferlebach** [comment]
[Attempt 426.json](https://github.com/user-attachments/files/16049926/Attempt.426.json)

**Comment by davidszkiba** [comment]
Ich denke, das sollte mit f6be18e2d behoben worden sein.
@ralferlebach ich schiebe dieses issue mal auf "in review". Kannst du bitte herausfinden, ob das mit einer aktuellen Version noch auftritt und, falls nicht, dieses Issue schließen?
