### ISSUE TITLE
ERROR: Keine Rückmeldung, wieso kein Ergebnis ermittelt werden konnte

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#529]
Wie lässt sich der Grund hierfür herausfinden und kommunizieren?

<img width="535" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/fc199dd2-7d37-4f1c-bc97-0d172602d7f3">

**Comment by davidszkiba** [comment]
Das lässt sich am besten herausfinden, wenn wir die zugehörigen attempt Daten sehen können. @ralferlebach kannst du den Inhalt der JSON Spalte von dem betroffenen Eintrag in der local_catquiz_attempts DB Tabelle bitte hier teilen?

Der angezeigte String ist eine Art fallback, wenn wir keine genauere Info haben, warum keine Skala angezeigt werden kann. Evtl kann man hier die Beschreibung verbessern.

**Comment by ralferlebach** [comment]
[debug.436.json](https://github.com/user-attachments/files/16240728/debug.436.json)

Hier der Versuch 436
<img width="772" alt="grafik" src="https://github.com/user-attachments/assets/1894a1a9-9f45-4acf-a85d-aaa0db77a57c">

**Comment by davidszkiba** [comment]
@ralferlebach danke, das ist auch JSON, aber aus der "debug_info" Spalte. Könntest du bitte auch den Inhalt der Spalte mit dem Namen "json" hier teilen? Ich möchte nachschauen, ob dort ein "personabilities_abilities" entry vorhanden ist und wenn ja, wie der aussieht. Ich denke, damit lässt sich feststellen, warum hier die Fallback Nachricht verwendet worden ist.

> [debug.436.json](https://github.com/user-attachments/files/16240728/debug.436.json)
> 
> Hier der Versuch 436 <img alt="grafik" width="772" src="https://private-user-images.githubusercontent.com/12737344/348866849-1894a1a9-9f45-4acf-a85d-aaa0db77a57c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDE2NzMsIm5iZiI6MTcyMTEwMTM3MywicGF0aCI6Ii8xMjczNzM0NC8zNDg4NjY4NDktMTg5NGExYTktOWY0NS00YWNmLWE4NWQtYWFhMGRiNzdhNTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDAzNDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMzNiYjVlNTRiNzI2ZDg4OTllYzc4ODAyMjdlNTQ0MWJlYWVlNjk0OTE1MjdiZDcyMDlkNzQ2ODZhMjY2ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eHOPALmkgZ17C_ig29JoDMzwusmLw0-4r6TOMOd4MzM">
