### ISSUE TITLE
ERROR: potentieller Fehler beim Einstieg mit persönlicher Fähigkeit

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#530]
Wir haben drei Versuche derselben Person hintereinander, die Übernahme der vorausgegangenen PP ist eingestellt.

Es scheint jedoch beim Einstiegspunkt Unstimmigkeiten zu geben. Wie lässt sich das prüfen?
1.
<img width="428" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/c67252d1-f172-49ee-b682-a78ed2e44a7f">
2.
<img width="426" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/9d75cd4e-25b1-4109-8272-7dda680f8c87">
3.
<img width="457" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/6aa1dbff-f058-44d3-a054-4afab654e927">

**Comment by davidszkiba** [comment]
Fixed by #595
