### ISSUE TITLE
ERROR: Fehler bei Testende

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#532]
<img width="803" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/5ea1ce78-0a58-40d4-8661-ab7743f7edef">

Strategie: (normaler) CAT
[CATQuiz-Export-Attemptnan.csv](https://github.com/user-attachments/files/16048552/CATQuiz-Export-Attemptnan.csv)

**Comment by ralferlebach** [comment]
Möglicherweise gleich #528

**Comment by ralferlebach** [comment]
[Mon Jul 01 13:41:57.059745 2024] [php:warn] [pid 879528] [client 37.201.212.237:20288] PHP Warning:  Undefined array key "personabilities_abilities" in /var/www/html/local/catquiz/classes/output/attemptfeedback.php on line 452, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php?cmid=8748
[Mon Jul 01 13:41:57.061551 2024] [php:notice] [pid 879528] [client 37.201.212.237:20288] Default exception handler: Fehler: array_filter(): Argument #1 ($array) must be of type array, null given Debug: \nError code: generalexceptionmessage\n* line 451 of /local/catquiz/classes/output/attemptfeedback.php: TypeError thrown\n* line 451 of /local/catquiz/classes/output/attemptfeedback.php: call to array_filter()\n* line 398 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\output\\attemptfeedback->get_courses_to_enrol()\n* line 880 of /local/catquiz/classes/catquiz_handler.php: call to local_catquiz\\output\\attemptfeedback->attempt_finished_tasks()\n* line 47 of /mod/adaptivequiz/catmodel/catquiz/lib.php: call to local_catquiz\\catquiz_handler::attempt_finished()\n* line 82 of /mod/adaptivequiz/classes/output/attempt/attempt_finished_page.php: call to adaptivequizcatmodel_catquiz_attempt_finished_feedback()\n* line 806 of /mod/adaptivequiz/renderer.php: call to mod_adaptivequiz\\output\\attempt\\attempt_finished_page::for_attempt_on_adaptive_quiz()\n* line 68 of /mod/adaptivequiz/attemptfinished.php: call to mod_adaptivequiz_renderer->attempt_finished_page()\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php?cmid=8748

**Comment by ralferlebach** [comment]
Den Fehler gab es wohl auch schon früher:

[Mon Jun 24 10:25:23.890209 2024] [php:warn] [pid 746069] [client 193.175.84.190:37886] PHP Warning:  Undefined array key "personabilities_abilities" in /var/www/html/local/catquiz/classes/output/attemptfeedback.php on line 452, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/view.php?id=8509
[Mon Jun 24 10:25:23.892299 2024] [php:notice] [pid 746069] [client 193.175.84.190:37886] Default exception handler: Fehler: array_filter(): Argument #1 ($array) must be of type array, null given Debug: \nError code: generalexceptionmessage\n* line 451 of /local/catquiz/classes/output/attemptfeedback.php: TypeError thrown\n* line 451 of /local/catquiz/classes/output/attemptfeedback.php: call to array_filter()\n* line 398 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\output\\attemptfeedback->get_courses_to_enrol()\n* line 880 of /local/catquiz/classes/catquiz_handler.php: call to local_catquiz\\output\\attemptfeedback->attempt_finished_tasks()\n* line 47 of /mod/adaptivequiz/catmodel/catquiz/lib.php: call to local_catquiz\\catquiz_handler::attempt_finished()\n* line 81 of /mod/adaptivequiz/classes/output/attempt/attempt_finished_page.php: call to adaptivequizcatmodel_catquiz_attempt_finished_feedback()\n* line 806 of /mod/adaptivequiz/renderer.php: call to mod_adaptivequiz\\output\\attempt\\attempt_finished_page::for_attempt_on_adaptive_quiz()\n* line 68 of /mod/adaptivequiz/attemptfinished.php: call to mod_adaptivequiz_renderer->attempt_finished_page()\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/view.php?id=8509

**Comment by davidszkiba** [comment]
Der Fehler sollte mit f6be18e2d51d9302676463049f5de183563c7473 behoben sein

**Comment by ralferlebach** [comment]
Super. Ich lasse das Frau Brieger, unsere glückliche Gewinnerin des goldenen Errors, heute einmal prüfen und melde (hoffentlich) den erfolgreichen Fix in Form von einen/zwei geschlossenen Issues.
