### ISSUE TITLE
ERROR: Statistik-Grafik zeigt falsche Werte an

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#539]
Die obere Grafik zeigt (glaubhaft) zahlreiche Versuche aus:
<img width="507" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/3ac57a17-1f8c-4181-93dc-fc1ac83cb1a8">

Die untere Grafik besagt, es gäbe nur zwei Personen, eine davon hätte noch gar nicht teilgenommen.
<img width="493" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/4d10ad80-16dc-4db6-9f4f-760dc2455402">

**Comment by ralferlebach** [comment]
betrifft #520

**Comment by davidszkiba** [comment]
@ralferlebach das liegt wohl wieder daran, dass im SQL auf user mit Rolle `student` gefiltert wird, die user, die per LTI eingeschrieben sind, aber nicht diese Rolle haben.
Ich werde, so wie bei der letzten Grafik mit diesem Problem, den `student` Filter wieder herausnehmen.
