### ISSUE TITLE
ERROR: Mindest-Fragezahl wird ständig mit Default-Wert aus Einstellung überschrieben

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#541]
Defaultwert fürs Plugin ist 15, eine Einstellung mit min. 5 Fragen wird nach Speichern und wieder Öffnen der Einstellungen erneut auf 15 gesetzt.

<img width="606" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/7e591609-c41d-41c9-9178-953837ee3f8f">

**Comment by eynimeni** [comment]
mform formular nachschauen wie andere defaults gesetzt werden - option_param default magic number, wenns die ist, default setzen
