### ISSUE TITLE
ERROR: get_rounded_or_null(): Argument #1 ($array) must be of type array, float given (möglicherweise bereits gefixt)

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#543]
Auszug aus den Error-Logs:

[Tue Jul 02 07:09:08.212170 2024] [php:notice] [pid 893803] [client 185.104.138.25:57792] Default exception handler: Fehler: local_catquiz\\teststrategy\\feedbackgenerator::get_rounded_or_null(): Argument #1 ($array) must be of type array, float given, called in [dirroot]/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 191 Debug: \nError code: generalexceptionmessage\n* line 327 of /local/catquiz/classes/teststrategy/feedbackgenerator.php: TypeError thrown\n* line 191 of /local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php: call to local_catquiz\\teststrategy\\feedbackgenerator->get_rounded_or_null()\n* line 156 of /local/catquiz/classes/teststrategy/feedbackgenerator.php: call to local_catquiz\\teststrategy\\feedbackgenerator\\graphicalsummary->load_data()\n* line 291 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\teststrategy\\feedbackgenerator->update_data()\n* line 178 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\output\\attemptfeedback->load_data_from_generators()\n* line 219 of /local/catquiz/classes/teststrategy/strategy.php: call to local_catquiz\\output\\attemptfeedback->update_feedbackdata()\n* line 165 of /local/catquiz/classes/teststrategy/strategy.php: call to local_catquiz\\teststrategy\\strategy->update_attemptfeedback()\n* line 820 of /local/catquiz/classes/catquiz_handler.php: call to local_catquiz\\teststrategy\\strategy->return_next_testitem()\n* line 84 of /mod/adaptivequiz/catmodel/catquiz/classes/local/catmodel/itemadministration/catquiz_item_administration.php: call to local_catquiz\\catquiz_handler::fetch_question_id()\n* line 106 of /mod/adaptivequiz/classes/local/adaptive_quiz_session.php: call to adaptivequizcatmodel_catquiz\\local\\catmodel\\itemadministration\\catquiz_item_administration->evaluate_ability_to_administer_next_item()\n* line 141 of /mod/adaptivequiz/attempt.php: call to mod_adaptivequiz\\local\\adaptive_quiz_session->administer_next_item_or_stop()\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php

sowie

[Tue Jul 02 07:09:58.827952 2024] [php:notice] [pid 890509] [client 185.104.138.25:57811] Default exception handler: Notwendiger Parameter "cmid" fehlt Debug: \nError code: missingparam\n* line 620 of /lib/moodlelib.php: moodle_exception thrown\n* line 35 of /mod/adaptivequiz/attempt.php: call to required_param()\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php?cmid=8748
[Tue Jul 02 07:10:05.443574 2024] [php:notice] [pid 890509] [client 185.104.138.25:57811] Default exception handler: Fehler: local_catquiz\\teststrategy\\feedbackgenerator::get_rounded_or_null(): Argument #1 ($array) must be of type array, float given, called in [dirroot]/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 191 Debug: \nError code: generalexceptionmessage\n* line 327 of /local/catquiz/classes/teststrategy/feedbackgenerator.php: TypeError thrown\n* line 191 of /local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php: call to local_catquiz\\teststrategy\\feedbackgenerator->get_rounded_or_null()\n* line 156 of /local/catquiz/classes/teststrategy/feedbackgenerator.php: call to local_catquiz\\teststrategy\\feedbackgenerator\\graphicalsummary->load_data()\n* line 291 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\teststrategy\\feedbackgenerator->update_data()\n* line 178 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\output\\attemptfeedback->load_data_from_generators()\n* line 219 of /local/catquiz/classes/teststrategy/strategy.php: call to local_catquiz\\output\\attemptfeedback->update_feedbackdata()\n* line 165 of /local/catquiz/classes/teststrategy/strategy.php: call to local_catquiz\\teststrategy\\strategy->update_attemptfeedback()\n* line 820 of /local/catquiz/classes/catquiz_handler.php: call to local_catquiz\\teststrategy\\strategy->return_next_testitem()\n* line 84 of /mod/adaptivequiz/catmodel/catquiz/classes/local/catmodel/itemadministration/catquiz_item_administration.php: call to local_catquiz\\catquiz_handler::fetch_question_id()\n* line 106 of /mod/adaptivequiz/classes/local/adaptive_quiz_session.php: call to adaptivequizcatmodel_catquiz\\local\\catmodel\\itemadministration\\catquiz_item_administration->evaluate_ability_to_administer_next_item()\n* line 141 of /mod/adaptivequiz/attempt.php: call to mod_adaptivequiz\\local\\adaptive_quiz_session->administer_next_item_or_stop()\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php?

sowie

[Tue Jul 02 07:10:25.744777 2024] [php:notice] [pid 894307] [client 185.104.138.25:57824] Default exception handler: Notwendiger Parameter "cmid" fehlt Debug: \nError code: missingparam\n* line 620 of /lib/moodlelib.php: moodle_exception thrown\n* line 35 of /mod/adaptivequiz/attempt.php: call to required_param()\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php?cmid=8748
[Tue Jul 02 07:10:32.356667 2024] [php:notice] [pid 894307] [client 185.104.138.25:57824] Default exception handler: Fehler: local_catquiz\\teststrategy\\feedbackgenerator::get_rounded_or_null(): Argument #1 ($array) must be of type array, float given, called in [dirroot]/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 191 Debug: \nError code: generalexceptionmessage\n* line 327 of /local/catquiz/classes/teststrategy/feedbackgenerator.php: TypeError thrown\n* line 191 of /local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php: call to local_catquiz\\teststrategy\\feedbackgenerator->get_rounded_or_null()\n* line 156 of /local/catquiz/classes/teststrategy/feedbackgenerator.php: call to local_catquiz\\teststrategy\\feedbackgenerator\\graphicalsummary->load_data()\n* line 291 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\teststrategy\\feedbackgenerator->update_data()\n* line 178 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\output\\attemptfeedback->load_data_from_generators()\n* line 219 of /local/catquiz/classes/teststrategy/strategy.php: call to local_catquiz\\output\\attemptfeedback->update_feedbackdata()\n* line 165 of /local/catquiz/classes/teststrategy/strategy.php: call to local_catquiz\\teststrategy\\strategy->update_attemptfeedback()\n* line 820 of /local/catquiz/classes/catquiz_handler.php: call to local_catquiz\\teststrategy\\strategy->return_next_testitem()\n* line 84 of /mod/adaptivequiz/catmodel/catquiz/classes/local/catmodel/itemadministration/catquiz_item_administration.php: call to local_catquiz\\catquiz_handler::fetch_question_id()\n* line 106 of /mod/adaptivequiz/classes/local/adaptive_quiz_session.php: call to adaptivequizcatmodel_catquiz\\local\\catmodel\\itemadministration\\catquiz_item_administration->evaluate_ability_to_administer_next_item()\n* line 141 of /mod/adaptivequiz/attempt.php: call to mod_adaptivequiz\\local\\adaptive_quiz_session->administer_next_item_or_stop()\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php?

sowie

[Tue Jul 02 10:48:45.085627 2024] [php:notice] [pid 897212] [client 132.195.236.37:60307] Default exception handler: Fehler: local_catquiz\\teststrategy\\feedbackgenerator::get_rounded_or_null(): Argument #1 ($array) must be of type array, float given, called in [dirroot]/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 191 Debug: \nError code: generalexceptionmessage\n* line 327 of /local/catquiz/classes/teststrategy/feedbackgenerator.php: TypeError thrown\n* line 191 of /local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php: call to local_catquiz\\teststrategy\\feedbackgenerator->get_rounded_or_null()\n* line 156 of /local/catquiz/classes/teststrategy/feedbackgenerator.php: call to local_catquiz\\teststrategy\\feedbackgenerator\\graphicalsummary->load_data()\n* line 291 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\teststrategy\\feedbackgenerator->update_data()\n* line 178 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\output\\attemptfeedback->load_data_from_generators()\n* line 219 of /local/catquiz/classes/teststrategy/strategy.php: call to local_catquiz\\output\\attemptfeedback->update_feedbackdata()\n* line 165 of /local/catquiz/classes/teststrategy/strategy.php: call to local_catquiz\\teststrategy\\strategy->update_attemptfeedback()\n* line 820 of /local/catquiz/classes/catquiz_handler.php: call to local_catquiz\\teststrategy\\strategy->return_next_testitem()\n* line 84 of /mod/adaptivequiz/catmodel/catquiz/classes/local/catmodel/itemadministration/catquiz_item_administration.php: call to local_catquiz\\catquiz_handler::fetch_question_id()\n* line 106 of /mod/adaptivequiz/classes/local/adaptive_quiz_session.php: call to adaptivequizcatmodel_catquiz\\local\\catmodel\\itemadministration\\catquiz_item_administration->evaluate_ability_to_administer_next_item()\n* line 141 of /mod/adaptivequiz/attempt.php: call to mod_adaptivequiz\\local\\adaptive_quiz_session->administer_next_item_or_stop()\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php
[Tue Jul 02 10:49:05.356124 2024] [php:notice] [pid 897213] [client 132.195.236.37:60311] Default exception handler: Notwendiger Parameter "cmid" fehlt Debug: \nError code: missingparam\n* line 620 of /lib/moodlelib.php: moodle_exception thrown\n* line 35 of /mod/adaptivequiz/attempt.php: call to required_param()\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php?cmid=8748
[Tue Jul 02 10:49:12.730931 2024] [php:notice] [pid 897213] [client 132.195.236.37:60311] Default exception handler: Fehler: local_catquiz\\teststrategy\\feedbackgenerator::get_rounded_or_null(): Argument #1 ($array) must be of type array, float given, called in [dirroot]/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 191 Debug: \nError code: generalexceptionmessage\n* line 327 of /local/catquiz/classes/teststrategy/feedbackgenerator.php: TypeError thrown\n* line 191 of /local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php: call to local_catquiz\\teststrategy\\feedbackgenerator->get_rounded_or_null()\n* line 156 of /local/catquiz/classes/teststrategy/feedbackgenerator.php: call to local_catquiz\\teststrategy\\feedbackgenerator\\graphicalsummary->load_data()\n* line 291 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\teststrategy\\feedbackgenerator->update_data()\n* line 178 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\output\\attemptfeedback->load_data_from_generators()\n* line 219 of /local/catquiz/classes/teststrategy/strategy.php: call to local_catquiz\\output\\attemptfeedback->update_feedbackdata()\n* line 165 of /local/catquiz/classes/teststrategy/strategy.php: call to local_catquiz\\teststrategy\\strategy->update_attemptfeedback()\n* line 820 of /local/catquiz/classes/catquiz_handler.php: call to local_catquiz\\teststrategy\\strategy->return_next_testitem()\n* line 84 of /mod/adaptivequiz/catmodel/catquiz/classes/local/catmodel/itemadministration/catquiz_item_administration.php: call to local_catquiz\\catquiz_handler::fetch_question_id()\n* line 106 of /mod/adaptivequiz/classes/local/adaptive_quiz_session.php: call to adaptivequizcatmodel_catquiz\\local\\catmodel\\itemadministration\\catquiz_item_administration->evaluate_ability_to_administer_next_item()\n* line 141 of /mod/adaptivequiz/attempt.php: call to mod_adaptivequiz\\local\\adaptive_quiz_session->administer_next_item_or_stop()\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php?

**Comment by ralferlebach** [comment]
War gestern immer noch häufiger (!) Fehler:

[Wed Jul 03 12:57:11.825061 2024] [php:notice] [pid 918183] [client 132.195.59.245:42324] Default exception handler: Fehler: local_catquiz\\teststrategy\\feedbackgenerator::get_rounded_or_null(): Argument #1 ($array) must be of type array, string given, called in [dirroot]/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 196 Debug: \nError code: generalexceptionmessage\n* line 327 of /local/catquiz/classes/teststrategy/feedbackgenerator.php: TypeError thrown\n* line 196 of /local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php: call to local_catquiz\\teststrategy\\feedbackgenerator->get_rounded_or_null()\n* line 156 of /local/catquiz/classes/teststrategy/feedbackgenerator.php: call to local_catquiz\\teststrategy\\feedbackgenerator\\graphicalsummary->load_data()\n* line 291 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\teststrategy\\feedbackgenerator->update_data()\n* line 178 of /local/catquiz/classes/output/attemptfeedback.php: call to local_catquiz\\output\\attemptfeedback->load_data_from_generators()\n* line 219 of /local/catquiz/classes/teststrategy/strategy.php: call to local_catquiz\\output\\attemptfeedback->update_feedbackdata()\n* line 165 of /local/catquiz/classes/teststrategy/strategy.php: call to local_catquiz\\teststrategy\\strategy->update_attemptfeedback()\n* line 820 of /local/catquiz/classes/catquiz_handler.php: call to local_catquiz\\teststrategy\\strategy->return_next_testitem()\n* line 84 of /mod/adaptivequiz/catmodel/catquiz/classes/local/catmodel/itemadministration/catquiz_item_administration.php: call to local_catquiz\\catquiz_handler::fetch_question_id()\n* line 106 of /mod/adaptivequiz/classes/local/adaptive_quiz_session.php: call to adaptivequizcatmodel_catquiz\\local\\catmodel\\itemadministration\\catquiz_item_administration->evaluate_ability_to_administer_next_item()\n* line 141 of /mod/adaptivequiz/attempt.php: call to mod_adaptivequiz\\local\\adaptive_quiz_session->administer_next_item_or_stop()\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php?

**Comment by ralferlebach** [comment]
Ist noch immer ein Problem:

"Nach Abgabe der ersten Frage kam eine Fehlermeldung 
![grafik](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/7295c707-cefe-4fd1-890b-71c3e39fb144)"

und:
"Zur Kenntnisnahme siehe Screenshot der Fehlermeldung.

Den Champagner können Sie an folgende Adresse schicken zwinkernd:
(Adresse}
![grafik](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/84295c16-e087-4322-8a3f-53b5b5be7a49)"

**Comment by davidszkiba** [comment]
@ralferlebach in welcher Version tritt das auf?
Ich verstehe nicht, warum in der Fehlermeldung Zeile 196 steht. 
https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/2024070400/classes/teststrategy/feedbackgenerator/graphicalsummary.php#L196 Der Aufruf von `get_rounded_or_null()` passiert in der 2024070400 Version in Zeile 218.

**Comment by ralferlebach** [comment]
@davidszkiba: Es muss eine frühere Version gewesen sein, dies beim Einsatz am 3. Juli aufgetreten ist.

Welche Version es war, kann ich nicht sagen. Gibt es in Moodle ein Update-Log für Plugins (wann wurde welche Version installiert)?

**Comment by davidszkiba** [comment]
Ok. Ich weiß leider nichts von so einem upgrade log. Hab mal schnell gegoogelt und dieses plugin gefunden, aber selbst das speichert nur die upgrades von moodle core: https://moodle.org/plugins/report_upgradelog

**Comment by ralferlebach** [comment]
Ich habe mal meinen Download-Ordner durchgesehen. Möglicherweise war es Version 2024070100, denn 202407020x machten massiv Probleme.
