### ISSUE TITLE
ERROR: Undefined array key 91

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#544]
[Tue Jul 02 14:47:57.877102 2024] [php:warn] [pid 899741] [client 132.195.235.94:53275] PHP Warning:  Undefined array key 91 in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/report/stats/index.php
[Tue Jul 02 14:47:57.877166 2024] [php:warn] [pid 899741] [client 132.195.235.94:53275] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/report/stats/index.php
[Tue Jul 02 14:47:57.888693 2024] [php:warn] [pid 899741] [client 132.195.235.94:53275] PHP Warning:  Undefined array key 91 in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/personabilities.php on line 501, referer: https://lti.alise.uni-wuppertal.de/report/stats/index.php
[Tue Jul 02 14:47:57.888722 2024] [php:warn] [pid 899741] [client 132.195.235.94:53275] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/personabilities.php on line 501, referer: https://lti.alise.uni-wuppertal.de/report/stats/index.php
[Tue Jul 02 14:47:57.956661 2024] [php:warn] [pid 899741] [client 132.195.235.94:53275] PHP Warning:  Undefined array key 91 in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/report/stats/index.php
[Tue Jul 02 14:47:57.956692 2024] [php:warn] [pid 899741] [client 132.195.235.94:53275] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/report/stats/index.php
[Tue Jul 02 14:47:58.252882 2024] [php:warn] [pid 899741] [client 132.195.235.94:53275] PHP Warning:  Undefined array key 91 in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/report/stats/index.php
[Tue Jul 02 14:47:58.252918 2024] [php:warn] [pid 899741] [client 132.195.235.94:53275] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/report/stats/index.php
[Tue Jul 02 14:47:58.259345 2024] [php:warn] [pid 899741] [client 132.195.235.94:53275] PHP Warning:  Undefined array key 91 in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/personabilities.php on line 501, referer: https://lti.alise.uni-wuppertal.de/report/stats/index.php
[Tue Jul 02 14:47:58.259373 2024] [php:warn] [pid 899741] [client 132.195.235.94:53275] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/personabilities.php on line 501, referer: https://lti.alise.uni-wuppertal.de/report/stats/index.php
[Tue Jul 02 14:47:58.349151 2024] [php:warn] [pid 899741] [client 132.195.235.94:53275] PHP Warning:  Undefined array key 91 in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/report/stats/index.php

usw. usw.

und dann:

Tue Jul 02 14:48:02.421732 2024] [php:warn] [pid 899741] [client 132.195.235.94:53275] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/personabilities.php on line 501, referer: https://lti.alise.uni-wuppertal.de/report/stats/index.php
[Tue

**Comment by davidszkiba** [comment]
Sollte mit 6727af5d5 und 18df618cb behoben sein.
@ralferlebach Kannst du das bitte nochmal mit einer aktuellen Release (>= 2024070802) testen und, falls es nicht mehr auftritt, dieses Issue schließen?

**Comment by ralferlebach** [comment]
Hehe, dazu müsste ich wissen, wie das überhaupt passiert ist. :-D

Ich schaue heute abend die Error-Logs noch einmal durch, dann schließe ich, sofern das nicht noch einmal aufgetreten ist.
