### ISSUE TITLE
ERROR: Trying to access array on key of type null

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#545]
[Tue Jul 02 14:50:49.676749 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Undefined array key "personabilities_abilities" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:49.676880 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:49.676888 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:49.679274 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Undefined array key "primaryscale" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:49.679317 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:49.980586 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Undefined array key "personabilities_abilities" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:49.980635 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:49.980649 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:49.983004 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Undefined array key "primaryscale" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:49.983041 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.284549 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Undefined array key "personabilities_abilities" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.284583 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.284605 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.286937 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Undefined array key "primaryscale" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.286961 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.588104 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Undefined array key "personabilities_abilities" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.588165 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.588173 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.590554 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Undefined array key "primaryscale" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.590591 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.892305 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Undefined array key "personabilities_abilities" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.892350 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.892364 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.894682 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Undefined array key "primaryscale" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:50:50.894718 2024] [php:warn] [pid 900455] [client 132.195.26.148:50203] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/modedit.php?update=8748&return=1
[Tue Jul 02 14:58:07.074085 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Undefined array key "personabilities_abilities" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.074164 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.074230 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.078169 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Undefined array key "primaryscale" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.078230 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.152850 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Undefined array key "personabilities_abilities" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.152905 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.152945 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.156876 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Undefined array key "primaryscale" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.156932 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.230465 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Undefined array key "personabilities_abilities" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.230548 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.230558 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.234603 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Undefined array key "primaryscale" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.234661 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.310105 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Undefined array key "personabilities_abilities" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.310188 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.310198 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.313987 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Undefined array key "primaryscale" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.314071 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.388921 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Undefined array key "personabilities_abilities" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.389045 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.389079 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.392874 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Undefined array key "primaryscale" in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226
[Tue Jul 02 14:58:07.392977 2024] [php:warn] [pid 900455] [client 132.195.26.148:50241] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/graphicalsummary.php on line 83, referer: https://lti.alise.uni-wuppertal.de/course/view.php?id=1226

**Comment by davidszkiba** [comment]
Sollte mit 812eb9524 und 18df618cb  behoben sein

@ralferlebach kannst du das mit einer aktuellen release (>= 2024070802) bitte nochmal testen und, falls es nicht mehr auftritt, dieses Issue schließen? Ich schiebe es mal auf "In Review"
