### ISSUE TITLE
ERROR: Nutzerrückmeldung "vergangene Feedbacks nicht mehr einzusehen"

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#548]
<img width="1255" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/947ab77e-2091-4711-b3b7-a7629d2aa5ca">

Ich kann dies bestätigen, die Ergebnisse werden auch für mich nicht angezeigt.

vermutlich in Zusammenhang mit #544 und #545

**Comment by davidszkiba** [comment]
@ralferlebach kannst du das nach dem nächsten Update bitte nochmal überprüfen und dieses issue ggf schließen?
