### ISSUE TITLE
ERROR: Fehler bei Zeitüberschreitung

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#549]
Rückmeldung aus dem Dez. 6:

ich habe heute getestet was passiert, wenn ich einfach über die vorgegebene Zeit komme. Ich habe den Test begonnen und dann ab Frage 6 keine Aktivität mehr gezeigt. Irgendwann habe ich versucht (weit über den 25 Minuten Gesamtzeit) die Frage zu beantworten. Ich konnte diese anklicken, aber es kam die Fehlermeldung siehe Screenshot. Was erscheint regulär bei einer Zeitüberschreitung? Gut wäre eine Meldung wie: „Leider ist die Zeit abgelaufen! Bitte starte den Test neu.“

![grafik](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/7bad967d-3995-4fdb-80b0-6df47284a5f8)

**Comment by ralferlebach** [comment]
Nur kurz zur Info/Transparenz:

Ich habe jetzt die Version auf unserem LTI-Server auf die letzte Version 1.0.1 (2024070100) zurückgerollt, damit wir heute einen möglichst fehlerfreien Einsatz in der Lehrveranstaltung haben.

**Comment by davidszkiba** [comment]
Sieht nach dem gleichen Problem wie #550 aus. Wenn  #550 behoben ist, sollten wir nochmal die Zeitüberschreitung testen.
