### ISSUE TITLE
ERROR: Undefined array key * in comparetotestaverage.php|personabilities.php

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#551]
[Wed Jul 03 07:09:30.435278 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  **Undefined array key 214 in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php** on line 395, referer: https://moodle.uni-wuppertal.de/
[Wed Jul 03 07:09:30.435346 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://moodle.uni-wuppertal.de/
[Wed Jul 03 07:09:30.748446 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  Undefined array key 214 in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://moodle.uni-wuppertal.de/
[Wed Jul 03 07:09:30.748523 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://moodle.uni-wuppertal.de/
[Wed Jul 03 07:09:30.754032 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  **Undefined array key 214 in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/personabilities.php** on line 501, referer: https://moodle.uni-wuppertal.de/
[Wed Jul 03 07:09:30.754069 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/personabilities.php on line 501, referer: https://moodle.uni-wuppertal.de/
[Wed Jul 03 07:09:31.499206 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  Undefined array key 91 in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://moodle.uni-wuppertal.de/
[Wed Jul 03 07:09:31.499263 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://moodle.uni-wuppertal.de/
[Wed Jul 03 07:09:31.504993 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  Undefined array key 91 in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/personabilities.php on line 501, referer: https://moodle.uni-wuppertal.de/
[Wed Jul 03 07:09:31.505042 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/personabilities.php on line 501, referer: https://moodle.uni-wuppertal.de/
[Wed Jul 03 07:09:31.783786 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  Undefined array key 91 in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://moodle.uni-wuppertal.de/
[Wed Jul 03 07:09:31.783853 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/comparetotestaverage.php on line 395, referer: https://moodle.uni-wuppertal.de/
[Wed Jul 03 07:09:31.787914 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  Undefined array key 91 in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/personabilities.php on line 501, referer: https://moodle.uni-wuppertal.de/
[Wed Jul 03 07:09:31.787963 2024] [php:warn] [pid 912599] [client 132.195.170.82:60971] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/local/catquiz/classes/teststrategy/feedbackgenerator/personabilities.php on line 501, referer: https://moodle.uni-wuppertal.de/

**Comment by davidszkiba** [comment]
Passieren diese Fehler während der Ausführung eines Tests, oder beim Anzeigen der Feedbacks von vergangenen Tests?

**Comment by ralferlebach** [comment]
@ralferlebach  : Error-Logs checken, schließen

**Comment by ralferlebach** [comment]
Scheint behoben.
