### ISSUE TITLE
ERROR: Fehler beim Schreiben der Datenbank

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#552]
[Wed Jul 03 12:53:33.397695 2024] [php:notice] [pid 917980] [client 132.195.56.79:58163] Default exception handler: **Fehler beim Schreiben der Datenbank Debug: Duplicate entry '485-33'** for key 'mdl_quesatte_queslo_uix'\nINSERT INTO mdl_question_attempts (questionusageid,slot,behaviour,questionid,variant,maxmark,minfraction,maxfraction,flagged,questionsummary,rightanswer,responsesummary,timemodified) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)\n-- line 1528 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()\n-- line 136 of /question/engine/datalib.php: call to mysqli_native_moodle_database->insert_record()\n-- line 1604 of /question/engine/datalib.php: call to question_engine_data_mapper->insert_question_attempt()\n-- line 98 of /question/engine/lib.php: call to question_engine_unit_of_work->save()\n-- line 122 of /mod/adaptivequiz/catmodel/catquiz/classes/local/catmodel/itemadministration/catquiz_item_administration.php: call to question_engine::save_questions_usage_by_activity()\n-- line 106 of /mod/adaptivequiz/catmodel/catquiz/classes/local/catmodel/itemadministration/catquiz_item_administration.php: call to adaptivequizcatmodel_catquiz\\local\\catmodel\\itemadministration\\catquiz_item_administration->get_slot_for_question()\n-- line 106 of /mod/adaptivequiz/classes/local/adaptive_quiz_session.php: call to adaptivequizcatmodel_catquiz\\local\\catmodel\\itemadministration\\catquiz_item_administration->evaluate_ability_to_administer_next_item()\n-- line 141 of /mod/adaptivequiz/attempt.php: call to mod_adaptivequiz\\local\\adaptive_quiz_session->administer_next_item_or_stop()\n[array (\n  0 => '485',\n  1 => 33,\n  2 => 'deferredfeedback',\n  3 => '4510',\n  4 => 1,\n  5 => 4.0,\n  6 => 0,\n  7 => 1.0,\n  8 => 0,\n  9 => 'Vereinfachen Sie f\xc3\xbcr reelle Zahlen [a, b, c, d] den gegebenen Term so weit wie m\xc3\xb6glich!\n\n_[\\\\displaystyle\\\\left(\\\\frac{a^2b^3}{cd}\\\\right)^3 : \\\\displaystyle\\\\left(\\\\frac{a^2b^2}{c^2d^4}\\\\right)^2=a^{n_1}\\\\cdot b^{n_2}\\\\cdot c^{n_3}\\\\cdot d^{n_4}]_\n\n_\n_\n\n_Erg\xc3\xa4nzen Sie die richtige L\xc3\xb6sung in die freien Felder._\n\n_[n_1=]_____ und [n_2=]_____ und [n_3=]_____ und [n_4=]_____\n_\n\n',\n  10 => 'Teil 1: 2; Teil 2: 5; Teil 3: 1; Teil 4: 5',\n  11 => NULL,\n  12 => 1720004013,\n)]\nError code: dmlwriteexception\n* line 497 of /lib/dml/moodle_database.php: dml_write_exception thrown\n* line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()\n* line 1482 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()\n* line 1528 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()\n* line 136 of /question/engine/datalib.php: call to mysqli_native_moodle_database->insert_record()\n* line 1604 of /question/engine/datalib.php: call to question_engine_data_mapper->insert_question_attempt()\n* line 98 of /question/engine/lib.php: call to question_engine_unit_of_work->save()\n* line 122 of /mod/adaptivequiz/catmodel/catquiz/classes/local/catmodel/itemadministration/catquiz_item_administration.php: call to question_engine::save_questions_usage_by_activity()\n* line 106 of /mod/adaptivequiz/catmodel/catquiz/classes/local/catmodel/itemadministration/catquiz_item_administration.php: call to adaptivequizcatmodel_catquiz\\local\\catmodel\\itemadministration\\catquiz_item_administration->get_slot_for_question()\n* line 106 of /mod/adaptivequiz/classes/local/adaptive_quiz_session.php: call to adaptivequizcatmodel_catquiz\\local\\catmodel\\itemadministration\\catquiz_item_administration->evaluate_ability_to_administer_next_item()\n* line 141 of /mod/adaptivequiz/attempt.php: call to mod_adaptivequiz\\local\\adaptive_quiz_session->administer_next_item_or_stop()\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/view.php?id=816

**Comment by davidszkiba** [comment]
Laut stacktrace tritt das auf, wenn ein CAT quiz gespielt wird - ich denke aber nicht, dass das die Ursache ist. Ursache ist evtl ein falscher Counter/Index in der Datenbank.

Ich habe folgende issues gefunden, die sehr ähnlich aussehen:

- https://moodle.org/mod/forum/discuss.php?d=347529
- https://github.com/KQMATH/moodle-mod_capquiz/issues/166

@ralferlebach wir könnten uns das vielleicht mal gemeinsam per adminer ansehen?

**Comment by ralferlebach** [comment]
Scheint behoben.
