### ISSUE TITLE
ERROR: CatManager crasht dauerhaft, nachdem Skala angelegt wurde (auch nach De- und Re-Installation der Plugins)

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#553]
Rückmeldung von Alexander Dominicus (Hochschule Bochum):

"ich habe alle deine Plugins nochmal testweise auf ein anderes System installiert (Moodle 4.4.1+).
Nachdem alles installiert war habe ich die Fragen importiert und aus Systemebene geschoben. 
Dann wollte ich im CAT-Manager die CSV hochladen. Da habe ich einen Fehler erhalten, dass irgendwas mit dem delimiter (halt “;” oder “,”….Genauen Error habe ich leider weggeklickt….sorry) nicht passt.
Ab dem Zeitpunkt habe ich jedesmal, wenn ich den CAT-Manager aufrufen will folgende Fehlermeldung 

![grafik](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/f04eb860-8fbc-4a09-b0ee-ad78ae8195c3)

Fehler: local_catquiz\catscale::get_link_to_catscale(): Argument #1 ($catscaleid) must be of type int, null given, called in [dirroot]/local/catquiz/classes/event/catscale_created.php on line 71

[Weitere Informationen über diesen Fehler](http://docs.moodle.org/404/de/error/moodle/generalexceptionmessage)
Debug-Info: 
Error code: generalexceptionmessage
Stack trace: 

    line 607 of /local/catquiz/classes/catscale.php: TypeError thrown
    line 71 of /local/catquiz/classes/event/catscale_created.php: call to local_catquiz\catscale::get_link_to_catscale()
    line 81 of /local/catquiz/classes/table/event_log_table.php: call to local_catquiz\event\catscale_created->get_description()
    line 862 of /lib/tablelib.php: call to local_catquiz\table\event_log_table->col_description()
    line 729 of /local/wunderbyte_table/classes/wunderbyte_table.php: call to flexible_table->format_row()
    line 506 of /local/wunderbyte_table/classes/wunderbyte_table.php: call to local_wunderbyte_table\wunderbyte_table->build_table()
    line 414 of /local/wunderbyte_table/classes/wunderbyte_table.php: call to local_wunderbyte_table\wunderbyte_table->printtable()
    line 116 of /local/catquiz/classes/output/catscalemanager/eventlogtableinstance.php: call to local_wunderbyte_table\wunderbyte_table->outhtml()
    line 191 of /local/catquiz/classes/output/catscalemanager/managecatscaledashboard.php: call to local_catquiz\output\catscalemanager\eventlogtableinstance->render_event_log_table()
    line 67 of /local/catquiz/manage_catscales.php: call to local_catquiz\output\catscalemanager\managecatscaledashboard->__construct()

Ich habe schon die beiden CATquiz-Plugins (das local und das mod) deinstalliert und wieder installiert. Das ändert jedoch nichts.
Hast du ne Idee was hier schief läuft.

Laut der Readme ist die normale Abfolge
1.) Plugins installieren
2.) XML-Fragen importieren und aus Systemebene schieben
3.) CSV-Datei zur Verknüpfung der Fragen mit den Schwierigkeiten im CAT-Manager hochladen

Muss vorher noch irgendeine Skala oder so angelegt werden?"

**Comment by ralferlebach** [comment]
die Idee mit den Tabellen löschen hatte ich auch schon. Allerdings sollten ja bei der Plugin deinstallation alle Tabelle mit deinstalliert werden. Und das scheint hier auch so zu sein: Nach der Deinstallation des mod und der local-Plugins sind keine entsprechenden Tabellen mehr vorhanden. 

Zur Fehler-Reproduktion:
- Da es im 4.3-System komplett reibungslos funktioniert würde ich vermuten, dass die Ursache vielleicht bei Moodle 4.4 zu suchen ist?
- Vorgehen bevor der Fehler auftrat: 
- Alle Plugins installiert (ohne Zwischenfälle)
- XML-Fragen importiert und auf Systemebene geschoben
- Im CAT-Manager versucht die CSV zu importieren, alle Einstellungen auf standard belassen. Hier gab es eine Fehlermeldung mit den Trennzeichen der CSV (leider weggeklickt)
- Plugin lief noch und ich habe auf “Skala hinzufügen” geklickt. Ab diesem Zeitpunkt kam nur noch die Fehlermeldung aus der letzten Mail. 


Generell will ich mit dem Error keinen Stress erzeugen: Auf dem einen System läuft. Das reicht für mich, dass ich erstmal mit der Erstellung einer eigenen CSV für eigene Fragen rumspielen kann.
Am Freitag habe ich zwischen 10 und 12 eine Termin. Ansonsten könntest du mich auch in das Gespräch mit dem Entwickler holen.

**Comment by davidszkiba** [comment]
@ralferlebach Könntest du bitte die XML Datei für die Fragen und die CSV Datei vom Import hier teilen, damit wir es damit prüfen können?

**Comment by ralferlebach** [comment]
[export_CATscales V2.csv](https://github.com/user-attachments/files/16125108/export_CATscales.V2.csv)

**Comment by ralferlebach** [comment]
[export_questionbank V2.xml.zip](https://github.com/user-attachments/files/16125124/export_questionbank.V2.xml.zip)

**Comment by ralferlebach** [comment]
Problem ist gelöst, aber Ursache besteht noch:

<img width="602" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/76735dd9-20c8-4030-a48a-234097c8b10c">

**Comment by ralferlebach** [comment]
vs.
<img width="736" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/9b93c065-315e-4cc1-8291-fb932ebfc12b">
(Moodle 4.3)

**Comment by eynimeni** [comment]
@ralferlebach auf deiner moodle 4.4 plattform tritt der fehler nicht auf, oder?

**Comment by davidszkiba** [comment]
Ich habe es jetzt in einer VM mit Moodle 4.4 und MariaDB getestet - dort kann ich es leider noch nicht reproduzieren.

**Comment by davidszkiba** [comment]
Ich habe in bf8b88037 das Auslesen der Eventdaten angepasst. Evtl behebt das den Fehler, aber da ich ihn nicht reproduzieren kann, kann ich das nicht mit Sicherheit sagen.
Die Änderungen sind in der Release mit Tag 2024070900 enthalten: https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/tree/2024070900

**Comment by ralferlebach** [comment]
OK, wir werden es mit Sicherheit erst in ein oder zwei Tagen erfahren, da moodle.nrw bzw. die RUB sich mit dem Update aktuell sehr schwer tun...

**Comment by ralferlebach** [comment]
Scheint erledigt
