### ISSUE TITLE
ERROR: Test berechnet offensichtlich nicht korrektes Ergebnis, Grafik fehlerhaft und passt nicht zur Tabelle

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#555]
Es geht um die Einschätzung der defizitären Skala B02:

<img width="748" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/22f1f1ce-9e04-4c31-b505-c7400f9b2f3a">

Diese Einschätzung kommt offenbar zustande, obwohl der Fähigkeitswert in der Globalskala deutlich höher liegt UND alle Fragen in der Skala B02 ausnahmslos korrekt beantwortet wurden (bitte auf Fragen aus B02 achten!):
<img width="741" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/97fcb2d0-3e17-40a1-98c4-383b7021c325">
<img width="733" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/a2df8195-84b4-4030-bc52-190d481f5ceb">
<img width="724" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/6546bbd1-b4a1-41f2-b195-92c9d5d3fa83">
<img width="727" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/b256e618-70b7-446e-a4f3-709da38eedb3">
<img width="717" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/67f85bd1-5c49-4640-a5f0-5613ce065413">

Zudem zeigt die Grafik einen merkwürdigen Verlauf: Die Kurve für B02 folgt der der Globalskala, obwohl keine Frage daraus ge3spielt wurde und weist "Knicke" bei Fragenummern auf (z.B. 18, 19), die ebenso nicht zur Skala B02 zuzurechnen sind.
<img width="424" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/ffbd09c4-98bf-415d-bb7e-be99d1a04e43">

**Comment by ralferlebach** [comment]
#558

**Comment by eynimeni** [comment]
solved
