### ISSUE TITLE
IMPROVEMENT: Angabe eines Nicht auszulieferenden Ergebnisses

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#556]
![grafik](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/6712f9e4-8288-48c6-a912-69421adbda92)

"Der Test hat bei mir nach 12 Fragen einfach abgebrochen, mit lediglich der Information, dass die Werte zu keiner Skala passen. 

Ich hätte mir etwas mehr Informationen über den Abbruch gewünscht, so musste das "Problem" mündlich besprochen werden"

Ich dachte, das wäre bereits umgesetzt...

**Comment by davidszkiba** [comment]
@ralferlebach Ja sollte bereits umgesetzt sein. Wir verwenden interne Fehlercodes, um festzustellen, welche Rückmeldung gegeben werden soll. Da gibt es bestimmte Fehlercodes für "alle Fragen richtig" und "alle Fragen falsch". Wenn es ein unbekannter code ist, wird als Fallback das Feedback verwendet, das hier berichtet worden ist ("Es konnte zu keiner Skala ein valides Ergebnis ermittelt werden").
Könntest du bitte die Daten aus der local_catquiz_attempts und local_catquiz_progress DB Tabelle zu diesem Versuch hier anhängen? Dann kann ich nachschauen, welcher Fehlercode das war.

**Comment by davidszkiba** [comment]
duplicate of #529 ?

**Comment by davidszkiba** [comment]
Wird in #529 behandelt
