### ISSUE TITLE
Umgang mit beliebigen fractions

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#558]
> Die Fraction einer Frage ist nicht notwendigerweise 0 u 1, sondern es kann auch Fragen mit Fraction 4 oder einem beliebigen anderen Wert geben. Man muss praktisch auch auf den maxgrade des entsprechenden Gradeitems schauen, um sicher zu sein.

Das muss noch implementiert werden

**Comment by davidszkiba** [comment]
In der questions Tabelle gibt es eine Spalte `defaultmark` - evtl geht es damit?

**Comment by ralferlebach** [comment]
Aktueller Datenbestend (nur local_catquiz im Einsatz):

<img width="405" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/036ad176-82f1-4b44-a1c8-3b112d8df2de">

**Comment by davidszkiba** [comment]
Es kommt wohl doch nicht vor, dass einen Fraction > 1 ist. Da wir den Fall, dass 0.999999 nicht als 1 gewertet wird bereits gelöst haben, schließe ich das Issue.
