### ISSUE TITLE
QA: manage_catscales - error on subitems creation

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-local_catquiz#56]
The following error occurs when sub-scale has been added 
Moodle exception: Exception - Warning: Undefined property: stdClass::$minmaxgroup in [dirroot]/local/catquiz/classes/form/modal_manage_catscale.php on line 215 File: /lib/behat/lib.php Line: 157 Stack trace: Error code: generalexceptionmessage * line 157 of /lib/behat/lib.php: Exception thrown * line 215 of /local/catquiz/classes/form/modal_manage_catscale.php: call to behat_error_handler() * line 116 of /local/catquiz/classes/form/modal_manage_catscale.php: call to local_catquiz\form\modal_manage_catscale->get_data() * line 77 of /lib/form/classes/external/dynamic_form.php: call to local_catquiz\form\modal_manage_catscale->process_dynamic_submission() * line 261 of /lib/externallib.php: call to core_form\external\dynamic_form::execute() * line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

        Exception - Warning: Undefined property: stdClass::$minmaxgroup in [dirroot]/local/catquiz/classes/form/modal_manage_catscale.php on line 215 (Exception)
        
 Reasons:
 The following fields  
![image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/91992970-1ae5-4ddd-bd8e-40a9017fea8f)
-  available for top-level CAT scale only
- and NOT avalialble in editing form for their child items - but required per code.

**Comment by eynimeni** [comment]
recheck to make sure that this is done correctly now

**Comment by eynimeni** [comment]
@semteacher can you please check if this is still an issue or if it can be closed?

**Comment by semteacher** [comment]
In fact it was solved long time ago - but I adjust test to ensure that decimal numbers have been envolved...
