### ISSUE TITLE
ERROR: Nach Anlegen einer neuen Skala im CAT-Manager gleicher Fehler wie in #553

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#562]
O-Ton Alexander:

"…und nochmal ich:

nachdem die Simulation nun auf unserem HSK.NRW-Server funktioniert hat (da waren Skalen schon vorangelegt) habe ich nun selber probiert eine Skala anzulegen 
("Skala hinzufügen” -> Name gegeben usw. )
Danach kam dann wieder der altbekannte Fehler (wie im Testsystem). Und ab da an auch jedes Mal, wenn man in den CAT-Manager geht:

Fehler: Argument 1 passed to local_catquiz\catscale::get_link_to_catscale() must be of the type int, null given, called in [dirroot]/local/catquiz/classes/event/catscale_created.php on line 71

[Weitere Informationen über diesen Fehler](http://docs.moodle.org/401/de/error/moodle/generalexceptionmessage)
Debug-Info: 
Error code: generalexceptionmessage
Stack trace: 

    line 616 of /local/catquiz/classes/catscale.php: TypeError thrown
    line 71 of /local/catquiz/classes/event/catscale_created.php: call to local_catquiz\catscale::get_link_to_catscale()
    line 81 of /local/catquiz/classes/table/event_log_table.php: call to local_catquiz\event\catscale_created->get_description()
    line 842 of /lib/tablelib.php: call to local_catquiz\table\event_log_table->col_description()
    line 729 of /local/wunderbyte_table/classes/wunderbyte_table.php: call to flexible_table->format_row()
    line 506 of /local/wunderbyte_table/classes/wunderbyte_table.php: call to local_wunderbyte_table\wunderbyte_table->build_table()
    line 414 of /local/wunderbyte_table/classes/wunderbyte_table.php: call to local_wunderbyte_table\wunderbyte_table->printtable()
    line 116 of /local/catquiz/classes/output/catscalemanager/eventlogtableinstance.php: call to local_wunderbyte_table\wunderbyte_table->outhtml()
    line 191 of /local/catquiz/classes/output/catscalemanager/managecatscaledashboard.php: call to local_catquiz\output\catscalemanager\eventlogtableinstance->render_event_log_table()
    line 67 of /local/catquiz/manage_catscales.php: call to local_catquiz\output\catscalemanager\managecatscaledashboard->__construct()

PS: Ich habe beim erstellen der Skala eigentlich nur einen Namen vergeben und sonst nix. Kann es sein, dass das “verboten” ist? Muss man vielleicht noch eine Überskala definieren oder sowas?"

**Comment by ralferlebach** [comment]
vermutlich zusammenhängend mit #553

**Comment by davidszkiba** [comment]
Das sieht tatsächlich nach dem gleichen Problem wie in #553 aus. Ich schließe dieses Issue als duplicate
