### ISSUE TITLE
IMPROVMENT: Performance bei CAT-Manager bei HSK.nrw extrem langsam

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#563]
vermutlich abhängig von Umfang der Fragensammlung

**Comment by ralferlebach** [comment]
Info von Alexander:

IGCHE-Moodle (wo es den Fehler mit der CatscaleID gab): MariaDB 11.4
Matrix-Moodle (wo es KEINEN Fehler mit der CatscaleID gab): MariaDB 10.7
HSK-Moodle (Wo es auch einen Fehler gab): MariaDB 10.6

**Comment by ralferlebach** [comment]
#570

**Comment by ralferlebach** [comment]
=> #584

**Comment by eynimeni** [comment]
nicht mehr relevant, war ein programmierfehler
