### ISSUE TITLE
ERROR: Testabbruch mit Fehler, wenn im Hintergrund Test-Strategie umgestellt wird

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#564]
CAT-Quiz mit Strategie "Klassischer Test" anlegen

Test-Versuch gestartet

CAT-Quiz zu Strategie "Defizit" umgestellt

Test-Versuch fortsetzen

Fehler:
<img width="961" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/75c38015-a64f-4255-bba6-114d5e962f8d">

**Comment by davidszkiba** [comment]
@ralferlebach Da ist wohl eine nicht aktuelle Version vom catquiz subplugin installiert. Der Aufruf der Funktion `catquiz_handler::attemptfeedback()` ist hier durch einen anderen Aufruf ersetzt worden: https://github.com/Wunderbyte-GmbH/moodle-adaptivequizcatmodel_catquiz/commit/e9ab1907d39ed6d444418af636ee15d2775500d0

Ich habe ein git tag `2024062800` für die letzte aktuelle Version des subplugins erstellt. Diese Version ist hier zu finden: https://github.com/Wunderbyte-GmbH/moodle-adaptivequizcatmodel_catquiz/tree/2024062800
