### ISSUE TITLE
ERROR: Vergleichsskala (Globalskala) wird nicht angezeigt

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#566]
Aktuelle Version, aktuelle Daten,

unter "Details zu Ihrem Ergebnis" wird das Ergebnis in der Globalskala als Vergleichswert nicht angezeigt.
<img width="727" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/f647ab0c-bad3-4ca5-af52-35340dc3d6e4">

**Comment by davidszkiba** [comment]
Das passiert, wenn die Globalskala als nicht zu reportieren eingestellt ist...

**Comment by ralferlebach** [comment]
Can we fix it?

(Als Vergleichsbasis sollten an der Stelle natürlich die Daten aus der Skala angezeigt werden. ;-)
