### ISSUE TITLE
ERROR: local_catquiz\task\recalculate_cat_model_params

### ISSUE THREAD

**Issue by Dmfama20** [Wunderbyte-GmbH/moodle-local_catquiz#568]
Bei dem Task "Modellparameter neu berechnen" wird seit der Version 2024070802 folgender Fehler ausgegeben:

Execute scheduled task: CAT Parameter neu berechnen (local_catquiz\task\recalculate_cat_model_params)
... started 00:34:01. Current memory use 33.5 MB.
... used 2 dbqueries
... used 0.0060441493988037 seconds
Scheduled task failed: CAT Parameter neu berechnen (local_catquiz\task\recalculate_cat_model_params),local_catquiz\catmodel_info::needs_update(): Argument #1 ($context) must be of type local_catquiz\catcontext, stdClass given, called in /var/www/html/local/catquiz/classes/task/recalculate_cat_model_params.php on line 73
Backtrace:
* line 73 of /local/catquiz/classes/task/recalculate_cat_model_params.php: call to local_catquiz\catmodel_info->needs_update()
* line 410 of /lib/classes/cron.php: call to local_catquiz\task\recalculate_cat_model_params->execute()
* line 208 of /lib/classes/cron.php: call to core\cron::run_inner_scheduled_task()
* line 125 of /lib/classes/cron.php: call to core\cron::run_scheduled_tasks()
* line 186 of /admin/cli/cron.php: call to core\cron::run_main_process()

**Comment by davidszkiba** [comment]
Fixed by #598
