### ISSUE TITLE
Performance: Fragen ausspielen

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#569]
falls db calls nach jeder frage passieren, die erst für das rendern des feedbacks nötig sind, sollten diese erst zum zeitpunkt wenn das feedback gerendert werden
zwischen den fragen dauert db queries time 4 -5 sekunden bei ralf am lti system und 1s noch dazu für die gesamtladezeit
DB reads 2944 -> oder wird hier jede Frage einzeln abgefragt?

![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/aa696f41-71c0-4fef-8515-9b462456b479)

**Comment by ralferlebach** [comment]
O-Ton Nutzer:
"Ich habe das Gefühl, dass es ein Moodle-Problem ist. Ich konnte gerade einen Deutschtest normal durchlaufen (habe es auch mal endlich auf immerhin 24 Fragen gebracht). Allerdings hat sich bei mir manches sehr langsam geladen. Insbesondere beim Aufgabenergebnisse absenden waren die Reaktionszeiten eher gebremst. Am Netz kann es nicht liegen, ich bin an der Uni im LAN."

**Comment by ralferlebach** [comment]
Scheint gelöst.
