### ISSUE TITLE
IMPROVMENT: Performance des CAT-Managers verbessern

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#570]
Hier einmal die Ladezeiten (200 s) von Alex' HSK-Moodle

<img width="903" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/9e828424-be39-48a4-a6f1-0aa156632340">

ca. 32.000 Fragen sind da im System
<img width="324" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/709f1650-a3a1-47a5-b31d-ce570eb0286b">
<img width="387" alt="grafik" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/12737344/76dbbc8a-f4ac-4459-9d01-7c6dbfaa50e7">

**Comment by eynimeni** [comment]
- [ ] event table ist nicht lazy load, evt. hier einen button zum nachladen
- [ ] checken ob die anderen wb_tables alle lazy laden

**Comment by ralferlebach** [comment]
![grafik](https://github.com/user-attachments/assets/9db032db-ade4-4a5e-bc55-50765f42a142)

**Comment by ralferlebach** [comment]
Ist gelöst.
