### ISSUE TITLE
ERROR: attempts_by_timerange INT expected, NULL given

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#574]
local_catquiz Version: 2024070802
 
"irgendwie bin ich dann doch zum Deutsch-Test gekommen und dann kam die Fehlermeldung, die ähnlich aussieht wie die von Christian Martin am 2.7.. Nach dem Klick auf weiter, fing der Test von vorne an. Ich hatte bis dahin ca 11 Fragen beantwortet."

![grafik](https://github.com/user-attachments/assets/766baf2e-349c-4289-8b32-1611dda88168)

**Comment by ralferlebach** [comment]
Attempts werden im Shortcode ohne jeglichen Inhalt angezeigt:

<img width="775" alt="grafik" src="https://github.com/user-attachments/assets/c04ba49f-13be-4d18-91f9-3a166985d2f1">

**Comment by davidszkiba** [comment]
Das sollte mit acb6cd8c6 behoben sein - das ist in der Release mit plugin version 2027070900 enthalten.
Damit wird nicht versucht, die Grafik anzuzeigen, wenn keine Primärskala erkannt worden ist.
Es wäre trotzdem interessant zu wissen, wie das JSON von dem local_catquiz_attempts Eintrag zu diesem Versuch aussieht. Anscheinend ist hier keine primaryscale gesetzt und ich würde gerne verstehen, warum nicht. @ralferlebach könntest du bitte die JSON Spalte aus der Datenbank hier teilen?

**Comment by ralferlebach** [comment]
Ist gelöst.
