### ISSUE TITLE
ERROR: Erklärtext wird nicht angezeigt

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#575]
local_catquiz-Version: 2024070802

So wird es erwartet:
<img width="740" alt="grafik" src="https://github.com/user-attachments/assets/7d697e62-376c-4b22-8e73-f5cc180267e5">

so sah ein Testversuch gestern aus:
<img width="801" alt="grafik" src="https://github.com/user-attachments/assets/2efce76d-552c-4ec9-8ba9-333d2be1592a">

und so der nächstfrühere:
<img width="743" alt="grafik" src="https://github.com/user-attachments/assets/bb929642-881e-4e9a-9793-cbe9d230002f">

**Comment by davidszkiba** [comment]
@ralferlebach ich denke der Text ist in einem Fall nicht angezeigt worden, weil es das schlechteste Ergebnis im Test war.
Früher war der Vergleichstext etwas kürzer (in etwa "Sie sind besser als X% im Kurs") und da haben wir es nicht angezeigt, wenn da gestanden wäre "Sie sind besser als 0% im Kurs".

Soll der Fall, dass man das schlechteste Ergebnis hat, gesondert behandelt werden oder zeigen wir hier einfach "besser als 0%" an?

**Comment by ralferlebach** [comment]
@davidszkiba : Wir sollten besser nicht "Du bist die dümmste Birne hier im Raum" kommunizieren - besser fände ich, wenn dieser eine Satz erst angezeigt wird, wenn der Prozentwert echt größer als Null, vielleicht sogar größer als xx Prozent (10%, 15%?) angezeigt würde.

Und: Können wir die Umbrüche, die ursprünglich im Text waren, umsetzen? Im Moment wirkt der Text etwas unübersichtlich.

**Also statt bisher:**
Der Test misst Ihr Wissen und Können in „ALiSe Deutsch” in Form eines Fähigkeitswertes zwischen -5.00 und 5.00. Je höher Ihr Fähigkeitswert ausfällt, desto besser ist Ihr Wissen und Ihr Können in der Skala. Ihr erreichter Fähigkeitswert ist 2.00 (mit einem Standardfehler von ± 0.30). Der aktuelle durchschnittliche Fähigkeitswert aller Teilnehmenden an dem Test beträgt 0.86. Mit Ihrem Ergebnis sind Sie momentan besser als 80% aller anderen Test-Teilnehmenden. Die folgende Graﬁk stellt Ihren Fähigkeitswert (obere Markierung) und den aktuellen Durchschnitt (untere Markierung) dar: 

**Besser:**
Der Test misst Ihr Wissen und Können in „ALiSe Deutsch” in Form eines Fähigkeitswertes zwischen -5.00 und 5.00. Je höher Ihr Fähigkeitswert ausfällt, desto besser ist Ihr Wissen und Ihr Können in der Skala. 

Ihr erreichter Fähigkeitswert ist 2.00 (mit einem Standardfehler von ± 0.30). Der aktuelle durchschnittliche Fähigkeitswert aller Teilnehmenden an dem Test beträgt 0.86. Mit Ihrem Ergebnis sind Sie momentan besser als 80% aller anderen Test-Teilnehmenden. 

Die folgende Graﬁk stellt Ihren Fähigkeitswert (obere Markierung) und den aktuellen Durchschnitt (untere Markierung) dar:
