### ISSUE TITLE
ERROR: potentieller Unterschied bei der Darstellung der Grafik als Ergebnis und als Shortcode

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#576]
Die Grafik sah im Test-Ergebnis anders aus (andere Vergleichsbasis) als in der Darstellung im Shortcode.

Beim Testergebnis waren alle drei Balken nach links gehend und in dunkelrot gefärbt, jetzt im Shortcode so:

<img width="543" alt="grafik" src="https://github.com/user-attachments/assets/5a7e101c-46d2-4026-ad04-e06cd1518fa6">

**Comment by davidszkiba** [comment]
Ich hab das versucht zu reproduzieren aber nicht geschafft. Ich kann mir, wenn ich mir den code anschaue, schwer erklären, wie das möglich ist.
Es wird der gleiche Code verwendet, um die Grafik im direkt auf das Quiz folgenden Feedback anzuzeigen und um sie in den Shortcodes anzuzeigen.
Falls das nochmal auftreten sollte, wäre es sehr hilfreich, wenn ich die JSON Daten aus der local_catquiz_attempts Datenbank Tabelle zu beiden Zeitpunkten sehen könnte.

**Comment by ralferlebach** [comment]
OK, gut. Ich schließe das mal.

Allerdings lässt sich das mit den JSONs nicht organisieren, da ja der Unterschied erst hzum späteren Zeitpunkt auffällt, wenn er denn auffallen sollte.
