### ISSUE TITLE
Teststrategien mit Mindesttestfagenanzahl

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#577]
Test, deren Mindestfagenanzahl nicht erreicht werden, sollen als solche kein Ergebnis berichten.
("Es konnte kein Testergebnis ermittelt werden, das die Mindestanzahl an zu beantortenden Fragen nicht erreicht wurde.")

**Comment by davidszkiba** [comment]
Feedback mit genug Fragen:

![image](https://github.com/user-attachments/assets/b3257cea-ba2b-4093-83ff-db3483231f13)

Feedback wenn Mindestanzahl nicht erreicht:

![image](https://github.com/user-attachments/assets/195f9991-2224-4fa3-8d02-dc02a5cdf30f)

Es werden also auch nicht die Tabs angezeigt
