### ISSUE TITLE
Invalid English string

### ISSUE THREAD

**Issue by mudrd8mz** [Wunderbyte-GmbH/moodle-local_catquiz#587]
https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/cab7679fecc1cbc8aa1b7d13f1abd4c9bde3c6d1/lang/en/local_catquiz.php#L253

**Comment by davidszkiba** [comment]
Thank you for noticing and opening this issue @mudrd8mz 
Should be fixed now in the 1.0.3 release
