### ISSUE TITLE
ERROR: MariaDB Speicherüberlauf

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#588]
Hängt dies mit unserem Plugin zusammen? (Andere Anwendungen laufen auf dem LTI-System nicht)

sudo systemctl status mariadb
<img width="1059" alt="grafik" src="https://github.com/user-attachments/assets/3ebb5259-f144-453a-beea-c46f0d516c4e">

Nach einem Restart der DB 
sudo systemctl restart mariadb

läuft es wieder.

**Comment by davidszkiba** [comment]
Hi Ralf,
kann es sein, dass der verfügbare Speicherplatz knapp wird? Error 28 bedeutet normalerweise, dass nicht genügend Platz auf der Festplatte vorhanden ist.

**Comment by ralferlebach** [comment]
Hmm... das kann eigentlich nicht sein.

Zudem läuft nach einem Neustart des SQL-Servers alles wieder einwandfrei. Grundsätzlich fehlernder Speicherplatzh wäre ja von einem Neustart nicht betroffen.

**Comment by davidszkiba** [comment]
@ralferlebach ok. Ich hätte noch das hier gefunden: https://dba.stackexchange.com/questions/198569/the-table-is-full-mariadb
Falls das der Grund ist, dann liegt es vermutlich an einer SQL query, in der recht viele Daten zwischengespeichert werden. Ich weiß nicht auswendig, ob es von mariadb logs gibt, in denen langsame oder große Queries aufgelistet werden. Falls ja, dann könnten wir so die entsprechende Query finden.

MariaDB läuft hier direkt am Server und nicht in einem docker container, richtig?

**Comment by davidszkiba** [comment]
Ah doch, es gibt für MariaDB ein slow query log: https://mariadb.com/kb/en/slow-query-log-overview/

**Comment by eynimeni** [comment]
nicht mehr aufgetreten
