### ISSUE TITLE
Dependencies missing in version.php

### ISSUE THREAD

**Issue by mudrd8mz** [Wunderbyte-GmbH/moodle-local_catquiz#597]
There are requirements for specific version of `mod_adaptivequiz` and for `adaptivequizcatmodel_catquiz` in https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/9a03f3b469b96f8e8c649da28749f1dd387538fb/README.md#dependencies

However, the version.php only mentions `local_wunderbyte_table`:

https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/9a03f3b469b96f8e8c649da28749f1dd387538fb/version.php#L33

Is there a reason for that? Why not to have `mod_adaptivequiz` and `adaptivequizcatmodel_catquiz` there too?

**Comment by davidszkiba** [comment]
@mudrd8mz Thank you for noticing, I added those dependencies now.
