### ISSUE TITLE
error duplicate id value from sql query

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#60]
Did you remember to make the first column something unique in your call to get_records? Duplicate value '902' found in column 'id'.
line 1049 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()
line 2123 of /lib/tablelib.php: call to pgsql_native_moodle_database->get_records_sql()
line 839 of /local/wunderbyte_table/classes/wunderbyte_table.php: call to table_sql->query_db()
line 428 of /local/wunderbyte_table/classes/wunderbyte_table.php: call to local_wunderbyte_table\wunderbyte_table->query_db_cached()
line 349 of /local/wunderbyte_table/classes/wunderbyte_table.php: call to local_wunderbyte_table\wunderbyte_table->printtable()
line 255 of /local/catquiz/classes/output/questionsdisplay.php: call to local_wunderbyte_table\wunderbyte_table->outhtml()
line 288 of /local/catquiz/classes/output/questionsdisplay.php: call to local_catquiz\output\questionsdisplay->renderquestionstable()
line 69 of /local/catquiz/manage_catscales.php: call to local_catquiz\output\questionsdisplay->export_for_template()

For catquiz::return_sql_for_catscalequestions()
here for example: http://10.111.0.3:8000/local/catquiz/edit_catscale.php?id=1#testitems

**Comment by davidszkiba** [comment]
Fixed by @bernhard-wunderbyte in 23322ce
