### ISSUE TITLE
Fehler und Warnungen von moodle.org beheben

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#600]
Es geht um die zahlreichen Fehler und Warnungen in den Code Checks und Mustache Checks auf Moodle.org
<img width="555" alt="grafik" src="https://github.com/user-attachments/assets/8faef409-d8a7-4f76-91ef-e5fdd6257307">

https://moodle.org/plugins/local_catquiz/1.0.2/32710?smurf=html#phpcs

Diese sollten mit der nächsten Version (1.0.3) schnellst möglichst behoben werden, sodass öffentliches Vertrauen in das Plugin etabliert werden kann.

**Comment by eynimeni** [comment]
hier braucht es ein update was wirklich noch aktuell ist

**Comment by eynimeni** [comment]
- [ ] 2h zeitbudget für fix javascrit code behat tests 4.4 -> evt. einfach von vitaly abschreiben
- [ ] mustache failures anschauen

-> ziel wäre alles möglich grün zu bekommen in max 1/2 tag

**Comment by eynimeni** [comment]
unit tests für 405 fixen
