### ISSUE TITLE
Logging verbessern - ERROR: Diverse Errors aus den letzten Tagen

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#603]
* [Thu Jul 25 08:57:22.517816 2024] [php:notice] [pid 327601] [client 132.195.42.153:52931] Default exception handler: Benutzen Sie nicht den Zur\xc3\xbcck-Button, wenn Sie Fragen bearbeiten. Debug: QUBAid: 594, slot: 1, post data: stdClass Object\n(\n
und
* [Thu Jul 25 08:58:11.740133 2024] [php:notice] [pid 327647] [client 104.28.54.67:65497] Default exception handler: Notwendiger Parameter "cmid" fehlt Debug: \nError code: missingparam\n* line 548 of /lib/classes/param.php: moodle_exception thrown\n* line 426 of /lib/classes/param.php: call to core\\param->get_request_parameter()\n* line 646 of /lib/moodlelib.php: call to core\\param->required_param()\n* line 35 of /mod/adaptivequiz/attempt.php: call to required_param()\n
[error.log.2.txt](https://github.com/user-attachments/files/16506683/error.log.2.txt)

* [Wed Jul 24 10:41:46.327011 2024] [php:notice] [pid 303680] [client 95.222.119.79:16766] Default exception handler: Notwendiger Parameter "attempt" fehlt Debug: \nError code: missingparam\n* line 548 of /lib/classes/param.php: moodle_exception thrown\n* line 426 of /lib/classes/param.php
[error.log.3.txt](https://github.com/user-attachments/files/16506697/error.log.3.txt)

* [Tue Jul 23 09:24:42.431174 2024] [php:warn] [pid 286503] [client 95.222.118.183:26489] PHP Warning:  Undefined property: stdClass::$catquiz_catscales in /var/www/html/local/catquiz/classes/shortcodes.php on line 322, referer: https://lti.alise.uni-wuppertal.de/course/index.php?categoryid=1
* [Tue Jul 23 09:28:18.452701 2024] [php:notice] [pid 286270] [client 95.222.118.183:1215] Default exception handler: Keine g\xc3\xbcltigen Argumente angegeben Debug: \nError code: invalidarguments\n* line 49 of /mod/adaptivequiz/view.php: moodle_exception thrown\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/attempt.php
* [Tue Jul 23 11:58:22.818302 2024] [php:notice] [pid 286272] [client 95.222.118.183:26439] Default exception handler: Sie haben aktuell nicht das Recht, dies zu tun (Adaptiven Test starten). Debug: \nError code: nopermissions\n* line 875 of /lib/accesslib.php: required_capability_exception thrown\n* line 76 of /mod/adaptivequiz/attempt.php: call to require_capability()\n, referer: https://lti.alise.uni-wuppertal.de/mod/adaptivequiz/view.php?id=816
* [Tue Jul 23 14:38:38.147554 2024] [php:notice] [pid 296877] [client 95.222.119.215:61879] Default exception handler: Fehler: No standarderror is set for scale 1 Debug: \nError code: generalexceptionmessage\n* line 301 of /local/catquiz/classes/teststrategy/feedbacksettings.php: Exception thrown\n* line 180 of /local/catquiz/classes/teststrategy/strategy/inferlowestskillgap.php: call to local_catquiz\\teststrategy\\feedbacksettings->filter_semax()\n* line 260 of /local/catquiz/classes/teststrategy/feedbackgenerator.php
[error.log.4.txt](https://github.com/user-attachments/files/16506721/error.log.4.txt)

**Comment by davidszkiba** [comment]
> [Tue Jul 23 14:38:38.147554 2024] [php:notice] [pid 296877] [client 95.222.119.215:61879] Default exception handler: Fehler: No standarderror is set for scale 1 Debug: \nError code: generalexceptionmessage\n* line 301 of /local/catquiz/classes/teststrategy/feedbacksettings.php: Exception thrown\n* line 180 of /local/catquiz/classes/teststrategy/strategy/inferlowestskillgap.php: call to local_catquiz\teststrategy\feedbacksettings->filter_semax()\n* line 260 of /local/catquiz/classes/teststrategy/feedbackgenerator.php

Wird hier verursacht: https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/main/classes/teststrategy/feedbacksettings.php#L298

Wenn in den moodle settings debug Nachrichten auf off gesetzt sind, sollte dieser Fehler nicht kommen.
Mit den var_dump()s und der Exception in einer Debug Umgebung wird versucht mitzuteilen, was hier genau in den Daten nicht stimmt. Aber in den logs fehlt diese Information leider. Ein weiterer Grund dafür, eine richtige Logging Lösung wie zB https://github.com/Seldaek/monolog zu verwenden

**Comment by ralferlebach** [comment]
Ich denke, das hat sich jetzt mit https://github.com/Wunderbyte-GmbH/moodle-mod_adaptivequiz/pull/14 alles endgültig geklärt.
