### ISSUE TITLE
Fehler nach Ablauf der maximalen Fragenanzahl

### ISSUE THREAD

**Issue by Dmfama20** [Wunderbyte-GmbH/moodle-local_catquiz#605]
In den Testeinstellungen habe ich angegeben, dass maximal 15 Fragen in einem Test gestellt werden sollen und ebenfalls maximal 15 Fragen pro Skala. Der akezptierte Standardfehler wurde zwischen 0.35 und 1 nicht vertändert. Nach der 15 Frage bekommt der Getestete dei folgende Fehlermeldung angezeigt.
![Bildschirmfoto 2024-08-07 um 15 33 48](https://github.com/user-attachments/assets/6a60e390-609e-49fe-98eb-d7e7dade70a4)

**Comment by ralferlebach** [comment]
Wir haben gerade nachgesehen: Es ist diese (letzte getaggte) Version im Einsatz:

https://github.com/Wunderbyte-GmbH/moodle-adaptivequizcatmodel_catquiz/releases/tag/2024062800

**Comment by davidszkiba** [comment]
@ralferlebach Das ist seltsam, denn in dieser getaggten Version kommt in Zeile 47 von catmodel/catquiz/lib.php nicht dieser Aufruf aus der Fehlermeldung vor: https://github.com/Wunderbyte-GmbH/moodle-adaptivequizcatmodel_catquiz/blob/2024062800/lib.php#L47

**Comment by Dmfama20** [comment]
Wir haben die Version 2024070802 installiert

**Comment by davidszkiba** [comment]
@Dmfama20 das ist die Version vom local_catquiz plugin. Ich denke das Problem liegt aber beim catmodel subplugin - das sollte sich in mod/adaptivequiz/catmodel/catquiz befinden.

**Comment by davidszkiba** [comment]
Hier der Link zur letzten Version: https://github.com/Wunderbyte-GmbH/moodle-adaptivequizcatmodel_catquiz/releases/tag/1.0.2

**Comment by ralferlebach** [comment]
Solllte mit dem "Gesamtpaket" in GitHub
https://github.com/Wunderbyte-GmbH/moodle-mod_adaptivequiz/tree/alise_adaptivequiz

behoben sein.
