### ISSUE TITLE
Item zu Skala hinzufügen funktioniert nicht

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#611]
Beim Versuch, ein neues Item zu einer bestehenden Skala manuell hinzuzufügen...
<img width="1430" alt="grafik" src="https://github.com/user-attachments/assets/7438b736-7a70-434b-a22f-04b1ad767f68">

... entsteht ein Circle of Death
<img width="1162" alt="grafik" src="https://github.com/user-attachments/assets/7067f38c-9101-4592-b5b5-6f7cd7c7fe20">

Steht vermutlich in Verbindung mit der zu behebenden SQL-Abfrage in catquiz.php
https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/tree/584-sql-fix-addcatscalequestions

**Comment by ralferlebach** [comment]
@davidszkiba : Ich habe es gerade ausprobiert: Es hat nichts mit dem SQL-Snipplet in catquiz.php und den Hochkomma um context zu tun - auch nach dessen Fix ist das Endlosladen noch immer da.

**Comment by davidszkiba** [comment]
Ok, ich schau mir mal im debugger an, was da nicht funktioniert

**Comment by davidszkiba** [comment]
@ralferlebach kannst du es mit den Änderungen aus [ed468c4](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/commit/ed468c493db9de34f0530d2e62eab6cab4973623) nochmal versuchen?

**Comment by ralferlebach** [comment]
Ja, das hat es gelöst.
