### ISSUE TITLE
Wiki zu Catquiz auf Moodle.org anlegen und pflegen

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#619]
- [x] rudimentärer Anfang erstellt dh. erste Seite angelegt
- [x] 1-3 Abschnitte angelegt und befüllt
- [x] in Moodle 4.4.
- [ ] deutsch & englisch

**Comment by ralferlebach** [comment]
https://docs.moodle.org/404/de/Adaptive_Quiz_-_Advanced_CAT_Module

**Comment by ralferlebach** [comment]
https://docs.moodle.org/405/en/Adaptive_Quiz_-_Advanced_CAT_Module
