### ISSUE TITLE
ERROR: Fehlermeldungen beim Wechseln der Rolle während oder direkt im Anschluss eines Tests (auf der Feedback-Seite)

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#629]
Ist vermutlich ein Issue für mod_adaptive:

während des Tests:
![grafik](https://github.com/user-attachments/assets/ed81b902-d024-4bc9-ae2e-484cae87b386)

beim Feedback nach dem Test:
![grafik](https://github.com/user-attachments/assets/72ebb197-f705-43c6-8744-b2eebbe3adf9)

Gewechselt wurde von teacher auf student.

**Comment by davidszkiba** [comment]
@ralferlebach ich kann das so leider nicht reproduzieren.
Welche Moodle Version ist das?
Wenn ich "switch role to ..." verwende um auf "Student" zu wechseln, bekomme ich unter moodle 4.1 folgende Fehlermeldung:

![Image](https://github.com/user-attachments/assets/ef991f68-8845-4bc3-9cd5-ca48aab75f89)

Das liegt daran, dass ich nach dem Rollenwechsel auf folgende URL umgeleitet werde: http://localhost:58000/mod/adaptivequiz/attemptfinished.php?cmid=18&id=2

Wenn ich dann aber die URL setze, die vor dem Rollenwechsel verwendet worden ist, dann  funktioniert es ohne Fehler: http://localhost:58000/mod/adaptivequiz/attemptfinished.php?attempt=686&instance=2

Aber ja, ich denke auch, dass das ein issue für mod_adaptive ist, da der Fehler dort ausgelöst wird.

**Comment by davidszkiba** [comment]
Checken, ob es in normalem adaptivequiz auch so passiert. Wenn ja, issue in adaptivequiz erstellen mit Info (welche Version) und Rezept zum Reproduzieren.

**Comment by davidszkiba** [comment]
Kann bei mir gerade kein klassisches Adaptivquiz aufsetzen

**Comment by ralferlebach** [comment]
Habe das an vtos weitergegeben:

https://github.com/vtos/moodle-mod_adaptivequiz/issues/43
