### ISSUE TITLE
ERROR: Fehler in der Personenfähigkeitsbewrechung bei Alles-richtig und Alles-falsch-Szenarien

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#637]
Hier ein Beispiel auf LTI-Server, Versuch 652:
<img width="457" alt="grafik" src="https://github.com/user-attachments/assets/6bbe7a22-83c8-4cf2-bb75-3e382061fb5e">

<img width="669" alt="grafik" src="https://github.com/user-attachments/assets/0348d7de-f631-4979-bf12-8d114bf5f8ac">

Problem 1: Mit EAP-Schätzung (mittels TR-Filter) werden Personenfähigkeiten stark zum Mittelwert der Verteilung hin (unter/über-) schätzt. Das Problem ist in der Literatur soweit bekannt, wir sollten aber dennoch eine Lösung finden.

Problem 2: Trotz korrekter Antwort sinkt bei uns die PP (siehe PP-Entwicklung bis Frage 9), was nicht sein darf. Wird der TR-Filter mehrfach evtl. angewendet?

**Comment by eynimeni** [comment]
@ralferlebach meldet sich wenn das angegangen werden kann

**Comment by ralferlebach** [comment]
https://github.com/ralferlebach/CAT-Simulation/pull/3/files#diff-bffa1682189310dba3cd77facfecbc48001388f2c04fbfcd667d2a8c34a48afd

**Comment by ralferlebach** [comment]
Kann nun gern angegangen werden.
