### ISSUE TITLE
ERROR: Bilder werden in den ShortCodes nicht korrekt angezeigt

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#639]
So sollte es (wie im Feedback angezeigt) aussehen:
<img width="815" alt="grafik" src="https://github.com/user-attachments/assets/e8e52273-d1df-48d7-89ff-b91a55972e3a">

So sieht es im ShortCode tatsächlich aus:
<img width="741" alt="grafik" src="https://github.com/user-attachments/assets/aae7f924-b7a9-43fa-b0bd-a9d1b455383c">

Und das ist der Grund: brokenfile.php
<img width="688" alt="grafik" src="https://github.com/user-attachments/assets/61b84271-0221-4f88-8279-a489e2c4cc0c">

**Comment by eynimeni** [comment]
TO DO: test at alise.wunderbyte.at (alise2.wunderbyte.at) @davidszkiba

**Comment by davidszkiba** [comment]
Auf alise.wunderbyte.at getestet - Bild wird im direkten Feedback und im Feedback via Shortcode angezeigt :)

![Image](https://github.com/user-attachments/assets/30fe1f43-120b-4dc6-95dc-9f3c7852bad7)
