### ISSUE TITLE
ERROR: Rückmeldungen zu angeblichen Personenfähigkeiten nach NULL Fragen oder zu wenig tatsächlichen Antworten

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#649]
Bei der Teststrategie "Alle Skalen abtesten" kam es jetzt zu dem Vorfall, dass obwohl - im Extremfall - keine einzige Antwort gegeben wurde, ziemlich gute Fähigkeiten bescheinigt wurden:

Keine Frage beantwortet, trotzdem "gutes" Ergebnis (# 801):
<img width="733" alt="grafik" src="https://github.com/user-attachments/assets/5b27fdf0-55ef-46d6-bd83-61335f84ea9a">
<img width="704" alt="grafik" src="https://github.com/user-attachments/assets/87ac6227-377f-4a09-ac06-f5ab280bac72">

Feedback trotz zu geringer Frageanzahl (# 805):
<img width="729" alt="grafik" src="https://github.com/user-attachments/assets/afffbbb5-8823-4ed7-971e-a58cbd95023b">
<img width="711" alt="grafik" src="https://github.com/user-attachments/assets/11786847-65f4-4843-882a-e3320af24a97">

Alles (1 Frage) falsch (802):
<img width="737" alt="grafik" src="https://github.com/user-attachments/assets/623e1c52-5c29-45df-b27c-3d5538e4c5a9">
<img width="696" alt="grafik" src="https://github.com/user-attachments/assets/71921364-7a42-4c72-ac6a-0caea2f3bc9e">

**Comment by davidszkiba** [comment]
@ralferlebach ich hab mir das nochmal angeschaut:
Wenn ich mich richtig erinnere, dann haben wir besprochen, dass bei dieser Strategie immer alle Ergebnisse angezeigt werden sollen.
Das ist die entsprechende Stelle aus dem 07_teststrategie_tester.php Skript ($valid_result wird immer auf true gesetzt):

```php
    foreach ($pp_calc as $scale => $value) {

        $valid_result = false;
        // Teste, ob das Ergebnis das valide Diagnose-Resultat ist
        if ($value && (strlen($scale)>strlen($scale_root) + 2) && ($N_calc[$scale] >= $N_min) && ($se_calc[$scale] <= $se_max)) {
            // für gewöhnlich (radCAT, strenCAT, defCAT, relScales): Mindestanzahl an Fragen und unter max. SE

            if ($test_strategie === 'defCAT') {
                // NOTE: Bei Defizit-CAT muss Skalen-PP kleiner gleich als Global-PP sein und mittlere Fraction < 1,
                // akzeptiere nur die erste Skala
                $valid_result = ($n && ($f_calc[$scale] < 1) && ($value <= $pp_calc[$scale_root]));
            }

            elseif ($test_strategie === 'strenCAT') {
                // NOTE: Bei Stärken-CAT muss Skalen-PP größer gleich als Global-PP sein und mittlere Fraction > 0,
                // akzeptiere nur die erste Skala
                $valid_result = ($n && ($f_calc[$scale] > 0) && ($value >= $pp_calc[$scale_root]));
            }

            else {
                // NOTE: Ansonsten akzeptiere nur Skalen, die gemischt beantwortet wurden (mittlere Fraction nicht 0 oder 1)
                $valid_result = (round($f_calc[$scale],0) !== $f_calc[$scale]);
            }
        }
        if ($test_strategie === 'classTest' || $test_strategie === 'allScales') {
            // NOTE: Bei klassischem Test und Alle Skalen werden alle Skalen bedingungslos angegeben
            $valid_result = true;
        }

        if ($valid_result) {
            echo "<br> Skala ".$scale." PP: ".round($value, 2)." (".round($se_calc[$scale], 2).") mit ".$N_calc[$scale]." Items und ".round($f_calc[$scale], 2)." mittlerer Punktzahl";

...
```

Bei der allscales Strategie wird das Ergebnis also *immer* angezeigt.

Soll es doch gewisse Ausnahmen geben, in denen kein Ergebnis angezeigt wird?

**Comment by davidszkiba** [comment]
Die Scores und Standardfehler werden schon ausgeblendet, was noch fehlt ist, dass die Feedbacks ebenfalls nicht angezeigt werden.
