### ISSUE TITLE
IMPROVEMENT: Skalen in der Strategie "AllScales" (vorübergehend) deaktivieren...

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#654]
... , solange sie die Mindestfragenanzahl erreicht und andere Skalen noch nicht erreicht haben. Danach wieder aktivieren und im Test weiterlaufen lassen.

**Comment by eynimeni** [comment]
Wenn in einer Skala die Mindestfragenanzahl erreicht ist, werden erst wieder Fragen von ihr gespielt, wenn es keine ausgewählte Skala mehr gibt, wo noch weniger als die Mindestzahl an Fragen gespielt wurden

**Comment by davidszkiba** [comment]
@ralferlebach hast du schon deinen Teststrategie-Tester mit dieser Änderung upgedated? Durch diese Änderung, werden sich auch die Ergebnisse in den automatischen Tests ändern, daher bräuchte ich dafür die neuen, erwarteten Resultate.
