### ISSUE TITLE
ERROR/IMPROVEMENT: Nach dem Löschen eines AdaptiveQuizes werden auch die catquiz_attempts, aber nicht die catquiz_progress-Tabellen gelöscht

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#662]
Bitte an den Event-Listener auch die Löschung der Progress-Tabellen anhängen.

<img width="876" alt="grafik" src="https://github.com/user-attachments/assets/598b11e4-0afe-4460-ad30-70e86ae44c98">

**Comment by davidszkiba** [comment]
Diese Änderungen müssen im subplugin gemacht werden: https://github.com/Wunderbyte-GmbH/moodle-adaptivequizcatmodel_catquiz/commit/64a0fc1db6981ca7a993c906fb3b2db3855e3141
