### ISSUE TITLE
ERROR: courseid in section.php nicht verfügbar

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#669]
betrifft statistics

<img width="838" alt="grafik" src="https://github.com/user-attachments/assets/1d356dce-66e5-428f-8012-ab18c1907dbb">

und feedback

<img width="838" alt="grafik" src="https://github.com/user-attachments/assets/14a14a06-78a7-4813-807a-cdbcebe1588d">

**Comment by eynimeni** [comment]
bitte für beide shortcodes testen (feedback auch)

**Comment by davidszkiba** [comment]
ok, auch für `[catquizfeedback]` getestet
