### ISSUE TITLE
ERROR: Merkwürdige Sortierung und Grafik-Lücke bei "All relevant Scales"

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#677]
Bei "all relevant scales"-Strategie sollen die Skalen im Ergebnis nach Key (also id? Name?) geordnet werden, aber Globalskala zuerst.

In der Tabelle schaut es gut aus:
<img width="770" alt="grafik" src="https://github.com/user-attachments/assets/e1d2e42c-b271-4d0e-b3ae-1b0cf8abfe89">

In der Grafik gibt's eine Lücke, die nicht sein soll:
<img width="472" alt="grafik" src="https://github.com/user-attachments/assets/3b93f49b-9601-4ebd-bdbd-52f4f1ed7beb">

Und in den Text-Feedbacks eine andere Anordnung (Globalskala zuerst, wie gewünscht):
<img width="799" alt="grafik" src="https://github.com/user-attachments/assets/c228919c-e687-4f06-8628-f63f7690364f">

**Comment by eynimeni** [comment]
Textausgabe Sortierungen wie in Tabelle: 1. Globalskala, dann alle anderen alphabetisch nach Name

**Comment by ralferlebach** [comment]
Letztes Bild.
D01
C04
B03
C09

**Comment by davidszkiba** [comment]
Ok, also geht es  um den Bereich über den Tabs:

![Image](https://github.com/user-attachments/assets/160f17d9-d0c6-450e-9acc-965fbf403aaa)

Ich hab den code jetzt so upgedated, dass diese Text anhand des Namens der zugehörigen Skala sortiert werden.
