### ISSUE TITLE
ERROR: Zeitangabe bei Statistik-Shortcode auf Grundlage der scakeid verschwunden

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#679]
<img width="769" alt="grafik" src="https://github.com/user-attachments/assets/242bb544-9acc-42cd-9501-6b1ffd8ecb3f">

vs.

<img width="783" alt="grafik" src="https://github.com/user-attachments/assets/edb815cc-fd4d-4c27-9b05-1024b6f4947f">

**Comment by eynimeni** [comment]
wenn filter in shortcode angegeben wird, sollte dieser auch transparent gemacht werden wenn mehrere tests verwendet werden
