### ISSUE TITLE
Berechnung der Ability mit politomen Items testen (@ralferlebach liefert noch Testdaten)

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#681]

**Comment by ralferlebach** [comment]
Sollte doch mit #689 erledigt sein, oder benötigen wir noch weitere Test-Daten?

**Comment by davidszkiba** [comment]
> Sollte doch mit [#689](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/pull/689) erledigt sein, oder benötigen wir noch weitere Test-Daten?

Ja stimmt...
