### ISSUE TITLE
get_suffix call unknown

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#688]
Hi Ralf, 

ich war gerade dabei auf meinem System catquiz neu zu installieren und hab mir dabei die neueste Version des Forks von adaptivequiz geholt.

Hier ist allerdings ein Fehler drinnen, die von dir von 1 Monat eingefügte funktion get_suffix() ist bei mir leider nicht vorhanden. 
Ich bin noch auf Moodle 4.1 
Ich kann somit weder Settings eines bestehenden Quizzes aufrufen, noch ein neues anlegen. 

Wenn man den suffix raus nimmt, funktioniert es wieder.

Ich verstehe nicht ganz, wozu der Suffix eingeführt wurde. Muss man hier evt. noch eine Rückwärts-Komptabilität schaffen?

![Screenshot 2024-10-03 at 10 15 56](https://github.com/user-attachments/assets/55d3925a-ae87-4857-a6d3-fa69187436cb)

![Screenshot 2024-10-03 at 10 15 31](https://github.com/user-attachments/assets/0a026120-8c6d-4960-8d0e-36fce9da5f1c)

**Comment by ralferlebach** [comment]
Das ist eine Moodle-Änderung in der Behandlung der Abschlusskriterien. Wenn diese zum Problem wird , muss die Moodle-Funktion abgefangen werden und der Fall versionsspezifisch gehandlet werden.
https://github.com/vtos/moodle-mod_adaptivequiz/issues/36
