### ISSUE TITLE
CSV-Import über CAT-Manager -> Fehler "Label .... is not unique"

### ISSUE THREAD

**Issue by Dmfama20** [Wunderbyte-GmbH/moodle-local_catquiz#693]
Hallo zusammen,

ich habe über den CAT-Manager eine CSV-Datei zur Item-Erstellung importiert: 
[IGCHE-A1.csv](https://github.com/user-attachments/files/17322678/IGCHE-A1.csv)

Das obige Beispiel ist gekürzt. Beim Original mit mehr als 1000 Einträgen habe ich nach ca einer Minute Wartezeit einen leeren Fehler erhalten: 
<img width="791" alt="Screenshot 2024-10-08 at 13 05 10" src="https://github.com/user-attachments/assets/3a880e2a-c45b-431a-91d1-fc4b78a71075">

Das eigentliche Problem ist aber, dass nach dem Upload der CSV zahlreiche Fehler ausgegeben werden:
<img width="607" alt="Screenshot 2024-10-09 at 13 03 43" src="https://github.com/user-attachments/assets/3e3a0cd5-2e2b-4e60-b2ad-b2ba53cfb9d1">

Eine Adminer-Abfrage zeigt jedoch, dass die Labels unique sind. Diese existieren nur mehrfach bzgl mehrerer Frageversionen:
<img width="1282" alt="Screenshot 2024-10-09 at 13 29 32" src="https://github.com/user-attachments/assets/5ae4fb3f-9b13-4067-8b4c-04335d3657cb">

D.h. vermutlich wird im Code nicht auf die letzte Version einer Frage zugegriffen, sondern auf alle.

**Comment by davidszkiba** [comment]
@Dmfama20 danke fürs Bescheid geben und den Hinweis mit den Question Versions, ich werd mir das anschauen

**Comment by eynimeni** [comment]
Ralf definiert ggf. noch ein gewünschtes Verhalten, falls das noch abweicht. Vorerst kann es so bleiben. Änderungswünsche in neues Issue.
Problem könnte sein, dass alte Itemids nicht mehr verfügbar sind und für Berechnungen dann Fehler passieren.
