### ISSUE TITLE
VERIFICATION: Bilder in Feedbacks

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#695]
Bzgl. #675 und #639 in Kombination mit #362:

Bitte prüfen, ob Bilder in Feedbacks jetzt bereits beim ersten Speichern ordentlich verarbeitet werden, bei erfolgreicher Testung eingebaute Warnmeldung entfernen/deaktivieren.

**Comment by davidszkiba** [comment]
Der PR mit den notwendigen Änderungen in mod_adaptivequiz ist nicht im upstream repository akzeptiert worden, daher denke ich, dass wir hier auch nicht darauf aufbauen sollten. Der PR ist oben verlinkt. Evtl wird er in anderer Form noch umgesetzt und dann können wir unser plugin dementsprechend anpassen.

**Comment by ralferlebach** [comment]
@davidszkiba : Doch doch, das bekommen wir noch hin.
Technisch ist es gar nicht anders möglich, als den Kontext sich an der Stelle (oder vorher) anzulegen und einzuholen - und mehr brauchen wir doch nicht.
