### ISSUE TITLE
SPRINTZIEL: Release 1.1.1 vorbereiten und releasen

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#698]
ZIEL!

see also #600 

- [x] phpUnit TEsts auch für Moodle 405 grün

**Comment by davidszkiba** [comment]
Ein aktueller develop branch ist gepusht, mit einer neuen internen Versionsnummer `2024102500`. Ralf testet noch und dann wird eine neue Release 1.1.1 samt git tag erstellt.

**Comment by davidszkiba** [comment]
- Stale JS files fixen, damit develop wieder gruen ist
- 4.5 in plugin directory als unterstuetzt markieren
- Genauso PHP 8.3
- External documentation auf wiki verlinken: siehe #619
