### ISSUE TITLE
ERROR: Import - must be valid object or a string

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#703]
Fehler beim Import folgender Datei:
[Itemparameter.csv](https://github.com/user-attachments/files/17366184/Itemparameter.csv)

<img width="717" alt="grafik" src="https://github.com/user-attachments/assets/739f7b17-a415-48a4-b606-b436e531e805">

Error code: generalexceptionmessage
* line 174 of /local/catquiz/classes/local/model/model_item_param.php: Error thrown
* line 191 of /local/catquiz/classes/local/model/model_item_param.php: call to local_catquiz\local\model\model_item_param->__construct()
* line 508 of /local/catquiz/classes/local/model/model_item_param_list.php: call to local_catquiz\local\model\model_item_param::from_record()
* line 455 of /local/catquiz/classes/local/model/model_item_param_list.php: call to local_catquiz\local\model\model_item_param_list::save_or_update_testitem_in_db()
* line 280 of /local/catquiz/classes/import/fileparser.php: call to local_catquiz\local\model\model_item_param_list::save_or_update_testitem_in_db()
* line 224 of /local/catquiz/classes/import/fileparser.php: call to local_catquiz\import\fileparser->execute_callback()
* line 57 of /local/catquiz/classes/importer/testitemimporter.php: call to local_catquiz\import\fileparser->process_csv_data()
* line 145 of /local/catquiz/classes/form/csvimport.php: call to local_catquiz\importer\testitemimporter::execute_testitems_csv_import()
* line 75 of /lib/form/classes/external/dynamic_form.php: call to local_catquiz\form\csvimport->process_dynamic_submission()
* line ? of unknownfile: call to core_form\external\dynamic_form::execute()
* line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

**Comment by eynimeni** [comment]
die erste zeile ist mit strichpunkt ";" getrennt, die anderen datensätze dann mit komma ","
vielleicht lässt es sich mit einer korrektur der separatoren lösen?

**Comment by ralferlebach** [comment]
OK, User-Problem weil Problem-User
