### ISSUE TITLE
ERROR: ggrm verursacht Fehlermeldungen

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#706]
<img width="1167" alt="grafik" src="https://github.com/user-attachments/assets/7cbfdb70-4398-439c-973e-299e7354c7de">

    line 153 of /local/catquiz/catmodel/grmgeneralized/classes/grmgeneralized.php: TypeError thrown
    line 292 of /local/catquiz/classes/local/model/model_item_param.php: call to catmodel_grmgeneralized\grmgeneralized::get_difficulty()
    line 293 of /local/catquiz/classes/local/model/model_item_param_list.php: call to local_catquiz\local\model\model_item_param->get_difficulty()
    line ? of unknownfile: call to local_catquiz\local\model\model_item_param_list->local_catquiz\local\model\{closure}()
    line 291 of /local/catquiz/classes/local/model/model_item_param_list.php: call to array_map()
    line 93 of /local/catquiz/classes/output/catscaledashboard.php: call to local_catquiz\local\model\model_item_param_list->get_values()
    line 209 of /local/catquiz/classes/output/catscaledashboard.php: call to local_catquiz\output\catscaledashboard->render_itemdifficulties()
    line 170 of /local/catquiz/classes/output/catscales.php: call to local_catquiz\output\catscaledashboard->export_scaledetails()
    line 157 of /local/catquiz/classes/output/catscalemanager/managecatscaledashboard.php: call to local_catquiz\output\catscales->return_detailview()
    line 66 of /local/catquiz/manage_catscales.php: call to local_catquiz\output\catscalemanager\managecatscaledashboard->__construct()

**Comment by davidszkiba** [comment]
Da ist die `get_difficulty` Funktion nicht richtig implementiert.
@ralferlebach kann ich hier die gleiche Berechnung wie in GRM verwenden?
Also:

```php
    /**
     * Calculate the mean difficulty
     *
     * @param array $ip
     *
     * @return float
     *
     */
    public static function calculate_mean_difficulty(array $ip): float {
        $ip['difficulties'] = self::sanitize_fractions($ip['difficulties']);
        $fractions = self::get_fractions($ip['difficulties']);
        $kmax = max(array_keys($fractions));

        return ($ip['difficulties'][$fractions[1]] + $ip['difficulties'][$fractions[$kmax]]) / 2;
    }
```
?

**Comment by ralferlebach** [comment]
Ja, das ist das Gleiche.
