### ISSUE TITLE
ERROR: Statistics-Shortcode - Angabe einer im Kurs nicht verwendeten scaleid führt zu Error

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#719]

**Comment by ralferlebach** [comment]
<img width="939" alt="grafik" src="https://github.com/user-attachments/assets/955f0d83-6e09-4585-81a1-5081b7ba6ff9">

<img width="832" alt="grafik" src="https://github.com/user-attachments/assets/0544c38a-d992-4128-9e93-84095bd1f9f3">

**Comment by eynimeni** [comment]
Errorhandling: Fehler abfangen und stattdessen Info ausgeben

**Comment by davidszkiba** [comment]
Ich hab es nicht geschafft, genau diesen Fehler zu reproduzieren. Ich habe trotzdem den code so geändert, dass dieser Fehler nicht mehr vorkommen sollte.
