### ISSUE TITLE
Error beim Import von Test-Items

### ISSUE THREAD

**Issue by Dmfama20** [Wunderbyte-GmbH/moodle-local_catquiz#720]
Hallo zusammen, 

ich habe diese CSV 
[IGCHE-A1.csv](https://github.com/user-attachments/files/17502687/IGCHE-A1.csv)
zum Import von Test-Items verwendet. Beim Import bekomme ich den folgenden Fehler angezeigt:

generalexceptionmessage
Fehler: local_catquiz\catscale::remove_testitem_from_scale(): Argument #1 ($catscaleid) must be of type int, null given, called in [dirroot]/local/catquiz/classes/local/model/model_item_param_list.php on line 435
Datei:  ...atquiz/classes/catscale.php
Zeile:  381
Stack trace: 

Error code: generalexceptionmessage
* line 381 of /local/catquiz/classes/catscale.php: TypeError thrown
* line 435 of /local/catquiz/classes/local/model/model_item_param_list.php: call to local_catquiz\catscale::remove_testitem_from_scale()
* line 280 of /local/catquiz/classes/import/fileparser.php: call to local_catquiz\local\model\model_item_param_list::save_or_update_testitem_in_db()
* line 224 of /local/catquiz/classes/import/fileparser.php: call to local_catquiz\import\fileparser->execute_callback()
* line 57 of /local/catquiz/classes/importer/testitemimporter.php: call to local_catquiz\import\fileparser->process_csv_data()
* line 145 of /local/catquiz/classes/form/csvimport.php: call to local_catquiz\importer\testitemimporter::execute_testitems_csv_import()
* line 75 of /lib/form/classes/external/dynamic_form.php: call to local_catquiz\form\csvimport->process_dynamic_submission()
* line ? of unknownfile: call to core_form\external\dynamic_form::execute()
* line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

**Comment by ralferlebach** [comment]
![Image](https://github.com/user-attachments/assets/f4d64234-51f9-4680-b6be-9c3f2a9e3333)
