### ISSUE TITLE
ERROR: Einschreibung in Gruppen für Kurs mit CAT-Quiz

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#745]
![Image](https://github.com/user-attachments/assets/141bd7c8-e248-4eea-ad17-de95f7e3109c)

Zum Testen der Installer-Funktionen:
https://alise.wunderbyte.at/mod/adaptivequiz/view.php?id=177

**Comment by ralferlebach** [comment]
In Verbindung mit https://github.com/Wunderbyte-GmbH/Moodle-tool_wbinstaller/issues/17

**Comment by davidszkiba** [comment]
Es hat leider wirklich einen Fehler gegeben: wir haben fälschlicherweise die Kurs-ID mit einem Kurs-Namen verglichen. Was aber auch noch wichtig ist: es kann nur in Gruppen eingeschrieben werden, die zu dem Kurs gehören, in den eingeschrieben wird. Also nur in eine Gruppe einzuschreiben aber nicht in den zugehörigen Kurs funktioniert im Moment nicht.

**Comment by ralferlebach** [comment]
Kurze Verständnisrückfrage: Bedeutet das, dass in Gruppen von Kursen, in die eingeschrieben wird, erfolgt - nicht im Kurs mit dem CAT-Quiz selbst?

Was geschieht, wenn in mehr als einen Kurs eingeschrieben wird? Was, wenn in keinen Kurs eine Einschreibung erfolgt?
Ist es möglich, auch in Gruppen des Kurses mit dem CAT-Quiz einzuschreiben?

**Comment by ralferlebach** [comment]
Bitte Gruppeneinschreibung für denselben Kurs, in dem auch das CAT-Quiz liegt, noch implementieren. Danke

**Comment by ralferlebach** [comment]
PR #755
