### ISSUE TITLE
ERROR: Ladeprobleme bei großen Skalen im CAT-Manager

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#751]
Im CAT-Manager werden große Skalen (wie z.B. ALiSe Mathematik) nicht mehr geladen, sowohl die Skalen- als auch die Fragen-Ansicht.
![grafik](https://github.com/user-attachments/assets/d7bf839e-4695-4f23-850a-6386fa25ad35)

z.T. erscheint folgender Hinweis im Browser:
![grafik](https://github.com/user-attachments/assets/3283f571-109c-4e5a-be83-278a10146739)

Für kleinere Skalen aber wird es geladen:
![grafik](https://github.com/user-attachments/assets/82a9af03-fc23-4e61-9328-fcf31f94ee73)

**Comment by ralferlebach** [comment]
[Firefox 2024-11-29 09.21 profile.json.gz](https://github.com/user-attachments/files/17956361/Firefox.2024-11-29.09.21.profile.json.gz)

**Comment by ralferlebach** [comment]
Javascript-Caching deaktivieren und gemeinsam untersuchen.

**Comment by davidszkiba** [comment]
Evtl liegt es am Fähigkeitswert chart - hier müssen die Daten umgewandelt werden [Object object]

**Comment by davidszkiba** [comment]
Wir haben das Problem gefunden: Wenn man eine Skala auswählt, sieht man 2 Charts:

1. ability scores
2. item difficulties

Das Entfernen der charts aus den mustache templates (löschen der Zeile mit `{{{chart}}}`) hat nichts genutzt, weil das JS trotzdem noch ausgeführt wird.
Das Entfernen vom Code, der `$OUTPUT->render($chart)` ausführt, hat dann letztendlich geholfen.

Hier sollten wir eine Maximalanzahl an Werten, die im Chart dargestellt werden, konfigurieren.
