### ISSUE TITLE
IMPROVEMENT: Context in bestehenden Tests beibehalten EDIT: in #723 enthalten

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#752]
Aktuell: Tests beziehen aus CAT-Scale den Context

Benötigt: Auch bei neuen Kontexten (Versionen, z.B. durch Import) müssen Tests mit dem Context weiter laufen, mit dem diese angelegt wurden, um Ergebnisse vergleichbar zu halten.

Einfügen: Datenfeld Context in local_catquiz_test, aus dem dieses Information bezogen wird, prüfen, ob in catquiz_progress der Context abgelegt wird

**Comment by davidszkiba** [comment]
Das habe ich als Teil von issue 723 umgesetzt, siehe zB commit https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/pull/771/commits/7d6244bad40922ee662071b845d52ce8db0864bc der im branch dev-david-issue-723 enthalten ist

**Comment by davidszkiba** [comment]
Ist in #723 enthalten
