### ISSUE TITLE
Eigene attempt Seite in local catquiz

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#757]
Anstatt die Seite von mod_adaptivequiz zu verwenden, eigene Seite in local_catquiz hinzufuegen

Query params:
- KEINE: alle attempts vom aktuellen user anzeigen
- attemptid: den angegebenen Attempt anzeigen, wenn er vom aktuellen user ist oder wenn der eingeloggte user die capability hat, fremde attempts zu sehen
- userid: alle attempts vom user, wenn der eingeloggte user die ability hat, fremde attempts zu sehen. Wenn es die eigene userid ist, geht es natürlich auch

Am einfachsten ist es wohl, die attempt mit dem shortcode und `format_text()` auszugeben

**Comment by ralferlebach** [comment]
Da der Filter Shortcode nicht zwingend für den Betrieb von AliSe/AdeLe ist, wäre eine Lösung ohne Shortcode günstiger.

Zudem ist die Frage, inwiefern Zugriffsberechtigungen notwendig zu prüfen wären.

Folgendes habe ich soeben magdalena geschrieben:
"Die Seite sollte m.E. nur das entsprechende Feedback enthalten und in einem neuen Tab öffenen. Keine Navigtioin o.ä. zurück zum Test oder Kurs oder so - es sei denn, wir wollen, dass die TN aus dem Lernpfad "weglaufen". (Sollten wir nächste Woche besprechen.)

Eine (bessere?) Alternative wäre auch, das Feedback direkt in ein modal zu rendern, sodass man dieses einsehen kann, ohne die Lernpfadseite zu verlassen bzw. zu dieser zurückkommen zu müssen."
