### ISSUE TITLE
ERROR: Installation setzt Manager als CAT-Manager ein

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#776]
Vorgehen:

1. neue Moodle-Instanz
2. Nutzer anlegen und denen die globale (System-) Rolle Manager zuweisen
3. ALiSe-Plugins installieren
4. CAT-Manager öffnen

Erwartet:
NUR CAT-Manager dürfen den CAT-Manager einsehen

ToDo
 [ ] Setzen der Capabilities bei Installation prüfen
 [ ] Zugriffsbeschränkung des CAT-Managers prüfen

**Comment by davidszkiba** [comment]
Beim Installieren des Plugins haben wir bisher das Recht so gesetzt, dass manager auch CAT Scale manager sind:

```        'local/catquiz:canmanage' => [
            'captype' => 'write',
            'contextlevel' => CONTEXT_SYSTEM,
            'archetypes' => [
                'manager' => CAP_ALLOW,
            ],
        ],
```

Wenn du möchtest, können wir den archetype rausnehmen. Dann haben bei der Erstinstallation nur Admins Zugriff auf die CAT scales.
Tendenziell würden wir es eher so lassen wie es ist

**Comment by ralferlebach** [comment]
@ralferlebach : Strings anpassen.
catquiz Manager
Catquiz VerwalterIn

**Comment by ralferlebach** [comment]
Im Branch "ralferlebach-fix-languagestrings" sind die gewünschten Änderungen (und andere sprachlichen Fixes) bereits enthalten.

https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/tree/ralferlebach-fix-languagestrings
