### ISSUE TITLE
Item-Parameter als private variables in der entsprechenden Klasse?

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-local_catquiz#78]
Wäre es nicht sinnvoll die (modell-spezifischen) Itemparameter als Vektor/Array in der Klasse mittels private Vars unterzubringen und diese durch einen Constructor sauber zu initialisieren sowie mittels Getter und Setter aus- und einlesen zu lassen?

Dies würde eine einheitliche Architektur innerhalb der Vererbung zulassen und die Item-Parameter müssten nicht aufwändig per Funktionsparameter durchgereicht werden.

**Comment by davidszkiba** [comment]
Es gibt für Itemparameter eine eigene Klasse `model_item_param`: https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/blob/develop/classes/local/model/model_item_param.php Zusätzlich gibt es im gleichen Namespace eine `item_param_list` Klasse, die dafür zuständig ist, gespeicherte Parameter aus der Datenbank zu lesen bzw neue Parameter in der Datenbank zu speichern.
Entsprechende Klassen gibt es im gleichen Namespace auch für Personenparameter.

Meine Motivation war, die Funktionalität zu trennen - die Aufgabe von einer Modell Klasse unterscheidet sich von der Aufgabe einer Itemparameter Klasse. Siehe zB auch https://www.google.com/search?q=composition+over+inheritance
