### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#82]
- [x] Click view action in item list
- [x] Implement edit & delete item I n items list -> this is worked on in #50 
- [x] Filter item parameter graphs: show only item parameters for items that are assigned to the selected catscale
- [x] Filter person parameter graph: show only person parameters of the selected catscale
- [x] Number of pilot questions in attemptfeedback is not correct (incorrect value 0 shown if pilot questions were shown)

**Comment by davidszkiba** [comment]
Regarding the last point: A new scale does not have test items, but the "stats" tab does still show graphs of item parameters. This is because item parameters are calculated *per context*. @georgmaisser Maybe it would be less confusing to display the graphs on a different page?

**Comment by eynimeni** [comment]
maybe recheck if questionssummary is correct

**Comment by davidszkiba** [comment]
Number of pilotquestions is not shown: it's just correct/incorrect/partly correct. Unanswered questions are counted as incorrect.
