### ISSUE TITLE
teststrategies: infer all subscales

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#85]
The CAT test is active until all subscales can be calculated via DPF:

> Der CAT-Test wird solange durchgeführt, bis alle Subskalen hinreichend (mittels DPF als erwartungskonform oder unter- bzw. überperformant) bestimmt sind

Select relevant subscales via: -> see new issue #162
~~- [ ] min (left) or right (max) inflection point~~
~~- [ ] min/max difficulty of all items~~
~~- [ ] threshold left/right in test information curve~~
~~- [ ] user defined~~

> Auswahl der relevanten Subskalen mittels
min(linker) und max(rechter) Wendepunkt aller Items
min/max(Schwierigkeit) aller Items
Schwellwert li./re. in Test-Informationskurve
frei nutzerdefiniert

Exclude a subscale:
- [x] if it is not relevant due to person parameters
- [x] If the standard error per subscale falls below a threshold
- [x] max number of items to be shown per scale is exceeded for a given subscale
- [x] ... but not if the minimum number of items per subscale is not reached yet (default 0)

> Ausschluss einer Subskala
wenn aufgrund der PP nicht relevant (siehe letzte Folie)
Standardfehler pro Subskala unterschritten
max. Anzahl der anzuzeigenden Items pro Skala für diese Subskala überschritten
aber nicht, wenn
Mindestanzahl von Items pro Subskala noch nicht erreicht (Default: 0)

#### Exclusion of subscales

- [x] Calculate standard error per scale. Show it as part of debuginfo feedback
- [x] Use standard error to mark a scale and its questions as excluded
- [x] Exclude based on min/max number of questions per scale

#### Selection of subscale

...

**Comment by davidszkiba** [comment]
@ralferlebach könntest du mir da noch genauer erklären, wie die Auswahl der relevanten Subscales funktionieren soll?
Besonders diesen Teil:
> Auswahl der relevanten Subskalen mittels
min(linker) und max(rechter) Wendepunkt aller Items
min/max(Schwierigkeit) aller Items
Schwellwert li./re. in Test-Informationskurve
frei nutzerdefiniert

**Comment by davidszkiba** [comment]
@ralferlebach Ist folgende Formel zum Berechnen des Standardfehlers pro Skala korrekt?

```
standarderror = 1 / sqrt(SUM(fisherinformation))
```

wobei SUM die fisher information aller Fragen in der jeweiligen Skala aufsummiert?

**Comment by davidszkiba** [comment]
@georgmaisser  @ralferlebach Ich gehe davon aus, dass zum Berechnen des Standarderrors pro Subskala auch alle bereits gespielten Fragen berücksichtigt werden.
Sollen dann für diese Teststrategie bereits gespielte Fragen aus dem Fragenpool entfernt werden oder nicht? Da es ja auch eine Mindestanzahl an Fragen pro Skala geben soll, kann es nämlich dazu kommen, dass eine Frage mehr als einmal angezeigt werden muss. Zum Beispiel wenn ein Minimum von 5 Fragen pro Skala angegeben ist, aber eine Skala nur 3 Fragen hat.

**Comment by georgmaisser** [comment]
Me. kann es nie so sein, dass eine Frage in einem Test 2x kommt. Es ist besser, kein Ergebnis zu haben als so ein Verhalten. Das invalidiert ja auch alle Ergebnisse für so eine Frage. @ralferlebach , wie siehst du das?

**Comment by ralferlebach** [comment]
> @georgmaisser @ralferlebach Ich gehe davon aus, dass zum Berechnen des Standarderrors pro Subskala auch alle bereits gespielten Fragen berücksichtigt werden. Sollen dann für diese Teststrategie bereits gespielte Fragen aus dem Fragenpool entfernt werden oder nicht? Da es ja auch eine Mindestanzahl an Fragen pro Skala geben soll, kann es nämlich dazu kommen, dass eine Frage mehr als einmal angezeigt werden muss. Zum Beispiel wenn ein Minimum von 5 Fragen pro Skala angegeben ist, aber eine Skala nur 3 Fragen hat.

Als Abbruchkriterium: ja, dann werden NUR die bereits ausgespielten (und beantworteten) Items in die Summenbildung einbezogen, also:
TI ($pp) = Summe aus FI ($pp) von allen n beantworteten Fragen

Für das Auswahlkriterium wäre ja die hypothetische Frage zugrunde zulegen, ob (ggf. unter Berücksichtigung der maximalen Fragenanzahl, also noch N - n offenen Möglichkeiten Fragen aus der Subskala zu stellen) der als Abbruchkriterium vorgegeben Standard-Fehler noch zu untertreffen ist.

Daher bildet sich die Summe (wie vermutet) zu:

TI ($pp) = Summe aus FI ($pp) von allen n beantworteten Fragen + Summe FI ($pp) von den (verbleibenden N - n ) Fragen mit den höchsten FI ($pp)

(Wir müssen also im Fall von festgelegtem SE UND festgelegter Maximalanzahl an Fragen pro Subkategorie N vorab die FI aller verbleibenden Items einer Subskala in eine Liste aufnehmen, diese absteigend sortieren lassen und dann die N - n obersten Elemente zusammenaddieren).

**Comment by davidszkiba** [comment]
> Hallo @davidszkiba:
> 
> standarderror [SE] = 1 / sqrt (test information [TI]) = 1 / sqrt(SUM(fisherinformation [FI])) Das ist die korrekte Formel. Für den Ausschluss einer Skala wäre daher der erste Punkt vom linken und rechten Skalenrand aus zu finden, bei dem die Ungleichung gilt:
> 
> 1/SE'^2 < TI = SUM (FI)
> 
> SE' ist dabei der vorgegebene Standardfehler, der bei Unterschreitung zum Abbruch des Testverfahrens führt.
> 
> Der Schnittpunkt lsst sich mittels Nullstellensuche (also das, was wir die ganze Zeit tun) finden. Dafür benötigen wird dan aber noch die ersten Ableitungen der Fischer-Informationen.
> 
> Oder wir berechnen dies mittels Brute Force. Was meinst du?

@ralferlebach Die fisher information ist ja wiederum von der person ability und den item parametern abhängig. Meinst du mit dem "ersten Punkt vom linken und rechten Skalenrand" also die person ability, ab der diese Ungleichung gilt?
Falls ja, dann können wir das wahrscheinlich tatsächlich einfacher mittels bruteforce bzw linearer Suche herausfinden, indem ich unterschiedliche Werte für die person ability einsetze.

**Comment by davidszkiba** [comment]
> > @georgmaisser @ralferlebach Ich gehe davon aus, dass zum Berechnen des Standarderrors pro Subskala auch alle bereits gespielten Fragen berücksichtigt werden. Sollen dann für diese Teststrategie bereits gespielte Fragen aus dem Fragenpool entfernt werden oder nicht? Da es ja auch eine Mindestanzahl an Fragen pro Skala geben soll, kann es nämlich dazu kommen, dass eine Frage mehr als einmal angezeigt werden muss. Zum Beispiel wenn ein Minimum von 5 Fragen pro Skala angegeben ist, aber eine Skala nur 3 Fragen hat.
> 
> Als Abbruchkriterium: ja, dann werden NUR die bereits ausgespielten (und beantworteten) Items in die Summenbildung einbezogen, also: TI ($pp) = Summe aus FI ($pp) von allen n beantworteten Fragen

Ok, werde ich so machen.

> 
> Für das Auswahlkriterium wäre ja die hypothetische Frage zugrunde zulegen, ob (ggf. unter Berücksichtigung der maximalen Fragenanzahl, also noch N - n offenen Möglichkeiten Fragen aus der Subskala zu stellen) der als Abbruchkriterium vorgegeben Standard-Fehler noch zu untertreffen ist.
> 
> Daher bildet sich die Summe (wie vermutet) zu:
> 
> TI ($pp) = Summe aus FI ($pp) von allen n beantworteten Fragen + Summe FI ($pp) von den (verbleibenden N - n ) Fragen mit den höchsten FI ($pp)
> 
> (Wir müssen also im Fall von festgelegtem SE UND festgelegter Maximalanzahl an Fragen pro Subkategorie N vorab die FI aller verbleibenden Items einer Subskala in eine Liste aufnehmen, diese absteigend sortieren lassen und dann die N - n obersten Elemente zusammenaddieren).

Auswahlkriterium bedeutet hier, ob eine Skala überhaupt noch angezeigt werden soll?
Wenn ich es richtig verstehe und Subskalen auf diese Art ausgewählt werden, dann gehen wir davon aus, dass sich die $pp nicht mehr ändern, oder? Die $pp werden aber nach jeder neuen Antwort (sofern es keine Pilotfrage ist) neu berechnet.

**Comment by ralferlebach** [comment]
Doch doch, $pp ändert auch in jedem Schritt und die Auswahl der (noch) relevanten Subskalen muss somit bei jedem Schritt erneut geprüft werden - mit der Konsequenzenz, dass ggf. bereits ausgeschlossene Skalen wieder relevant werden können (wenn sich $pp in deren effektiven Bereich verschoben hat).

**Comment by davidszkiba** [comment]
Der Ausschluss der Skalen funktioniert jetzt. Was noch fehlt ist:

> Auswahl der relevanten Subskalen mittels
min(linker) und max(rechter) Wendepunkt aller Items
min/max(Schwierigkeit) aller Items
Schwellwert li./re. in Test-Informationskurve
frei nutzerdefiniert

**Comment by davidszkiba** [comment]
Update: Die Fragenauswahl noch Informationsgehalt - so wie es jetzt implementiert ist - kann so beibehalten werden. Die verbleibenden Punkte haben geringe Priorität. Ich erstelle dafür ein separates issue.
