### ISSUE TITLE
teststrategy: infer lowest skill gap

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#86]
The test ends if the lowest subscale (the one that underperforms significantly or to the greatest extent) can be determined via DPF
> „Der CAT-Test abgebrochen, wenn mittels DPF die unterste Subskala hinreichend bestimmt ist, die signifikant bzw. am stärksten unterperformt.“

scale to be tested selected via
- [x] PP is only calculated for scales that have a sufficient number of answers 
- [x] Abweichung ist PP (zu prüfende Skala) - PP (übergeordnete Skala)

additional abort conditions:
- standard error falls below a threshold
- maximum number of items to be viewed per scale is exceeded

### Details

Note:  A question can belong to both a scale and to one of its subscales
- Everytime a user gives an answer, calculate the person ability for the most specific subscale. At least two answers with differenct outcome (true/false) are needed in order to calculate the ability parameter.
- Selecting the next question works as follows:
    - If there is no information about ability per scale, just pick a question from the top-most scale via weighted fisher information. Otherwise:
    - Select the (sub)scale where the user has the lowest ability
   - From that scale, use the timepenalty-weighted fisher information to select the next question to be played

**Comment by ralferlebach** [comment]
Gibt es hierzu bereits einen branch?

**Comment by davidszkiba** [comment]
Jetzt gib es einen: dev-david-issue-86

**Comment by davidszkiba** [comment]
Update to description: calculate the ability only for the most specific scale per item. When the attempt is finished, we can calculate the ability for the parent scales as well.

**Comment by davidszkiba** [comment]
Next steps:

- [ ] All questions of a scale are excluded, if the maximum number of questions per scale is reached (take 10 as hardcoded default value for now)
- [ ] All questions of a scale are excluded, if the person ability for that scale does not change
- [ ] The attempt feedback includes abilities of all tested subscales
